Repository vmware-clarity/ng-clarity, pull requests merged in 2022-05, with the labels that each got.

#100 feat: enable key navigation for datagrid
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  projects/angular/src/data/datagrid/datagrid-placeholder.ts
  projects/angular/src/data/datagrid/datagrid.html
  projects/angular/src/data/datagrid/datagrid.spec.ts
  projects/angular/src/data/datagrid/datagrid.ts
  projects/angular/src/data/datagrid/helpers.spec.ts
  projects/angular/src/data/datagrid/utils/key-navigation-grid.controller.ts
Labels: cla-not-required

#101 fix(navigation): visibility of close button in tablet and mobile view
  projects/angular/src/layout/nav/_responsive-nav.clarity.scss
Labels: cla-not-required, type:fix

#102 fix(navigation): visibility of close button in tablet and mobile view
  projects/angular/src/layout/nav/_responsive-nav.clarity.scss
  projects/angular/src/layout/nav/nav-level.ts
Labels: cla-not-required

#104 feat: enable key navigation for datagrid (backport)
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  projects/angular/src/data/datagrid/datagrid-placeholder.ts
  projects/angular/src/data/datagrid/datagrid.html
  projects/angular/src/data/datagrid/datagrid.spec.ts
  projects/angular/src/data/datagrid/datagrid.ts
  projects/angular/src/data/datagrid/helpers.spec.ts
  projects/angular/src/data/datagrid/utils/key-navigation-grid.controller.ts
Labels: cla-not-required

#112 fix: fix multiple overlay nesting scenarios
  package-lock.json
  projects/angular/src/utils/variables/_variables.global.scss
  projects/demo/src/app/app.routing.ts
  projects/demo/src/app/z-index/custom-filter.demo.ts
  projects/demo/src/app/z-index/various-content/various-content.html
  projects/demo/src/app/z-index/various-content/various-content.ts
  projects/demo/src/app/z-index/z-index.demo.html
  projects/demo/src/app/z-index/z-index.demo.module.ts
  projects/demo/src/app/z-index/z-index.demo.ts
  projects/demo/src/app/z-index/z-index.routing.ts
Labels: cla-not-required

#117 fix: fix multiple overlay nesting scenarios (backport)
  package-lock.json
  projects/angular/src/utils/variables/_variables.global.scss
  projects/demo/src/app/app.routing.ts
  projects/demo/src/app/z-index/custom-filter.demo.ts
  projects/demo/src/app/z-index/various-content/various-content.html
  projects/demo/src/app/z-index/various-content/various-content.ts
  projects/demo/src/app/z-index/z-index.demo.html
  projects/demo/src/app/z-index/z-index.demo.module.ts
  projects/demo/src/app/z-index/z-index.demo.ts
  projects/demo/src/app/z-index/z-index.routing.ts
Labels: cla-not-required

#115 chore: update demo app to use shim
  package-lock.json
  package.json
  projects/demo/src/app/app.component.html
  projects/demo/src/app/app.component.ts
  projects/demo/src/app/content-container.component.ts
  projects/demo/src/styles.scss
Labels: cla-not-required

#132 fix(datagrid): update detail pane close icon color to match modal
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
Labels: cla-not-required

#131 chore: update `prepare` script to work on windows
  package.json
Labels: cla-not-required, type:chore, scope:build

#135 fix(modal): disconnect the resize observer once the modal body is removed (v12 backport)
  projects/angular/src/modal/modal-body.ts
Labels: cla-not-required, type:fix, backport

#136 fix(datagrid): add role=gridcell to row detail element
  projects/angular/src/data/datagrid/datagrid-row-detail.spec.ts
  projects/angular/src/data/datagrid/datagrid-row-detail.ts
Labels: cla-not-required, type:fix

#137 fix(datagrid): add role=gridcell to row detail element (backport)
  projects/angular/src/data/datagrid/datagrid-row-detail.spec.ts
  projects/angular/src/data/datagrid/datagrid-row-detail.ts
Labels: cla-not-required, type:fix, backport
