Repository vmware-clarity/ng-clarity, pull requests merged in 2022-04, with the labels that each got.

#56 deploy forked demos
  .github/workflows/build.yml
  .github/workflows/demo.yml
Labels: cla-not-required, type:chore

#60 Topic/bump npm 12
  .github/workflows/build.yml
  .github/workflows/preview.yml
  .github/workflows/release.yml
  docs/CONTRIBUTING_DEVELOPMENT.md
  package-lock.json
  package.json
Labels: cla-not-required, type:chore

#58 deploy forked demos (12.x)
  .github/workflows/build.yml
  .github/workflows/demo.yml
Labels: cla-not-required, type:chore, backport

#59 chore: remove run-func build dependency - 12
  package-lock.json
  package.json
  scripts/get-changed-files.js
Labels: cla-not-required, type:chore, backport

#54 (backport) fix(vertical-nav): use sr-only css for collapsed link text
  projects/angular/src/layout/vertical-nav/_vertical-nav.clarity.scss
Labels: cla-not-required, type:fix, backport

#66 chore: add stale and inactive threads workflows
  .github/workflows/label-stale-threads.yml
  .github/workflows/lock-inactive-threads.yml
Labels: cla-not-required, type:chore

#70 fix: provide a way to change placeholder and aria-label for builtin filters
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/built-in/filters/datagrid-numeric-filter.spec.ts
  projects/angular/src/data/datagrid/built-in/filters/datagrid-numeric-filter.ts
  projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.spec.ts
  projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.ts
  projects/angular/src/data/datagrid/datagrid-column.ts
Labels: cla-not-required

#65 chore: report failure if demo fails to upload
  .github/workflows/demo.yml
Labels: cla-not-required, type:chore

#67 topic/get changed files fixes
  package.json
  scripts/get-changed-files.js
Labels: cla-not-required, type:chore

#68 chore: match dot folders with stylelint
  package.json
Labels: cla-not-required, type:chore

#75 (backport) fix(wizard): move wizard focus after page change
  projects/angular/src/wizard/providers/wizard-navigation.service.spec.ts
  projects/angular/src/wizard/providers/wizard-navigation.service.ts
  projects/angular/src/wizard/wizard.spec.ts
  projects/angular/src/wizard/wizard.ts
Labels: cla-not-required

#81 fix(navigation): add aria-hidden attributes to hidden elements
  projects/angular/src/layout/nav/nav-level.spec.ts
  projects/angular/src/layout/nav/nav-level.ts
Labels: cla-not-required, type:fix

#78 chore: build sync v12
  .browserslistrc
  .czrc
  .github/workflows/build.yml
  .github/workflows/label-stale-threads.yml
  .github/workflows/lock-inactive-threads.yml
  README.md
  api-extractor.json
  docs/BUILD.md
  docs/CONTRIBUTING.md
  docs/CONTRIBUTING_DESIGN.md
  docs/CONTRIBUTING_DEVELOPMENT.md
  docs/CONTRIBUTING_DOCUMENTATION.md
  docs/CONTRIBUTING_ISSUES.md
  logo.png
  package-lock.json
  package.json
  projects/angular/clarity.api.md
  projects/angular/package.json
  projects/demo/package.json
  projects/demo/tsconfig.json
  projects/ui/package.json
  scripts/get-changed-files.js
Labels: cla-not-required, type:chore

#73 feat(nav): add clrAriaCurrentLink directive for nav links
  projects/angular/clarity.api.md
  projects/angular/src/layout/nav/aria-current-link.spec.ts
  projects/angular/src/layout/nav/aria-current-link.ts
  projects/angular/src/layout/nav/index.ts
  projects/angular/src/layout/nav/navigation.module.ts
  projects/demo/src/app/app.component.html
  projects/demo/src/app/content-container.component.ts
Labels: cla-not-required

#61 feat: add demo for tree-view-type-ahead
  projects/angular/clarity.api.md
  projects/angular/src/clr-angular.module.ts
  projects/angular/src/data/tree-view/models/tree-node.model.ts
  projects/angular/src/data/tree-view/tree-focus-manager.service.spec.ts
  projects/angular/src/data/tree-view/tree-focus-manager.service.ts
  projects/angular/src/data/tree-view/tree-node.spec.ts
  projects/angular/src/data/tree-view/tree-node.ts
  projects/angular/src/data/tree-view/tree.spec.ts
  projects/angular/src/popover/common/abstract-popover.spec.ts
  projects/angular/src/utils/focus/key-focus/util.ts
  projects/angular/src/utils/for-type-ahead/for-type-ahead.module.ts
  projects/angular/src/utils/for-type-ahead/for-type-ahead.service.ts
  projects/angular/src/utils/for-type-ahead/for-type-ahead.spec.ts
  projects/angular/src/utils/for-type-ahead/for-type-ahead.ts
  projects/angular/src/utils/for-type-ahead/index.ts
  projects/angular/src/utils/index.ts
  projects/demo/src/app/tree-view/tree-view.demo.module.ts
  projects/demo/src/app/tree-view/tree-view.demo.routing.ts
  projects/demo/src/app/tree-view/tree-view.demo.ts
  projects/demo/src/app/tree-view/type-ahead/inventory.ts
  projects/demo/src/app/tree-view/type-ahead/tree-view-type-ahead.html
  projects/demo/src/app/tree-view/type-ahead/tree-view-type-ahead.ts
Labels: cla-not-required, type:feat

#74 fix: datepicker 'days' row is not set as table header
  projects/angular/src/forms/datepicker/calendar.html
Labels: cla-not-required

#80 fix: datepicker 'days' row is not set as table header (backport)
  projects/angular/src/forms/datepicker/calendar.html
Labels: cla-not-required

#84 chore: fix ci publishing (v12)
  package.json
  projects/angular/clarity.api.md
Labels: cla-not-required, type:chore

#85 fix(combobox): update aria attrs for clr-combobox
  projects/angular/src/forms/combobox/combobox.html
  projects/angular/src/utils/popover/popover-content.spec.ts
Labels: cla-not-required, type:fix

#88 fix(combobox): backport combobox a11y changes
  projects/angular/src/forms/combobox/combobox.html
Labels: cla-not-required, backport

#90 fix(navigation): visibility of navigation section when clicking on nav-link
  projects/angular/src/layout/nav/nav-level.ts
Labels: cla-not-required, type:fix

#91 (backport) fix(navigation): visibility of navigation when nav-link is clicked
  projects/angular/src/layout/nav/nav-level.ts
Labels: cla-not-required, type:fix, backport
