Repository vmware-clarity/ng-clarity, pull requests merged in 2022-03, with the labels that each got.

#2 chore: use proper project name for angular.json
  angular.json
Labels: cla-not-required

#11 chore: update branch name and urls
  README.md
  docs/CONTRIBUTING_DESIGN.md
  docs/CONTRIBUTING_DEVELOPMENT.md
  docs/CONTRIBUTING_DOCUMENTATION.md
  projects/angular/package.json
  projects/ui/package.json
Labels: cla-not-required

#13 fix: the show columns dialog contains an implicit heading vpat-795
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  projects/angular/src/data/datagrid/datagrid-column-toggle.ts
Labels: bug, cla-not-required

#19 fix: the show columns dialog contains an implicit heading vpat-795 (backport)
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  projects/angular/src/data/datagrid/datagrid-column-toggle.ts
Labels: cla-not-required

#24 chore: fix test watch npm script
  package.json
Labels: cla-not-required

#23 chore: fix test watch npm script
  package.json
Labels: cla-not-required

#15 (backport) fix(password): add screen-reader only text for password
  projects/angular/clarity.api.md
  projects/angular/src/forms/password/password-container.spec.ts
  projects/angular/src/forms/password/password-container.ts
  projects/angular/src/utils/i18n/common-strings.default.ts
  projects/angular/src/utils/i18n/common-strings.interface.ts
Labels: cla-not-required

#22 chore: add issue and PR templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/contribution-proposal.md
  .github/pull_request_template.md
Labels: cla-not-required

#30 chore(build): fix build:angular:watch script
  package.json
Labels: cla-not-required, type:chore, scope:build

#38 fix(tree-view): fix enter/space key interaction with open parent tree nodes
  projects/angular/src/data/tree-view/tree-node.ts
Labels: cla-not-required, type:fix

#45 chore: update running steps for development in the contribution docs
  docs/CONTRIBUTING_DEVELOPMENT.md
  package-lock.json
  package.json
Labels: cla-not-required

#44 (Backport) fix(dropdown): icon trigger alignment with label
  projects/angular/src/popover/dropdown/_dropdown.clarity.scss
Labels: cla-not-required, component: dropdown

#51 chore: add npx to netlify deploy workflow commands
  .github/workflows/build.yml
  .github/workflows/preview.yml
  .github/workflows/release.yml
Labels: cla-not-required, type:chore

#49 chore: remove unused version-validation script
  scripts/version-validation.js
Labels: cla-not-required, type:chore, backport

#48 chore: add npx to netlify deploy workflow commands
  .github/workflows/build.yml
  .github/workflows/preview.yml
  .github/workflows/release.yml
Labels: cla-not-required, type:chore, backport

#53 fix(vertical-nav): use sr-only css for collapsed link text
  projects/angular/src/layout/vertical-nav/_vertical-nav.clarity.scss
Labels: cla-not-required
