Repository vmware-clarity/ng-clarity, pull requests merged in 2022-07, with the labels that each got.

#212 chore: build library and watch for changes when starting demo app (backport)
  package-lock.json
  package.json
Labels: cla-not-required, type:chore, backport

#215 chore: report correct sha and branch name to chromatic
  .github/workflows/pr-visual-regression.yml
Labels: cla-not-required

#213 chore: cancel running builds if changes are pushed
  .github/workflows/pr-build.yml
Labels: cla-not-required, type:chore

#219 chore: set explicit column widths in datagrid stories
  .storybook/stories/datagrid/datagrid-action-overflow.stories.ts
  .storybook/stories/datagrid/datagrid-column.stories.ts
  .storybook/stories/datagrid/datagrid-detail.stories.ts
  .storybook/stories/datagrid/datagrid-page-size.stories.ts
  .storybook/stories/datagrid/datagrid-pagination.stories.ts
  .storybook/stories/datagrid/datagrid-placeholder.stories.ts
  .storybook/stories/datagrid/datagrid-row.stories.ts
  .storybook/stories/datagrid/datagrid.stories.ts
Labels: cla-not-required, type:chore

#217 chore: pass repo to chromatic so baseline can be found for forks
  .github/workflows/pr-visual-regression.yml
Labels: cla-not-required, type:chore

#220 chore: skip chromatic tests for changes that do not target `main`
  .github/workflows/pr-visual-regression.yml
Labels: cla-not-required, type:chore

#216 chore: add redirect for angular storybook
  netlify.toml
Labels: cla-not-required, type:chore

#214 chore: use single non-headless browser when watching tests
  karma.conf.js
Labels: cla-not-required, type:chore

#218 chore: cancel running builds if changes are pushed (backport)
  .github/workflows/pr-build.yml
Labels: cla-not-required, backport

#228 chore: update `potiuk/get-workflow-origin` action to v1_3
  .github/workflows/pr-comment-bot.yml
  .github/workflows/pr-preview.yml
  .github/workflows/pr-visual-regression.yml
Labels: cla-not-required, type:chore

#229 chore: remove outdated support link
  README.md
Labels: cla-not-required, type:chore

#235 feat(datagrid): range selection with shift key (v12 back port)
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-row.html
  projects/angular/src/data/datagrid/datagrid-row.ts
  projects/angular/src/data/datagrid/datagrid.spec.ts
  projects/angular/src/data/datagrid/datagrid.ts
  projects/angular/src/data/datagrid/providers/selection.ts
Labels: cla-not-required

#210 feat(datagrid): range selection with shift key
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-row.html
  projects/angular/src/data/datagrid/datagrid-row.ts
  projects/angular/src/data/datagrid/datagrid.spec.ts
  projects/angular/src/data/datagrid/datagrid.ts
  projects/angular/src/data/datagrid/providers/selection.ts
Labels: cla-not-required, type:feat

#240 fix(stepper): reset when form is reset but not when form is patched (backport)
  projects/angular/src/accordion/stepper/stepper.spec.ts
  projects/angular/src/accordion/stepper/stepper.ts
Labels: cla-not-required, type:fix, backport

#196 feat(datagrid): change focused action on arrow key press
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-action-overflow.ts
  projects/angular/src/data/datagrid/datagrid.module.ts
Labels: cla-not-required, type:feat

#249 chore: fetch commit in pr visual regression workflow
  .github/workflows/pr-visual-regression.yml
Labels: cla-not-required, type:chore

#251 fix(wizard): remove unnecessary vertical scroll bar
  projects/angular/src/wizard/_wizard.clarity.scss
Labels: cla-not-required

#248 feat: widen angular peer deps
  projects/angular/package.json
Labels: cla-not-required, type:feat

#252 fix(wizard): remove unnecessary vertical scroll bar (backport)
  projects/angular/src/wizard/_wizard.clarity.scss
Labels: cla-not-required, type:fix, backport

#256 fix(wizard): fix wizard content height issues
  projects/angular/src/wizard/_wizard.clarity.scss
Labels: cla-not-required

#253 feat(datepicker): indicate current day with aria-current
  projects/angular/src/forms/datepicker/day.spec.ts
  projects/angular/src/forms/datepicker/day.ts
Labels: cla-not-required, type:feat

#260 fix(combobox): force usage of css min function
  projects/angular/src/forms/combobox/_combobox.clarity.scss
Labels: cla-not-required
