Repository vmware-clarity/ng-clarity, pull requests merged in 2022-09, with the labels that each got.

#302 fix(datagrid): detail-pane overlaping the content in smaller container
  .storybook/helpers/elements.data.ts
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
Labels: cla-not-required, type:fix

#317 fix: set wizard stepnav item `aria-controls` attribute to wizard page id
  projects/angular/src/wizard/wizard-stepnav-item.spec.ts
  projects/angular/src/wizard/wizard-stepnav-item.ts
Labels: cla-not-required, type:fix

#318 fix: set wizard stepnav item `aria-controls` attribute to wizard page id (v12 backport)
  projects/angular/src/wizard/wizard-stepnav-item.spec.ts
  projects/angular/src/wizard/wizard-stepnav-item.ts
Labels: cla-not-required, type:fix, backport

#319 fix(timeline): add role="img" to timeline step icon
  projects/angular/clarity.api.md
  projects/angular/src/timeline/timeline-step.spec.ts
  projects/angular/src/timeline/timeline-step.ts
Labels: cla-not-required, type:fix

#321 Revert "chore: auto accept merged visual changes"
  .github/workflows/accept-merged-visual-changed.yml
Labels: cla-not-required

#322 chore: apply style changes in storybook watch mode
  package.json
Labels: cla-not-required, type:chore
