Repository vmware-clarity/ng-clarity, pull requests merged in 2022-10, with the labels that each got.

#327 fix(list): make unstyled list markers transparent instead of list-style-type none
  projects/angular/src/typography/_lists.scss
Labels: cla-not-required

#330 fix(list): make unstyled list markers transparent instead of list-sytle-type none (backport)
  projects/angular/src/typography/_lists.scss
Labels: cla-not-required, type:fix, backport

#340 chore: auto accept merged visual changes
  .github/workflows/accept-merged-visual-changes.yml
Labels: cla-not-required

#342 chore(datagrid): make long content optional in datagrid detail story
  .storybook/helpers/elements.data.ts
  .storybook/stories/datagrid/datagrid-detail.stories.ts
Labels: cla-not-required, type:chore

#343 feat(modal): allow custom aria-label for close button
  .storybook/stories/modal/modal.stories.ts
  projects/angular/clarity.api.md
  projects/angular/src/modal/modal.html
  projects/angular/src/modal/modal.spec.ts
  projects/angular/src/modal/modal.ts
Labels: cla-not-required, type:feat

#344 fix(stack-view): prevent page scroll when block toggled via space key
  projects/angular/src/data/stack-view/stack-block.ts
Labels: cla-not-required, type:fix

#346 chore: cancel current "Accept Merged Visual Changes" workflow runs
  .github/workflows/accept-merged-visual-changes.yml
Labels: cla-not-required

#358 chore: remove dead spinner `clrAssertive` attribute in stack view demo
  projects/demo/src/app/stack-view/stack-view-angular-lazyload.html
Labels: cla-not-required

#356 fix(forms): remove touched enforcement
  projects/angular/src/forms/common/wrapped-control.spec.ts
  projects/angular/src/forms/common/wrapped-control.ts
  projects/angular/src/forms/input/input.spec.ts
Labels: cla-not-required, type:fix

#360 fix(datepicker): validate min/max date
  projects/angular/clarity.api.md
  projects/angular/src/forms/datepicker/all.spec.ts
  projects/angular/src/forms/datepicker/date-input.validator.spec.ts
  projects/angular/src/forms/datepicker/date-input.validator.ts
  projects/angular/src/forms/datepicker/datepicker.module.ts
  projects/angular/src/forms/datepicker/index.ts
  projects/demo/src/app/datepicker/datepicker-min-max.html
Labels: cla-not-required, type:fix

#364 chore(datagrid): remove unused constructor parameters
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-column-toggle.ts
  projects/angular/src/data/datagrid/providers/selection.spec.ts
  projects/angular/src/data/datagrid/providers/selection.ts
Labels: cla-not-required, type:chore

#367 chore(date-picker): remove unused private `decadeRange` property
  projects/angular/src/forms/datepicker/yearpicker.ts
Labels: cla-not-required, type:chore

#366 chore: remove `AriaService` indirection in favor of reading ids directly
  projects/angular/clarity.api.md
  projects/angular/src/forms/combobox/combobox.ts
  projects/angular/src/forms/combobox/options.spec.ts
  projects/angular/src/forms/combobox/options.ts
  projects/angular/src/layout/tabs/tab-content.spec.ts
  projects/angular/src/layout/tabs/tab-content.ts
  projects/angular/src/layout/tabs/tab-link.directive.ts
  projects/angular/src/layout/tabs/tab.ts
  projects/angular/src/popover/tooltip/tooltip.ts
  projects/angular/src/utils/aria/aria.service.ts
Labels: cla-not-required, type:chore

#365 chore: remove `UNIQUE_ID` token in favor of `uniqueIdFactory` function
  projects/angular/clarity.api.md
  projects/angular/src/accordion/accordion-panel.spec.ts
  projects/angular/src/accordion/accordion-panel.ts
  projects/angular/src/accordion/stepper/stepper-panel.spec.ts
  projects/angular/src/accordion/stepper/stepper-panel.ts
  projects/angular/src/button/button-group/button-group.ts
  projects/angular/src/data/datagrid/datagrid-action-overflow.ts
  projects/angular/src/data/datagrid/datagrid-column-separator.ts
  projects/angular/src/data/datagrid/datagrid-column-toggle.ts
  projects/angular/src/data/datagrid/datagrid-filter.spec.ts
  projects/angular/src/data/datagrid/datagrid-filter.ts
  projects/angular/src/data/datagrid/datagrid.ts
  projects/angular/src/data/datagrid/helpers.spec.ts
  projects/angular/src/data/stack-view/stack-block.ts
  projects/angular/src/data/stack-view/stack-content-input.spec.ts
  projects/angular/src/data/stack-view/stack-content-input.ts
  projects/angular/src/data/stack-view/stack-view-custom-tags.ts
  projects/angular/src/data/tree-view/tree-node.spec.ts
  projects/angular/src/data/tree-view/tree-node.ts
  projects/angular/src/forms/combobox/option.spec.ts
  projects/angular/src/forms/combobox/option.ts
  projects/angular/src/forms/combobox/options.spec.ts
  projects/angular/src/forms/combobox/providers/combobox-focus-handler.service.ts
  projects/angular/src/modal/modal.ts
  projects/angular/src/popover/dropdown/providers/dropdown-focus-handler.service.ts
  projects/angular/src/popover/dropdown/providers/dropdown-focus-handler.spec.ts
  projects/angular/src/popover/signpost/signpost-content.ts
  projects/angular/src/popover/tooltip/tooltip-content.spec.ts
  projects/angular/src/popover/tooltip/tooltip-content.ts
  projects/angular/src/popover/tooltip/tooltip-trigger.spec.ts
  projects/angular/src/popover/tooltip/tooltip.ts
  projects/angular/src/timeline/timeline-step-title.spec.ts
  projects/angular/src/utils/focus/focusable-item/basic-focusable-item.service.ts
  projects/angular/src/utils/focus/focusable-item/basic-focusable-item.spec.ts
  projects/angular/src/utils/focus/focusable-item/custom-focusable-item-provider.ts
  projects/angular/src/utils/id-generator/id-generator.service.ts
  projects/angular/src/utils/id-generator/id-generator.spec.ts
  projects/angular/src/wizard/wizard.ts
Labels: cla-not-required, type:chore
