Repository vmware-clarity/ng-clarity, pull requests merged in 2022-06, with the labels that each got.

#144 chore: update clarity core version
  package-lock.json
  package.json
Labels: cla-not-required

#153 fix(combobox): keep focus while filtering and improve input .. back port
  projects/angular/src/forms/combobox/_combobox.clarity.scss
  projects/angular/src/forms/combobox/options.ts
  projects/angular/src/forms/combobox/providers/combobox-focus-handler.service.ts
Labels: cla-not-required, type:fix, backport

#148 chore: use correct name in pull request bot comments
  .github/workflows/bot.yml
Labels: cla-not-required

#154 chore: remove references to non-existent `clrOff` and `clrAssertive` spinner inputs
  projects/demo/src/app/spinners/spinner-component.html
Labels: type:chore

#158 feat: add placeholder to datagrid string filter (v12 backport)
  projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.spec.ts
  projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.ts
Labels: cla-not-required, type:feat, backport

#159 fix: provide a way to change placeholder and aria-label for builtin filters (v12 backport)
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/built-in/filters/datagrid-numeric-filter.spec.ts
  projects/angular/src/data/datagrid/built-in/filters/datagrid-numeric-filter.ts
  projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.spec.ts
  projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.ts
  projects/angular/src/data/datagrid/datagrid-column.ts
Labels: cla-not-required, type:fix, backport

#162 fix: overlay clipping issues
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  projects/angular/src/data/stack-view/_stack-view.clarity.scss
  projects/demo/src/app/app.routing.ts
  projects/demo/src/app/overlay-clipping/overlay-clipping.demo.html
  projects/demo/src/app/overlay-clipping/overlay-clipping.demo.module.ts
  projects/demo/src/app/overlay-clipping/overlay-clipping.demo.ts
  projects/demo/src/app/overlay-clipping/overlay-clipping.routing.ts
Labels: cla-not-required

#163 fix: overlay clipping issues (backport)
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  projects/angular/src/data/stack-view/_stack-view.clarity.scss
  projects/demo/src/app/app.routing.ts
  projects/demo/src/app/overlay-clipping/overlay-clipping.demo.html
  projects/demo/src/app/overlay-clipping/overlay-clipping.demo.module.ts
  projects/demo/src/app/overlay-clipping/overlay-clipping.demo.ts
  projects/demo/src/app/overlay-clipping/overlay-clipping.routing.ts
Labels: cla-not-required, type:fix, backport

#167 fix(vertical-nav): set min-height of nav icon
  projects/angular/src/layout/vertical-nav/_vertical-nav.clarity.scss
Labels: cla-not-required

#168 fix(vertical-nav): set min-height of nav icon (backport)
  projects/angular/src/layout/vertical-nav/_vertical-nav.clarity.scss
Labels: cla-not-required, backport

#174 chore: preserve path when hard landing on demo app url
  projects/demo/src/app/cds-theme-select.component.ts
Labels: cla-not-required, type:chore

#177 chore: add checkout step back to `demo` workflow
  .github/workflows/demo.yml
Labels: cla-not-required

#185 Revert "feat: keyboard navigation utils for list/menus"
  projects/angular/clarity.api.md
  projects/angular/src/utils/index.ts
  projects/angular/src/utils/list-key-navigation/index.ts
  projects/angular/src/utils/list-key-navigation/key-navigation-list.module.ts
  projects/angular/src/utils/list-key-navigation/key-navigation-list.spec.ts
  projects/angular/src/utils/list-key-navigation/key-navigation-list.ts
  projects/angular/src/utils/list-key-navigation/providers/focusable-items.ts
  projects/angular/src/utils/list-key-navigation/providers/key-navigation-list.config.ts
  projects/angular/src/utils/list-key-navigation/utils.ts
  projects/demo/src/app/datagrid/datagrid.demo.module.ts
  projects/demo/src/app/datagrid/full/full.html
Labels: cla-not-required

#190 chore: remove unused `@angular/cdk` dependency
  package-lock.json
  package.json
Labels: cla-not-required, type:chore

#187 chore: add datagrid stories
  .storybook/stories/datagrid/datagrid-action-overflow.stories.ts
  .storybook/stories/datagrid/datagrid-column.stories.ts
  .storybook/stories/datagrid/datagrid-detail.stories.ts
  .storybook/stories/datagrid/datagrid-page-size.stories.ts
  .storybook/stories/datagrid/datagrid-pagination.stories.ts
  .storybook/stories/datagrid/datagrid-placeholder.stories.ts
  .storybook/stories/datagrid/datagrid-row.stories.ts
  .storybook/stories/datagrid/datagrid.stories.ts
Labels: cla-not-required, type:chore

#189 chore: add stack view stories
  .storybook/stories/stack-view/stack-block.stories.ts
  .storybook/stories/stack-view/stack-view-with-lazy-loaded-blocks.stories.ts
  .storybook/stories/stack-view/stack-view.stories.ts
Labels: cla-not-required, type:chore

#186 chore: add tree stories
  .storybook/helpers/files.data.ts
  .storybook/stories/tree/tree-node.stories.ts
  .storybook/stories/tree/tree-with-lazy-loaded-nodes.stories.ts
  .storybook/stories/tree/tree-with-lazy-loaded-recursive-nodes.stories.ts
  .storybook/stories/tree/tree-with-recursive-nodes.stories.ts
  .storybook/stories/tree/tree.stories.ts
Labels: cla-not-required, type:chore

#188 chore: add chromatic support
  .github/workflows/pr-visual-regression.yml
  .github/workflows/release.yml
  .storybook/helpers/setup-storybook.helpers.ts
  .storybook/preview.js
Labels: cla-not-required, type:chore
