Repository vmware-clarity/ng-clarity, pull requests merged in 2022-08, with the labels that each got.

#262 chore: improve dev contribution documentation
  docs/CONTRIBUTING_DEVELOPMENT.md
  docs/CONTRIBUTING_DEV_BUG_FIXES.md
  docs/CONTRIBUTING_DEV_FEATURES.md
Labels: cla-not-required

#263 chore: add clr-control-success to forms story
  .storybook/stories/forms/forms.stories.ts
Labels: cla-not-required, type:chore

#266 chore(datagrid): add a11y inputs handling for the row in storybook
  .storybook/stories/datagrid/datagrid-row.stories.ts
Labels: cla-not-required

#242 feat(datepicker): indicate selected day in aria label
  projects/angular/clarity.api.md
  projects/angular/src/forms/datepicker/day.spec.ts
  projects/angular/src/forms/datepicker/day.ts
  projects/angular/src/utils/i18n/common-strings.default.ts
  projects/angular/src/utils/i18n/common-strings.interface.ts
Labels: type:feat

#268 chore: exit once story upload is complete
  .github/workflows/pr-visual-regression.yml
Labels: cla-not-required

#264 chore: add button variations to button story
  .storybook/stories/button/button.stories.ts
Labels: cla-not-required, type:chore

#277 chore: remove unused and incomplete virtual scroll directive
  projects/angular/src/utils/virtual-scroll/all.spec.ts
  projects/angular/src/utils/virtual-scroll/dom-helpers.spec.ts
  projects/angular/src/utils/virtual-scroll/dom-helpers.ts
  projects/angular/src/utils/virtual-scroll/index.ts
  projects/angular/src/utils/virtual-scroll/non-ng-iterable.ts
  projects/angular/src/utils/virtual-scroll/virtual-for-of.spec.ts
  projects/angular/src/utils/virtual-scroll/virtual-for-of.ts
  projects/angular/src/utils/virtual-scroll/virtual-scroll.module.ts
  projects/demo/src/app/app.routing.ts
  projects/demo/src/app/virtual-scroll/slots.ts
  projects/demo/src/app/virtual-scroll/virtual-scroll-array.ts
  projects/demo/src/app/virtual-scroll/virtual-scroll-infinite-generator.ts
  projects/demo/src/app/virtual-scroll/virtual-scroll-slot-machine.ts
  projects/demo/src/app/virtual-scroll/virtual-scroll.demo.module.ts
  projects/demo/src/app/virtual-scroll/virtual-scroll.demo.routing.ts
  projects/demo/src/app/virtual-scroll/virtual-scroll.demo.scss
  projects/demo/src/app/virtual-scroll/virtual-scroll.demo.ts
Labels: cla-not-required, type:chore

#270 feat(datagrid): add input for page size select element id
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-page-size.spec.ts
  projects/angular/src/data/datagrid/datagrid-page-size.ts
Labels: cla-not-required, type:feat

#281 feat(datagrid): add input for page size select element id (v12 backport)
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-page-size.spec.ts
  projects/angular/src/data/datagrid/datagrid-page-size.ts
Labels: cla-not-required, type:feat, backport

#284 fix(radio): use correct styles for disabled radio buttons
  projects/angular/src/forms/styles/_properties.forms.scss
  projects/angular/src/forms/styles/_radio.clarity.scss
Labels: type:fix

#287 fix(radio): use correct styles for disabled radio buttons (v12 backport)
  projects/angular/src/forms/styles/_properties.forms.scss
  projects/angular/src/forms/styles/_radio.clarity.scss
Labels: cla-not-required, type:fix, backport

#290 chore(docs): fix install links in readme (v12 backport)
  README.md
Labels: cla-not-required, type:chore, backport

#282 chore: remove unused and incomplete virtual scroll directive (v12 backport)
  projects/angular/src/utils/virtual-scroll/all.spec.ts
  projects/angular/src/utils/virtual-scroll/dom-helpers.spec.ts
  projects/angular/src/utils/virtual-scroll/dom-helpers.ts
  projects/angular/src/utils/virtual-scroll/index.ts
  projects/angular/src/utils/virtual-scroll/non-ng-iterable.ts
  projects/angular/src/utils/virtual-scroll/virtual-for-of.spec.ts
  projects/angular/src/utils/virtual-scroll/virtual-for-of.ts
  projects/angular/src/utils/virtual-scroll/virtual-scroll.module.ts
  projects/demo/src/app/app.routing.ts
  projects/demo/src/app/virtual-scroll/slots.ts
  projects/demo/src/app/virtual-scroll/virtual-scroll-array.ts
  projects/demo/src/app/virtual-scroll/virtual-scroll-infinite-generator.ts
  projects/demo/src/app/virtual-scroll/virtual-scroll-slot-machine.ts
  projects/demo/src/app/virtual-scroll/virtual-scroll.demo.module.ts
  projects/demo/src/app/virtual-scroll/virtual-scroll.demo.routing.ts
  projects/demo/src/app/virtual-scroll/virtual-scroll.demo.scss
  projects/demo/src/app/virtual-scroll/virtual-scroll.demo.ts
Labels: cla-not-required, type:chore, backport

#294 fix(vertical-nav): align icon and text of selected link with other links
  projects/angular/src/layout/vertical-nav/_vertical-nav.clarity.scss
Labels: cla-not-required, type:fix

#298 fix(vertical-nav): align icon and text of selected link with other links (v12 backport)
  projects/angular/src/layout/vertical-nav/_vertical-nav.clarity.scss
Labels: cla-not-required, type:fix, backport

#295 chore: auto accept merged visual changes
  .github/workflows/accept-merged-visual-changed.yml
Labels: type:chore
