Repository vmware-clarity/ng-clarity, pull requests merged in 2023-02, with the labels that each got.

#488 feat/chore: remove remaining references to the sidenav
  projects/angular/src/layout/nav/_properties.subnav.scss
  projects/angular/src/layout/nav/_variables.subnav.scss
  projects/angular/src/popover/dropdown/_variables.dropdown.scss
  projects/angular/src/utils/_theme.dark.clarity.scss
  projects/angular/src/utils/variables/_properties.typography.scss
  projects/angular/src/utils/variables/_variables.typography.scss
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required, beta

#487 fix(combobox): do not prefilter when first opened
  projects/angular/src/forms/combobox/combobox.ts
  projects/angular/src/forms/combobox/option-items.directive.spec.ts
  projects/angular/src/forms/combobox/option-items.directive.ts
  projects/angular/src/forms/combobox/providers/option-selection.service.ts
Labels: cla-not-required, type:breaking-change

#491 feat(datagrid): rename css custom properties to add "color" suffix
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  projects/angular/src/data/datagrid/_properties.datagrid.scss
  projects/angular/src/data/datagrid/_variables.datagrid.scss
  projects/angular/src/utils/_overwrites.clarity.scss
  projects/angular/src/utils/_theme.dark.clarity.scss
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required, type:breaking-change

#490 feat(wizard): rename css custom properties for consistency and to remove ambiguity
  projects/angular/src/utils/_overwrites.clarity.scss
  projects/angular/src/utils/_theme.dark.clarity.scss
  projects/angular/src/wizard/_properties.wizard.scss
  projects/angular/src/wizard/_variables.wizard.scss
  projects/angular/src/wizard/_wizard.clarity.scss
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required, type:breaking-change

#492 feat(datagrid): require using common strings to translate column toggle
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-column-toggle-button.spec.ts
  projects/angular/src/data/datagrid/datagrid-column-toggle-button.ts
  projects/angular/src/data/datagrid/datagrid-column-toggle-title.ts
  projects/angular/src/data/datagrid/datagrid-column-toggle.spec.ts
  projects/angular/src/data/datagrid/datagrid-column-toggle.ts
  projects/angular/src/data/datagrid/datagrid-footer.spec.ts
  projects/angular/src/data/datagrid/datagrid-footer.ts
  projects/angular/src/data/datagrid/datagrid.module.ts
  projects/angular/src/data/datagrid/index.ts
  projects/angular/src/deprecations.spec.ts
  projects/demo/src/app/datagrid/hide-show-columns/hide-show.html
Labels: cla-not-required, type:breaking-change

#496 chore: use correct path for @cds/core shim in storybook page
  .storybook/pages/cds-core-shim.stories.mdx
Labels: cla-not-required

#499 Revert "fix(vertical-nav): add aria list structure to vertical nav links"
  projects/angular/src/layout/vertical-nav/vertical-nav-link.ts
  projects/angular/src/layout/vertical-nav/vertical-nav.html
Labels: cla-not-required, type:fix

#498 fix(forms): update validation with onpush strategy components
  projects/angular/src/forms/common/if-control-state/if-control-state.service.ts
  projects/angular/src/forms/datepicker/date-input.validator.spec.ts
Labels: cla-not-required

#510 chore(datagrid): improve `trackBy` function type annotations
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-column-toggle.ts
  projects/angular/src/data/datagrid/datagrid-items-trackby.spec.ts
  projects/angular/src/data/datagrid/datagrid-items.spec.ts
  projects/angular/src/data/datagrid/datagrid.spec.ts
  projects/angular/src/data/datagrid/providers/items.ts
  projects/angular/src/data/datagrid/providers/selection.ts
  projects/angular/src/forms/combobox/option-items.directive.spec.ts
  projects/demo/src/app/datagrid/full/full.ts
  projects/demo/src/app/datagrid/preserve-selection/preserve-selection.ts
  projects/demo/src/app/datagrid/selection-single/selection-single.ts
  projects/demo/src/app/datagrid/selection/selection.ts
Labels: cla-not-required, type:chore

#509 chore(storybook): add pages for chromatic theme snapshots
  .github/workflows/accept-merged-visual-changes.yml
  .github/workflows/pr-visual-regression.yml
  .storybook/helpers/constants.ts
  .storybook/helpers/setup-storybook.helpers.ts
  .storybook/preview.js
  package-lock.json
  package.json
Labels: cla-not-required, type:chore

#515 chore: remove chromatic check for accurate webpack stats tracking
  .storybook/helpers/setup-storybook.helpers.ts
  .storybook/manager.js
  .storybook/public/manager.css
  package-lock.json
  package.json
Labels: cla-not-required

#517 fix: include minified cds-core shim in `@clr/ui` package
  package.json
Labels: cla-not-required, type:fix

#518 fix: include minified cds-core shim in `@clr/ui` package (13.x backbort)
  package.json
Labels: cla-not-required, type:fix, backport

#522 fix(datagrid): show "not allowed" cursor in disabled selection cell
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
Labels: cla-not-required, type:fix

#521 fix(datagrid): disable row checkbox/radio button in Angular v15
  projects/angular/src/data/datagrid/datagrid-row.html
  projects/angular/src/data/datagrid/datagrid-row.spec.ts
Labels: cla-not-required, type:fix

#514 fix(datagrid): resolve manage columns and popover shim color issues
  .storybook/stories/datagrid/datagrid-action-overflow.stories.ts
  .storybook/stories/datagrid/datagrid.stories.ts
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required

#524 fix(datagrid): show "not allowed" cursor in disabled selection cell (13.x backport)
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
Labels: cla-not-required, type:fix, backport

#523 fix(datagrid): disable row checkbox/radio button in Angular v15 (13.x backport)
  projects/angular/src/data/datagrid/datagrid-row.html
  projects/angular/src/data/datagrid/datagrid-row.spec.ts
Labels: cla-not-required, type:fix, backport

#526 fix(datagrid): resolve manage columns and popover shim color issues (backport to 13.x)
  .storybook/stories/datagrid/datagrid-action-overflow.stories.ts
  .storybook/stories/datagrid/datagrid.stories.ts
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required, type:fix, backport

#525 chore: remove workflows that only run from `main` from the `13.x` branch
  .github/workflows/accept-merged-visual-changes.yml
  .github/workflows/label-stale-threads.yml
  .github/workflows/lock-inactive-threads.yml
  .github/workflows/pr-comment-bot.yml
  .github/workflows/pr-preview.yml
  .github/workflows/pr-visual-regression.yml
Labels: cla-not-required, type:chore
