Repository vmware-clarity/ng-clarity, pull requests merged in 2023-04, with the labels that each got.

#613 feat(combobox): scroll to selected value on open
  projects/angular/src/forms/combobox/combobox.ts
  projects/angular/src/forms/combobox/providers/combobox-focus-handler.service.ts
Labels: cla-not-required, type:feat

#611 fix(tree): removes static width and height for tree nodes with checkbox
  .storybook/stories/dropdown/dropdown-tree.stories.ts
  projects/angular/src/data/tree-view/_tree-view.clarity.scss
  tests/snapshots/tree/tree-node--variants-core-dark.png
  tests/snapshots/tree/tree-node--variants-core-light.png
  tests/snapshots/tree/tree-node--variants-high-contrast.png
  tests/snapshots/tree/tree-node--variants-ng-dark.png
  tests/snapshots/tree/tree-node--variants-ng-light.png
Labels: cla-not-required, type:fix

#614 fix(datagrid): hide clr-dg-placeholder when not needed
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
Labels: cla-not-required, type:fix

#616 chore: remove highlight from visual snapshots
  tests/snapshots/datagrid/action-overflow--variants-core-dark.png
  tests/snapshots/datagrid/action-overflow--variants-core-light.png
  tests/snapshots/datagrid/action-overflow--variants-high-contrast.png
  tests/snapshots/datagrid/action-overflow--variants-ng-dark.png
  tests/snapshots/datagrid/action-overflow--variants-ng-light.png
  tests/snapshots/datagrid/column--variants-core-dark.png
  tests/snapshots/datagrid/column--variants-core-light.png
  tests/snapshots/datagrid/column--variants-high-contrast.png
  tests/snapshots/datagrid/column--variants-ng-dark.png
  tests/snapshots/datagrid/column--variants-ng-light.png
  tests/snapshots/datagrid/page-size--variants-core-dark.png
  tests/snapshots/datagrid/page-size--variants-core-light.png
  tests/snapshots/datagrid/page-size--variants-high-contrast.png
  tests/snapshots/datagrid/page-size--variants-ng-dark.png
  tests/snapshots/datagrid/page-size--variants-ng-light.png
  tests/snapshots/datagrid/pagination--variants-core-dark.png
  tests/snapshots/datagrid/pagination--variants-core-light.png
  tests/snapshots/datagrid/pagination--variants-high-contrast.png
  tests/snapshots/datagrid/pagination--variants-ng-dark.png
  tests/snapshots/datagrid/pagination--variants-ng-light.png
  tests/snapshots/datagrid/placeholder--variants-core-dark.png
  tests/snapshots/datagrid/placeholder--variants-core-light.png
  tests/snapshots/datagrid/placeholder--variants-high-contrast.png
  tests/snapshots/datagrid/placeholder--variants-ng-dark.png
  tests/snapshots/datagrid/placeholder--variants-ng-light.png
  tests/snapshots/datagrid/row--variants-core-dark.png
  tests/snapshots/datagrid/row--variants-core-light.png
  tests/snapshots/datagrid/row--variants-high-contrast.png
  tests/snapshots/datagrid/row--variants-ng-dark.png
  tests/snapshots/datagrid/row--variants-ng-light.png
  tests/visual-snapshots.spec.ts
Labels: cla-not-required, type:chore

#619 chore(focus-trap): unquote style values in test component
  projects/angular/src/utils/focus-trap/focus-trap.directive.spec.ts
Labels: cla-not-required, type:chore

#600 fix(dropdown): prevent default `click` event if item is disabled
  projects/angular/src/popover/dropdown/dropdown-item.ts
Labels: cla-not-required, type:fix

#620 fix(dropdown): prevent default `click` event if item is disabled (backport to 13.x)
  projects/angular/src/popover/dropdown/dropdown-item.ts
Labels: cla-not-required, type:fix, backport

#622 chore: use `commonStringsDefault` instead of creating service instance
  .storybook/stories/alert/alert.stories.ts
  .storybook/stories/button/button-group.stories.ts
  .storybook/stories/datagrid/datagrid-column.stories.ts
  .storybook/stories/datagrid/datagrid.stories.ts
  .storybook/stories/modal/modal.stories.ts
  projects/angular/src/data/datagrid/datagrid-pagination.spec.ts
  projects/angular/src/data/datagrid/datagrid-row-detail.spec.ts
  projects/angular/src/emphasis/alert/providers/icon-and-types.service.spec.ts
  projects/angular/src/layout/vertical-nav/vertical-nav.spec.ts
  projects/angular/src/modal/modal.spec.ts
  projects/angular/src/wizard/wizard-stepnav-item.spec.ts
Labels: cla-not-required, type:chore

#621 feat(datagrid): add input for action overflow button label
  .storybook/stories/datagrid/datagrid-action-overflow.stories.ts
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-action-overflow.spec.ts
  projects/angular/src/data/datagrid/datagrid-action-overflow.ts
Labels: cla-not-required, type:feat

#625 fix(popover): export stop propagation directive
  projects/angular/clarity.api.md
  projects/angular/src/utils/popover/all.spec.ts
  projects/angular/src/utils/popover/index.ts
  projects/angular/src/utils/popover/popover-host.directive.ts
  projects/angular/src/utils/popover/stop-escape-propagation.directive.spec.ts
  projects/angular/src/utils/popover/stop-escape-propagation.directive.ts
Labels: cla-not-required, type:fix

#626 fix(datagrid): change label around clickable row
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-row.html
  projects/angular/src/data/datagrid/datagrid-row.spec.ts
  projects/angular/src/data/datagrid/datagrid-row.ts
Labels: cla-not-required

#629 fix(datagrid): change label around clickable row (backport 13.x) (#626)
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-row.html
  projects/angular/src/data/datagrid/datagrid-row.spec.ts
  projects/angular/src/data/datagrid/datagrid-row.ts
Labels: cla-not-required

#630 chore: assert actual string values instead of common string values
  projects/angular/src/accordion/stepper/stepper-panel.spec.ts
  projects/angular/src/data/datagrid/datagrid-column-toggle.spec.ts
  projects/angular/src/data/datagrid/datagrid-detail.spec.ts
  projects/angular/src/data/datagrid/datagrid-filter.spec.ts
  projects/angular/src/data/datagrid/datagrid-pagination.spec.ts
  projects/angular/src/data/datagrid/datagrid-row-detail.spec.ts
  projects/angular/src/data/datagrid/datagrid.spec.ts
  projects/angular/src/emphasis/alert/providers/icon-and-types.service.spec.ts
  projects/angular/src/layout/nav/header.spec.ts
  projects/angular/src/layout/vertical-nav/vertical-nav.spec.ts
  projects/angular/src/modal/modal.spec.ts
  projects/angular/src/wizard/wizard-stepnav-item.spec.ts
Labels: cla-not-required, type:chore

#631 chore: add accordion api markdown example
  projects/angular/src/accordion/API.md
Labels: cla-not-required

#633 feat: add env file to support multiple operating systems
  .env
  package.json
Labels: cla-not-required

#628 chore: use `commonStringsDefault` instead of creating service instance (backport to 13.x)
  .storybook/stories/alert/alert.stories.ts
  .storybook/stories/button/button-group.stories.ts
  .storybook/stories/datagrid/datagrid-column.stories.ts
  .storybook/stories/datagrid/datagrid.stories.ts
  .storybook/stories/modal/modal.stories.ts
  projects/angular/src/data/datagrid/datagrid-pagination.spec.ts
  projects/angular/src/data/datagrid/datagrid-row-detail.spec.ts
  projects/angular/src/emphasis/alert/providers/icon-and-types.service.spec.ts
  projects/angular/src/layout/vertical-nav/vertical-nav.spec.ts
  projects/angular/src/modal/modal.spec.ts
  projects/angular/src/wizard/wizard-stepnav-item.spec.ts
Labels: cla-not-required, type:chore, backport

#632 chore: assert actual string values instead of common string values (backport to 13.x)
  projects/angular/src/accordion/stepper/stepper-panel.spec.ts
  projects/angular/src/data/datagrid/datagrid-column-toggle.spec.ts
  projects/angular/src/data/datagrid/datagrid-detail.spec.ts
  projects/angular/src/data/datagrid/datagrid-filter.spec.ts
  projects/angular/src/data/datagrid/datagrid-pagination.spec.ts
  projects/angular/src/data/datagrid/datagrid-row-detail.spec.ts
  projects/angular/src/data/datagrid/datagrid.spec.ts
  projects/angular/src/emphasis/alert/providers/icon-and-types.service.spec.ts
  projects/angular/src/layout/nav/header.spec.ts
  projects/angular/src/layout/vertical-nav/vertical-nav-group.spec.ts
  projects/angular/src/layout/vertical-nav/vertical-nav.spec.ts
  projects/angular/src/modal/modal.spec.ts
  projects/angular/src/wizard/wizard-stepnav-item.spec.ts
Labels: cla-not-required, type:chore, backport

#603 chore: remove `chromatic` visual regression testing
  .github/workflows/accept-merged-visual-changes.yml
  .github/workflows/pr-visual-regression.yml
  .github/workflows/release.yml
  .storybook/helpers/setup-storybook.helpers.ts
  .storybook/preview.js
  .storybook/tsconfig.json
  package.json
  tests/visual-snapshots.spec.ts
Labels: cla-not-required, type:chore

#648 feat(forms): add required mark class (backport to 13.x)
  .storybook/stories/forms/forms-required-mark.stories.ts
  projects/angular/src/forms/styles/_form.clarity.scss
  tests/snapshots/forms/required-mark--variants-core-dark.png
  tests/snapshots/forms/required-mark--variants-core-light.png
  tests/snapshots/forms/required-mark--variants-high-contrast.png
  tests/snapshots/forms/required-mark--variants-ng-dark.png
  tests/snapshots/forms/required-mark--variants-ng-light.png
Labels: cla-not-required, backport

#647 fix(datagrid): expandable rows overflow on safari
  .storybook/stories/datagrid/datagrid-expandable-row.stories.ts
  projects/angular/src/utils/animations/expandable-animation/expandable-animation.ts
Labels: cla-not-required, type:fix

#610 feat(alert): add aria labels for alerts pager
  projects/angular/clarity.api.md
  projects/angular/src/emphasis/alert/alerts-pager.html
  projects/angular/src/emphasis/alert/alerts-pager.spec.ts
  projects/angular/src/emphasis/alert/alerts-pager.ts
  projects/angular/src/utils/i18n/common-strings.default.ts
  projects/angular/src/utils/i18n/common-strings.interface.ts
Labels: cla-not-required, type:feat, a11y

#651 fix(datagrid): expandable rows overflow on safari ( backport to 13.x)
  .storybook/stories/datagrid/datagrid-expandable-row.stories.ts
  projects/angular/src/utils/animations/expandable-animation/expandable-animation.ts
Labels: cla-not-required, backport

#652 feat(alert): add aria labels for alerts pager (backport to 13.x)
  projects/angular/clarity.api.md
  projects/angular/src/emphasis/alert/alerts-pager.html
  projects/angular/src/emphasis/alert/alerts-pager.spec.ts
  projects/angular/src/emphasis/alert/alerts-pager.ts
  projects/angular/src/utils/i18n/common-strings.default.ts
  projects/angular/src/utils/i18n/common-strings.interface.ts
Labels: cla-not-required, backport

#641 chore: remove highlight from visual snapshots (backport to 13.x)
  tests/snapshots/datagrid/action-overflow--variants-core-dark.png
  tests/snapshots/datagrid/action-overflow--variants-core-light.png
  tests/snapshots/datagrid/action-overflow--variants-high-contrast.png
  tests/snapshots/datagrid/action-overflow--variants-ng-dark.png
  tests/snapshots/datagrid/action-overflow--variants-ng-light.png
  tests/snapshots/datagrid/column--variants-core-dark.png
  tests/snapshots/datagrid/column--variants-core-light.png
  tests/snapshots/datagrid/column--variants-high-contrast.png
  tests/snapshots/datagrid/column--variants-ng-dark.png
  tests/snapshots/datagrid/column--variants-ng-light.png
  tests/snapshots/datagrid/page-size--variants-core-dark.png
  tests/snapshots/datagrid/page-size--variants-core-light.png
  tests/snapshots/datagrid/page-size--variants-high-contrast.png
  tests/snapshots/datagrid/page-size--variants-ng-dark.png
  tests/snapshots/datagrid/page-size--variants-ng-light.png
  tests/snapshots/datagrid/pagination--variants-core-dark.png
  tests/snapshots/datagrid/pagination--variants-core-light.png
  tests/snapshots/datagrid/pagination--variants-high-contrast.png
  tests/snapshots/datagrid/pagination--variants-ng-dark.png
  tests/snapshots/datagrid/pagination--variants-ng-light.png
  tests/snapshots/datagrid/placeholder--variants-core-dark.png
  tests/snapshots/datagrid/placeholder--variants-core-light.png
  tests/snapshots/datagrid/placeholder--variants-high-contrast.png
  tests/snapshots/datagrid/placeholder--variants-ng-dark.png
  tests/snapshots/datagrid/placeholder--variants-ng-light.png
  tests/snapshots/datagrid/row--variants-core-dark.png
  tests/snapshots/datagrid/row--variants-core-light.png
  tests/snapshots/datagrid/row--variants-high-contrast.png
  tests/snapshots/datagrid/row--variants-ng-dark.png
  tests/snapshots/datagrid/row--variants-ng-light.png
  tests/visual-snapshots.spec.ts
Labels: cla-not-required, backport

#642 chore: remove `chromatic` visual regression testing (backport to 13.x)
  .github/workflows/release.yml
  .storybook/helpers/setup-storybook.helpers.ts
  .storybook/preview.js
Labels: cla-not-required, backport
