Repository vmware-clarity/ng-clarity, pull requests merged in 2023-10, with the labels that each got.

#976 fix(alert): remove hostBinding and use renderer for alert-hidden class
  projects/angular/clarity.api.md
  projects/angular/src/emphasis/alert/alert.ts
  projects/angular/src/emphasis/alert/alerts.spec.ts
  projects/demo/src/app/alert/angular/alert-angular-app-level-alerts.demo.html
  projects/demo/src/app/alert/angular/alert-angular-app-level-alerts.ts
Labels: cla-not-required, type:fix, v16

#944 chore(vrt): change filter to exclude default stories (v15)
  tests/visual-snapshots.spec.ts
Labels: cla-not-required, v15

#982 fix(alert): remove hostBinding and use renderer for alert-hidden class
  projects/angular/clarity.api.md
  projects/angular/src/emphasis/alert/alert.ts
  projects/angular/src/emphasis/alert/alerts.spec.ts
  projects/demo/src/app/alert/angular/alert-angular-app-level-alerts.demo.html
  projects/demo/src/app/alert/angular/alert-angular-app-level-alerts.ts
Labels: cla-not-required, type:fix

#978 chore(typography): align token generation with design through mixin
  projects/angular/src/utils/_mixins.scss
Labels: cla-not-required, type:chore, token-migration

#980 fix(card): update card header to correct font-weight
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required

#979 fix(header): add correct header title font-weight value
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/header/header--variants-core-dark.png
  tests/snapshots/header/header--variants-core-light.png
  tests/snapshots/header/header-colors--variants-core-dark.png
  tests/snapshots/header/header-colors--variants-core-light.png
  tests/snapshots/header/headers-collapsed--variants-core-dark.png
  tests/snapshots/header/headers-collapsed--variants-core-light.png
  tests/snapshots/header/headers-collapsed--variants-ng-dark.png
  tests/snapshots/header/headers-collapsed--variants-ng-light.png
  tests/snapshots/header/headers-static--variants-core-dark.png
  tests/snapshots/header/headers-static--variants-core-light.png
Labels: cla-not-required

#987 fix(card): update card header to correct font-weight (v15 backport)
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required, v15

#988 fix(header): add correct header title font-weight value (v15 backport)
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/header/header--variants-core-dark.png
  tests/snapshots/header/header--variants-core-light.png
  tests/snapshots/header/header-colors--variants-core-dark.png
  tests/snapshots/header/header-colors--variants-core-light.png
  tests/snapshots/header/headers-static--variants-core-dark.png
  tests/snapshots/header/headers-static--variants-core-light.png
Labels: cla-not-required, v15

#989 fix(modal): update title font-family variable (v15 backport)
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/modal/static--variants-core-dark.png
  tests/snapshots/modal/static--variants-core-light.png
  tests/snapshots/wizard/wizard--variants-core-dark.png
  tests/snapshots/wizard/wizard--variants-core-light.png
  tests/snapshots/wizard/wizard-page--variants-core-dark.png
  tests/snapshots/wizard/wizard-page--variants-core-light.png
Labels: cla-not-required, v15

#992 chore: unit tests to use cds theme
  package.json
  projects/angular/src/forms/styles/containers.spec.ts
  projects/angular/src/progress/spinner/spinner.spec.ts
  projects/angular/src/test.ts
  projects/demo/src/app/cds-theme-select.component.ts
Labels: cla-not-required, type:chore

#943 chore(storybook): refactor signpost stories to csf
  .storybook/helpers/common.ts
  .storybook/stories/signpost/signpost.stories.ts
  tests/screenshot-options.ts
  tests/snapshots/signpost/signpost--initial-core-dark.png
  tests/snapshots/signpost/signpost--initial-core-light.png
  tests/snapshots/signpost/signpost--initial-ng-dark.png
  tests/snapshots/signpost/signpost--initial-ng-light.png
  tests/snapshots/signpost/signpost--opened-core-dark.png
  tests/snapshots/signpost/signpost--opened-core-light.png
  tests/snapshots/signpost/signpost--opened-ng-dark.png
  tests/snapshots/signpost/signpost--opened-ng-light.png
Labels: cla-not-required, v16

#985 feat(buttons): remove fallbacks and shim relations
  projects/angular/src/button/STYLES.md
  projects/angular/src/button/_buttons.clarity.scss
  projects/angular/src/button/_properties.buttons.scss
  projects/angular/src/button/_variables.buttons.scss
  projects/angular/src/button/button-group/_button-group.clarity.scss
  projects/angular/src/popover/dropdown/_dropdown.clarity.scss
  projects/angular/src/utils/_mixins.scss
  projects/angular/src/utils/_overwrites.clarity.scss
  projects/demo/src/app/button-group/static/checkbox/button-group-checkboxes.html
  projects/demo/src/app/button-group/static/radio/button-group-radios.html
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/button/button--variants-core-dark.png
  tests/snapshots/button/button--variants-core-light.png
  tests/snapshots/button/button-group--variants-core-dark.png
  tests/snapshots/button/button-group--variants-core-light.png
  tests/snapshots/button/buttons-all--variants-core-dark.png
  tests/snapshots/button/buttons-all--variants-core-light.png
  tests/snapshots/button/buttons-loading-states--variants-core-dark.png
  tests/snapshots/button/buttons-loading-states--variants-core-light.png
  tests/snapshots/card/card--variants-core-dark.png
  tests/snapshots/card/card--variants-core-light.png
  tests/snapshots/datagrid/datagrid--variants-core-dark.png
  tests/snapshots/datagrid/datagrid--variants-core-light.png
  tests/snapshots/dropdown/dropdown--variants-core-dark.png
  tests/snapshots/dropdown/dropdown--variants-core-light.png
  tests/snapshots/dropdown/dropdown-menu--variants-core-dark.png
  tests/snapshots/dropdown/dropdown-menu--variants-core-light.png
  tests/snapshots/dropdown/dropdown-static--variants-core-dark.png
  tests/snapshots/dropdown/dropdown-static--variants-core-light.png
  tests/snapshots/login/login--variants-core-dark.png
  tests/snapshots/login/login--variants-core-light.png
  tests/snapshots/modal/modal--variants-core-dark.png
  tests/snapshots/modal/modal--variants-core-light.png
  tests/snapshots/modal/static--variants-core-dark.png
  tests/snapshots/modal/static--variants-core-light.png
  tests/snapshots/stepper/stepper--variants-core-dark.png
  tests/snapshots/stepper/stepper--variants-core-light.png
  tests/snapshots/wizard/wizard--variants-core-dark.png
  tests/snapshots/wizard/wizard--variants-core-light.png
  tests/snapshots/wizard/wizard-page--variants-core-dark.png
  tests/snapshots/wizard/wizard-page--variants-core-light.png
Labels: cla-not-required, type:feat, token-migration

#1005 fix(accordion): update event type and add descriptions
  projects/angular/clarity.api.md
  projects/angular/src/accordion/accordion-panel.ts
  projects/angular/src/accordion/accordion.ts
Labels: cla-not-required

#996 chore(accordion): update storybook stories to csfv3
  .storybook/stories/accordion/accordion-panel.stories.ts
  .storybook/stories/accordion/accordion.stories.ts
  .storybook/stories/accordion/nested-accordion.stories.ts
  tests/snapshots/accordion/accordion--initial-core-dark.png
  tests/snapshots/accordion/accordion--initial-core-light.png
  tests/snapshots/accordion/accordion--initial-ng-dark.png
  tests/snapshots/accordion/accordion--initial-ng-light.png
  tests/snapshots/accordion/accordion--multiple-panels-opened-core-dark.png
  tests/snapshots/accordion/accordion--multiple-panels-opened-core-light.png
  tests/snapshots/accordion/accordion--multiple-panels-opened-ng-dark.png
  tests/snapshots/accordion/accordion--multiple-panels-opened-ng-light.png
  tests/snapshots/accordion/accordion--single-panel-opened-core-dark.png
  tests/snapshots/accordion/accordion--single-panel-opened-core-light.png
  tests/snapshots/accordion/accordion--single-panel-opened-ng-dark.png
  tests/snapshots/accordion/accordion--single-panel-opened-ng-light.png
  tests/snapshots/accordion/accordion--variants-core-dark.png
  tests/snapshots/accordion/accordion--variants-core-light.png
  tests/snapshots/accordion/accordion--variants-ng-dark.png
  tests/snapshots/accordion/accordion--variants-ng-light.png
  tests/snapshots/accordion/accordion-panel--panel-closed-core-dark.png
  tests/snapshots/accordion/accordion-panel--panel-closed-core-light.png
  tests/snapshots/accordion/accordion-panel--panel-closed-disabled-core-dark.png
  tests/snapshots/accordion/accordion-panel--panel-closed-disabled-core-light.png
  tests/snapshots/accordion/accordion-panel--panel-closed-disabled-ng-dark.png
  tests/snapshots/accordion/accordion-panel--panel-closed-disabled-ng-light.png
  tests/snapshots/accordion/accordion-panel--panel-closed-ng-dark.png
  tests/snapshots/accordion/accordion-panel--panel-closed-ng-light.png
  tests/snapshots/accordion/accordion-panel--panel-opened-core-dark.png
  tests/snapshots/accordion/accordion-panel--panel-opened-core-light.png
  tests/snapshots/accordion/accordion-panel--panel-opened-disabled-core-dark.png
  tests/snapshots/accordion/accordion-panel--panel-opened-disabled-core-light.png
  tests/snapshots/accordion/accordion-panel--panel-opened-disabled-ng-dark.png
  tests/snapshots/accordion/accordion-panel--panel-opened-disabled-ng-light.png
  tests/snapshots/accordion/accordion-panel--panel-opened-ng-dark.png
  tests/snapshots/accordion/accordion-panel--panel-opened-ng-light.png
  tests/snapshots/accordion/accordion-panel--variants-core-dark.png
  tests/snapshots/accordion/accordion-panel--variants-core-light.png
  tests/snapshots/accordion/accordion-panel--variants-ng-dark.png
  tests/snapshots/accordion/accordion-panel--variants-ng-light.png
  tests/snapshots/accordion/nested-accordion--closed-core-dark.png
  tests/snapshots/accordion/nested-accordion--closed-core-light.png
  tests/snapshots/accordion/nested-accordion--closed-ng-dark.png
  tests/snapshots/accordion/nested-accordion--closed-ng-light.png
  tests/snapshots/accordion/nested-accordion--opened-core-dark.png
  tests/snapshots/accordion/nested-accordion--opened-core-light.png
  tests/snapshots/accordion/nested-accordion--opened-ng-dark.png
  tests/snapshots/accordion/nested-accordion--opened-ng-light.png
  tests/snapshots/accordion/nested-accordion--variants-core-dark.png
  tests/snapshots/accordion/nested-accordion--variants-core-light.png
  tests/snapshots/accordion/nested-accordion--variants-ng-dark.png
  tests/snapshots/accordion/nested-accordion--variants-ng-light.png
Labels: cla-not-required

#1000 fix(vertical-nav): align nav parent/child left padding
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/vertical-nav/vertical-nav-group--variants-core-dark.png
  tests/snapshots/vertical-nav/vertical-nav-group--variants-core-light.png
  tests/snapshots/vertical-nav/vertical-nav-routing--variants-core-dark.png
  tests/snapshots/vertical-nav/vertical-nav-routing--variants-core-light.png
Labels: cla-not-required

#969 chore(storybook): add tabs collapsed story to test smaller screens
  .storybook/preview.js
  .storybook/stories/tabs/tabs-collapsed.stories.ts
  tests/snapshots/tabs/tabs-reactive--variants-core-dark.png
  tests/snapshots/tabs/tabs-reactive--variants-core-light.png
  tests/snapshots/tabs/tabs-reactive--variants-ng-dark.png
  tests/snapshots/tabs/tabs-reactive--variants-ng-light.png
Labels: cla-not-required

#1010 chore(storybook): add tabs collapsed story to test smaller screens
  .storybook/preview.js
  .storybook/stories/tabs/tabs-collapsed.stories.ts
  tests/snapshots/tabs/tabs-reactive--variants-core-dark.png
  tests/snapshots/tabs/tabs-reactive--variants-core-light.png
  tests/snapshots/tabs/tabs-reactive--variants-ng-dark.png
  tests/snapshots/tabs/tabs-reactive--variants-ng-light.png
Labels: cla-not-required

#1009 chore(storybook): add tabs collapsed story to test smaller screens
  .storybook/preview.js
  .storybook/stories/tabs/tabs-collapsed.stories.ts
  tests/snapshots/tabs/tabs-reactive--variants-core-dark.png
  tests/snapshots/tabs/tabs-reactive--variants-core-light.png
Labels: cla-not-required

#1002 fix(card): update card header to correct font-weight (port of #980)
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required

#1008 fix(datagrid): update manage columns dialog close button color
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required

#1003 fix(header): add correct header title font-weight value (#979)
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/header/header--variants-core-dark.png
  tests/snapshots/header/header--variants-core-light.png
  tests/snapshots/header/header-colors--variants-core-dark.png
  tests/snapshots/header/header-colors--variants-core-light.png
  tests/snapshots/header/headers-collapsed--variants-core-dark.png
  tests/snapshots/header/headers-collapsed--variants-core-light.png
  tests/snapshots/header/headers-static--variants-core-dark.png
  tests/snapshots/header/headers-static--variants-core-light.png
Labels: cla-not-required

#1004 chore(storybook): refactor signpost stories to csf (port of #943)
  .storybook/helpers/common.ts
  .storybook/stories/signpost/signpost.stories.ts
  tests/screenshot-options.ts
  tests/snapshots/signpost/signpost--initial-core-dark.png
  tests/snapshots/signpost/signpost--initial-core-light.png
  tests/snapshots/signpost/signpost--opened-core-dark.png
  tests/snapshots/signpost/signpost--opened-core-light.png
Labels: cla-not-required

#1011 fix(datagrid): align checkbox with text in datagrid (port of #1006)
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  tests/snapshots/datagrid/row--variants-core-dark.png
  tests/snapshots/datagrid/row--variants-core-light.png
Labels: cla-not-required, type:fix

#993 feat(badges): remove shim mapping and get rid of fallbacks
  projects/angular/src/emphasis/STYLES.md
  projects/angular/src/emphasis/_badges.clarity.scss
  projects/angular/src/emphasis/_properties.badges.scss
  projects/angular/src/emphasis/_variables.badges.scss
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/badge/badge--variants-core-dark.png
  tests/snapshots/badge/badge--variants-core-light.png
  tests/snapshots/label/label--variants-core-dark.png
  tests/snapshots/label/label--variants-core-light.png
Labels: cla-not-required

#1012 feat(checkbox radio): remove fallbacks and shim relations
  projects/angular/src/forms/STYLES.MD
  projects/angular/src/forms/checkbox/STYLES.md
  projects/angular/src/forms/radio/STYLES.md
  projects/angular/src/forms/styles/_checkbox.clarity.scss
  projects/angular/src/forms/styles/_containers.clarity.scss
  projects/angular/src/forms/styles/_mixins.forms.scss
  projects/angular/src/forms/styles/_properties.forms.scss
  projects/angular/src/forms/styles/_radio.clarity.scss
  projects/angular/src/forms/styles/_variables.forms.scss
  projects/angular/src/forms/styles/containers.spec.ts
  projects/demo/src/app/checkboxes/checkboxes.demo.html
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/checkbox-or-toggle/checkbox-or-toggle--variants-core-light.png
  tests/snapshots/forms/input-states--variants-core-dark.png
  tests/snapshots/forms/input-states--variants-core-light.png
  tests/snapshots/forms/reactive--variants-core-dark.png
  tests/snapshots/forms/reactive--variants-core-light.png
  tests/snapshots/radio/radio--variants-core-dark.png
  tests/snapshots/radio/radio--variants-core-light.png
Labels: cla-not-required, type:feat

#994 feat(labels): remove shim mapping and get rid of fallbacks
  projects/angular/src/emphasis/STYLES.md
  projects/angular/src/emphasis/_labels.clarity.scss
  projects/angular/src/emphasis/_properties.label.scss
  projects/angular/src/emphasis/_variables.badges.scss
  projects/angular/src/emphasis/_variables.label.scss
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/label/label--variants-core-dark.png
  tests/snapshots/label/label--variants-core-light.png
Labels: cla-not-required, type:feat, token-migration

#1013 feat(select): remove shim mapping and fallbacks
  projects/angular/src/forms/STYLES.MD
  projects/angular/src/forms/styles/_properties.forms.scss
  projects/angular/src/forms/styles/_select.clarity.scss
  projects/angular/src/forms/styles/_variables.forms.scss
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/datagrid/action-overflow--variants-core-dark.png
  tests/snapshots/datagrid/action-overflow--variants-core-light.png
  tests/snapshots/datagrid/column--variants-core-dark.png
  tests/snapshots/datagrid/column--variants-core-light.png
  tests/snapshots/datagrid/datagrid--variants-core-dark.png
  tests/snapshots/datagrid/datagrid--variants-core-light.png
  tests/snapshots/datagrid/detail--variants-core-dark.png
  tests/snapshots/datagrid/detail--variants-core-light.png
  tests/snapshots/datagrid/page-size--variants-core-dark.png
  tests/snapshots/datagrid/page-size--variants-core-light.png
  tests/snapshots/datagrid/pagination--variants-core-dark.png
  tests/snapshots/datagrid/pagination--variants-core-light.png
  tests/snapshots/datagrid/placeholder--variants-core-dark.png
  tests/snapshots/datagrid/placeholder--variants-core-light.png
  tests/snapshots/datagrid/row--variants-core-dark.png
  tests/snapshots/datagrid/row--variants-core-light.png
  tests/snapshots/forms/input-states--variants-core-dark.png
  tests/snapshots/forms/input-states--variants-core-light.png
  tests/snapshots/forms/required-mark--variants-core-dark.png
  tests/snapshots/forms/required-mark--variants-core-light.png
  tests/snapshots/login/login--variants-core-dark.png
  tests/snapshots/login/login--variants-core-light.png
  tests/snapshots/select/select--variants-core-dark.png
  tests/snapshots/select/select--variants-core-light.png
Labels: cla-not-required

#1001 fix(modal): update title font-family variable (port of #981)
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/modal/static--variants-core-dark.png
  tests/snapshots/modal/static--variants-core-light.png
  tests/snapshots/wizard/wizard--variants-core-dark.png
  tests/snapshots/wizard/wizard--variants-core-light.png
  tests/snapshots/wizard/wizard-page--variants-core-dark.png
  tests/snapshots/wizard/wizard-page--variants-core-light.png
Labels: cla-not-required

#991 feat(spinner): set shim styles as default
  projects/angular/src/progress/spinner/_properties.spinner.scss
  projects/angular/src/progress/spinner/_spinner.clarity.scss
  projects/angular/src/progress/spinner/_variables.spinner.scss
  projects/angular/src/progress/spinner/spinner.spec.ts
  projects/angular/src/utils/_overwrites.clarity.scss
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/spinner/spinner--variants-core-dark.png
  tests/snapshots/spinner/spinner--variants-core-light.png
Labels: cla-not-required

#1014 feat(modal, wizard): remove shim mapping and fallbacks
  projects/angular/src/modal/STYLES.md
  projects/angular/src/modal/_modal.clarity.scss
  projects/angular/src/modal/_properties.modal.scss
  projects/angular/src/modal/_variables.modal.scss
  projects/angular/src/utils/_mixins.scss
  projects/angular/src/utils/_overwrites.clarity.scss
  projects/angular/src/wizard/STYLES.md
  projects/angular/src/wizard/_properties.wizard.scss
  projects/angular/src/wizard/_variables.wizard.scss
  projects/angular/src/wizard/_wizard.clarity.scss
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/modal/static--variants-core-dark.png
  tests/snapshots/modal/static--variants-core-light.png
  tests/snapshots/wizard/wizard--variants-core-dark.png
  tests/snapshots/wizard/wizard--variants-core-light.png
  tests/snapshots/wizard/wizard-page--variants-core-dark.png
  tests/snapshots/wizard/wizard-page--variants-core-light.png
Labels: cla-not-required, type:feat, token-migration

#1020 fix(labels, tree-view): remove has pseudo selector
  projects/angular/clarity.api.md
  projects/angular/src/data/tree-view/tree-node.html
  projects/angular/src/data/tree-view/tree-node.ts
  projects/angular/src/emphasis/_labels.clarity.scss
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required

#1024 fix(label): remove has pseudo class selector (port of #1020)
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required

#1025 fix(label): remove has pseudo class selector (port of #1020)
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/label/label--variants-core-dark.png
  tests/snapshots/label/label--variants-core-light.png
Labels: cla-not-required

#1023 fix(tree-view): remove has css selector (port of #1020)
  projects/angular/clarity.api.md
  projects/angular/src/data/tree-view/tree-node.html
  projects/angular/src/data/tree-view/tree-node.ts
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required

#1027 fix(signpost): allow keyboard scrolling in overflow content
  projects/angular/src/popover/signpost/signpost-content.ts
Labels: cla-not-required, type:fix

#1028 fix(signpost): allow keyboard scrolling in overflow content ( backport of #1027 )
  projects/angular/src/popover/signpost/signpost-content.ts
Labels: cla-not-required, type:fix, next

#1017 fix(stepper): update min-width to match max-width
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/stepper/stepper--variants-core-dark.png
  tests/snapshots/stepper/stepper--variants-core-light.png
Labels: cla-not-required
