Repository vmware-clarity/ng-clarity, pull requests merged in 2023-07, with the labels that each got.

#805 chore: rename style doc files to `STYLES.md`
  projects/angular/src/button/button-group/STYLES.md
  projects/angular/src/forms/common/STYLES.md
  projects/angular/src/layout/tabs/STYLES.md
Labels: cla-not-required, type:chore

#806 chore: update style docs classes headings for consistency
  projects/angular/src/accordion/STYLES.md
  projects/angular/src/button/STYLES.md
  projects/angular/src/button/button-group/STYLES.md
  projects/angular/src/data/STYLES.md
  projects/angular/src/data/stack-view/STYLES.md
  projects/angular/src/data/tree-view/STYLES.md
  projects/angular/src/emphasis/STYLES.md
  projects/angular/src/emphasis/alert/STYLES.md
  projects/angular/src/forms/checkbox/STYLES.md
  projects/angular/src/forms/combobox/STYLES.md
  projects/angular/src/forms/datepicker/STYLES.md
  projects/angular/src/forms/input/STYLES.md
  projects/angular/src/forms/radio/STYLES.md
  projects/angular/src/forms/range/STYLES.md
  projects/angular/src/forms/select/STYLES.md
  projects/angular/src/forms/textarea/STYLES.md
  projects/angular/src/layout/STYLES.md
  projects/angular/src/layout/grid/STYLES.md
  projects/angular/src/layout/main-container/STYLES.md
  projects/angular/src/layout/vertical-nav/STYLES.md
  projects/angular/src/modal/STYLES.md
  projects/angular/src/popover/dropdown/STYLES.md
  projects/angular/src/popover/signpost/STYLES.md
  projects/angular/src/popover/tooltip/STYLES.md
  projects/angular/src/progress/progress-bars/STYLES.md
  projects/angular/src/progress/spinner/STYLES.md
  projects/angular/src/timeline/STYLES.md
  projects/angular/src/typography/STYLES.md
  projects/angular/src/wizard/STYLES.md
Labels: cla-not-required, type:chore

#807 fix(combobox): remove pseudo focus on empty items
  projects/angular/src/forms/combobox/options.ts
Labels: cla-not-required, type:fix

#808 feat: ship `STYLES.md` content in `@clr/ui` package
  package.json
  scripts/compile-style-docs.js
Labels: cla-not-required, website / documentation

#814 fix(tooltip): allow user to interact with tooltip content using mouse
  projects/angular/src/popover/tooltip/_tooltips.clarity.scss
Labels: cla-not-required

#818 chore: update pr comment wording
  .github/workflows/pr-comment-bot.yml
Labels: cla-not-required, type:chore

#830 chore: add login page story
  .storybook/stories/login/login.stories.ts
  tests/snapshots/login/login--variants-core-dark.png
  tests/snapshots/login/login--variants-core-light.png
  tests/snapshots/login/login--variants-high-contrast.png
  tests/snapshots/login/login--variants-ng-dark.png
  tests/snapshots/login/login--variants-ng-light.png
Labels: cla-not-required, type:chore

#812 fix(ui): add missing tokens, remap tokens to system
  projects/ui/src/shim.cds-core.scss
  projects/ui/src/token_shim.cds-core.scss
  tests/snapshots/accordion/accordion--variants-core-light.png
  tests/snapshots/accordion/accordion-panel--variants-core-light.png
  tests/snapshots/accordion/nested-accordion--variants-core-light.png
  tests/snapshots/alert/alert--variants-core-light.png
  tests/snapshots/alert/alerts--variants-core-light.png
  tests/snapshots/badge/badge--variants-core-light.png
  tests/snapshots/button/button--variants-core-light.png
  tests/snapshots/button/button-group--variants-core-light.png
  tests/snapshots/card/card--variants-core-light.png
  tests/snapshots/checkbox-or-toggle/checkbox-or-toggle--variants-core-light.png
  tests/snapshots/checkbox-or-toggle/checkbox-or-toggle-container--variants-core-light.png
  tests/snapshots/combobox/combobox--variants-core-light.png
  tests/snapshots/datagrid/action-overflow--variants-core-light.png
  tests/snapshots/datagrid/column--variants-core-light.png
  tests/snapshots/datagrid/datagrid--variants-core-light.png
  tests/snapshots/datagrid/detail--variants-core-light.png
  tests/snapshots/datagrid/page-size--variants-core-light.png
  tests/snapshots/datagrid/pagination--variants-core-light.png
  tests/snapshots/datagrid/placeholder--variants-core-light.png
  tests/snapshots/datagrid/row--variants-core-light.png
  tests/snapshots/datalist/datalist--variants-core-light.png
  tests/snapshots/datepicker/datecontainer--variants-core-light.png
  tests/snapshots/datepicker/datepicker--variants-core-light.png
  tests/snapshots/dropdown/dropdown--variants-core-light.png
  tests/snapshots/dropdown/dropdown-menu--variants-core-light.png
  tests/snapshots/forms/reactive--variants-core-light.png
  tests/snapshots/forms/required-mark--variants-core-light.png
  tests/snapshots/forms/template-driven--variants-core-light.png
  tests/snapshots/header/header--variants-core-light.png
  tests/snapshots/label/label--variants-core-light.png
  tests/snapshots/list/list--variants-core-light.png
  tests/snapshots/login/login--variants-core-light.png
  tests/snapshots/modal/modal--variants-core-light.png
  tests/snapshots/progress-bar/progress-bar--variants-core-light.png
  tests/snapshots/radio/radio--variants-core-light.png
  tests/snapshots/radio/radio-container--variants-core-light.png
  tests/snapshots/range/range-container--variants-core-light.png
  tests/snapshots/select/select--variants-core-light.png
  tests/snapshots/signpost/signpost--variants-core-light.png
  tests/snapshots/spinner/spinner--variants-core-light.png
  tests/snapshots/stack-view/stack-block--variants-core-light.png
  tests/snapshots/stack-view/stack-view--variants-core-light.png
  tests/snapshots/stack-view/stack-view-with-lazy-loaded-blocks--variants-core-light.png
  tests/snapshots/stepper/stepper--variants-core-light.png
  tests/snapshots/table/table--variants-core-light.png
  tests/snapshots/tabs/tabs--variants-core-light.png
  tests/snapshots/timeline/timeline--variants-core-light.png
  tests/snapshots/timeline/timeline-step--variants-core-light.png
  tests/snapshots/tooltip/tooltip--variants-core-light.png
  tests/snapshots/tree/tree--variants-core-light.png
  tests/snapshots/tree/tree-node--variants-core-light.png
  tests/snapshots/tree/tree-with-lazy-loaded-nodes--variants-core-light.png
  tests/snapshots/tree/tree-with-lazy-loaded-recursive-nodes--variants-core-light.png
  tests/snapshots/tree/tree-with-recursive-nodes--variants-core-light.png
  tests/snapshots/vertical-nav/vertical-nav--variants-core-light.png
  tests/snapshots/vertical-nav/vertical-nav-group--variants-core-light.png
  tests/snapshots/wizard/wizard--variants-core-light.png
  tests/snapshots/wizard/wizard-page--variants-core-light.png
Labels: cla-not-required

#826 chore: deploy pr preview whether or not build succeeds if docs generated
  .github/workflows/pr-comment-bot.yml
  .github/workflows/pr-preview.yml
Labels: cla-not-required, type:chore

#838 chore: add static modal stories for visual tests
  .storybook/stories/modal/modal-static.stories.ts
  tests/snapshots/modal/static--variants-core-dark.png
  tests/snapshots/modal/static--variants-core-light.png
  tests/snapshots/modal/static--variants-high-contrast.png
  tests/snapshots/modal/static--variants-ng-dark.png
  tests/snapshots/modal/static--variants-ng-light.png
Labels: cla-not-required, type:chore

#841 fix(stack-view): ignore input events in stack block
  projects/angular/clarity.api.md
  projects/angular/src/data/stack-view/stack-block.ts
Labels: cla-not-required, type:fix

#842 fix(ui): add missing _properties imports and refactor for consistency
  projects/angular/src/accordion/_accordion.clarity.scss
  projects/angular/src/data/tree-view/_tree-view.clarity.scss
  projects/angular/src/emphasis/_badges.clarity.scss
  projects/angular/src/emphasis/alert/_alert.clarity.scss
  projects/angular/src/forms/combobox/_combobox.clarity.scss
  projects/angular/src/forms/datepicker/_datepicker.clarity.scss
  projects/angular/src/layout/_card.clarity.scss
  projects/angular/src/layout/_login.clarity.scss
  projects/angular/src/layout/nav/_subnav.clarity.scss
  projects/angular/src/layout/tabs/_tabs.clarity.scss
  projects/angular/src/modal/_modal.clarity.scss
  projects/angular/src/popover/dropdown/_dropdown.clarity.scss
  projects/angular/src/popover/signpost/_signposts.clarity.scss
  projects/angular/src/progress/progress-bars/_progress-bars.clarity.scss
  projects/angular/src/timeline/_timeline.clarity.scss
  projects/angular/src/utils/_reboot.clarity.scss
  projects/angular/src/wizard/_wizard.clarity.scss
  tests/snapshots/modal/static--variants-core-dark.png
  tests/snapshots/modal/static--variants-core-light.png
  tests/snapshots/modal/static--variants-high-contrast.png
  tests/snapshots/modal/static--variants-ng-light.png
Labels: cla-not-required, type:chore

#795 feat(datalist): add tokens and update shim
  .storybook/stories/datalist/datalist.stories.ts
  projects/angular/src/forms/STYLES.MD
  projects/angular/src/forms/datalist/datalist-container.ts
  projects/angular/src/forms/styles/_datalist.clarity.scss
  projects/angular/src/forms/styles/_properties.forms.scss
  projects/angular/src/utils/_mixins.scss
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/datalist/datalist--variants-core-dark.png
  tests/snapshots/datalist/datalist--variants-core-light.png
  tests/snapshots/datalist/datalist--variants-high-contrast.png
  tests/snapshots/datalist/datalist--variants-ng-dark.png
  tests/snapshots/datalist/datalist--variants-ng-light.png
  tests/snapshots/forms/required-mark--variants-core-dark.png
  tests/snapshots/forms/required-mark--variants-core-light.png
  tests/snapshots/forms/required-mark--variants-high-contrast.png
  tests/snapshots/forms/required-mark--variants-ng-dark.png
  tests/snapshots/forms/required-mark--variants-ng-light.png
Labels: cla-not-required, type:feat, waiting:needs-design

#845 fix(links): exclude btn and nav-link from styling
  projects/angular/src/layout/nav/_links.clarity.scss
Labels: cla-not-required, type:fix

#847 chore(vrt): expand parallel workers for tests
  playwright.config.ts
Labels: cla-not-required
