Repository vmware-clarity/ng-clarity, pull requests merged in 2023-03, with the labels that each got.

#527 chore: remove "check if main is merged" step from release workflows
  .github/workflows/release-preview.yml
  .github/workflows/release.yml
Labels: cla-not-required, type:chore

#529 chore: update chromatic to rebuild on lockfile and sass changes
  .github/workflows/accept-merged-visual-changes.yml
  .github/workflows/pr-visual-regression.yml
Labels: cla-not-required

#528 chore: update @cds/core, add form story
  .storybook/stories/forms/forms.stories.ts
  package-lock.json
  package.json
Labels: cla-not-required, type:chore

#531 fix(datagrid): set non-selectable multi select rows to disabled on initial render
  .storybook/stories/datagrid/datagrid-row.stories.ts
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-row.spec.ts
  projects/angular/src/data/datagrid/datagrid-row.ts
Labels: cla-not-required, type:fix

#533 fix(datepicker): add title to next month icon to align with other icons
  projects/angular/src/forms/datepicker/daypicker.html
Labels: cla-not-required

#530 fix(button): add mapping of warning button to danger styles
  .storybook/stories/button/button.stories.ts
  projects/angular/src/button/_buttons.clarity.scss
  projects/angular/src/button/_variables.buttons.scss
  projects/angular/src/utils/_theme.dark.clarity.scss
Labels: cla-not-required, type:fix

#535 fix(button): add mapping of warning button to danger styles (backport)
  .storybook/stories/button/button.stories.ts
  projects/angular/src/button/_buttons.clarity.scss
  projects/angular/src/button/_variables.buttons.scss
  projects/angular/src/utils/_theme.dark.clarity.scss
Labels: cla-not-required

#536 fix(datepicker): add title to next month icon to align with other icons (backport)
  projects/angular/src/forms/datepicker/daypicker.html
Labels: cla-not-required

#537 fix(datagrid): set non-selectable multi select rows to disabled on initial render (backport)
  .storybook/stories/datagrid/datagrid-row.stories.ts
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-row.spec.ts
  projects/angular/src/data/datagrid/datagrid-row.ts
Labels: cla-not-required

#538 fix(datagrid): prevent "manage columns" from making rows selectable
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-column-toggle-trackby.ts
  projects/angular/src/data/datagrid/datagrid-column-toggle.ts
  projects/angular/src/data/datagrid/datagrid-items-trackby.spec.ts
  projects/angular/src/data/datagrid/datagrid-items-trackby.ts
Labels: cla-not-required, type:fix

#540 fix(datagrid): prevent "manage columns" from making rows selectable (13.x backport)
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-column-toggle-trackby.ts
  projects/angular/src/data/datagrid/datagrid-column-toggle.ts
  projects/angular/src/data/datagrid/datagrid-items-trackby.spec.ts
  projects/angular/src/data/datagrid/datagrid-items-trackby.ts
Labels: cla-not-required, type:fix, backport

#541 fix(datagrid): add workaround to enable `clrDgSelectable` with `*ngFor` (13.x backport)
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-items-trackby.spec.ts
  projects/angular/src/data/datagrid/datagrid-items-trackby.ts
  projects/angular/src/data/datagrid/datagrid-items.spec.ts
  projects/angular/src/data/datagrid/datagrid-items.ts
  projects/angular/src/data/datagrid/datagrid-row.spec.ts
  projects/angular/src/data/datagrid/datagrid.spec.ts
  projects/angular/src/data/datagrid/datagrid.ts
  projects/angular/src/data/datagrid/index.ts
  projects/angular/src/data/datagrid/providers/items.ts
  projects/angular/src/data/datagrid/providers/selection.spec.ts
  projects/angular/src/data/datagrid/providers/selection.ts
Labels: cla-not-required, type:fix, backport

#545 chore(datagrid): remove old sorting bindings from column story
  .storybook/stories/datagrid/datagrid-column.stories.ts
Labels: cla-not-required, type:chore

#547 chore(datagrid): remove unused sort event handler in column story
  .storybook/stories/datagrid/datagrid-column.stories.ts
Labels: cla-not-required, type:chore

#546 chore(datagrid): add `clrDgColumnResize` event to column story
  .storybook/stories/datagrid/datagrid-column.stories.ts
Labels: cla-not-required, type:chore

#544 fix(combobox): rename incorrect css var (missing -color)
  projects/angular/src/forms/combobox/_properties.combobox.scss
Labels: cla-not-required, type:fix

#549 fix(combobox): rename incorrect css var (missing -color) (backport 13.x)
  projects/angular/src/forms/combobox/_properties.combobox.scss
Labels: cla-not-required, type:fix, backport

#550 chore(combobox): filter options as user types
  .storybook/stories/combobox/combobox.stories.ts
Labels: cla-not-required, type:chore

#551 chore(combobox): filter options in story as user types (13.x backport)
  .storybook/stories/combobox/combobox.stories.ts
Labels: cla-not-required, type:chore, backport

#553 chore: update angular to latest v15.x
  package-lock.json
  package.json
Labels: cla-not-required

#543 fix(button): add keyboard navigation in button-group menu
  projects/angular/clarity.api.md
  projects/angular/src/button/all.spec.ts
  projects/angular/src/button/button-group/button-group.html
  projects/angular/src/button/button-group/button-group.ts
  projects/angular/src/button/providers/button-group-focus-handler.service.ts
  projects/angular/src/button/providers/button-group-focus-handler.spec.ts
  projects/angular/src/button/providers/button-group-focus.enum.ts
Labels: cla-not-required, type:fix, waiting:needs-a11y, a11y

#552 chore: import scss files directly for chromatic to detect changes
  .github/workflows/accept-merged-visual-changes.yml
  .github/workflows/pr-visual-regression.yml
  .storybook/preview.js
  package.json
Labels: cla-not-required, type:chore

#560 fix(tooltip): prevent flashing when hovering trigger
  projects/angular/src/popover/tooltip/_tooltips.clarity.scss
Labels: cla-not-required, type:fix

#548 fix(forms): fix template-driven forms validation regression
  .storybook/stories/forms/forms-reactive.stories.ts
  .storybook/stories/forms/forms-template-driven.stories.ts
  projects/angular/src/forms/common/abstract-container.ts
  projects/angular/src/forms/datepicker/date-container.spec.ts
  projects/angular/src/forms/tests/container.spec.ts
  projects/demo/src/app/forms/forms.demo.module.ts
  projects/demo/src/app/forms/forms.demo.routing.ts
  projects/demo/src/app/forms/forms.demo.ts
  projects/demo/src/app/forms/reactive/reactive.ts
  projects/demo/src/app/forms/template-driven/template-driven.ts
Labels: cla-not-required

#564 Revert "fix(button): add keyboard navigation in button-group menu"
  projects/angular/clarity.api.md
  projects/angular/src/button/all.spec.ts
  projects/angular/src/button/button-group/button-group.html
  projects/angular/src/button/button-group/button-group.ts
  projects/angular/src/button/providers/button-group-focus-handler.service.ts
  projects/angular/src/button/providers/button-group-focus-handler.spec.ts
  projects/angular/src/button/providers/button-group-focus.enum.ts
Labels: cla-not-required

#566 chore(datagrid): add `clrDgColumnResize` event to column story (backport to 13.x)
  .storybook/stories/datagrid/datagrid-column.stories.ts
Labels: cla-not-required, type:chore, backport

#565 fix(tooltip): prevent flashing when hovering trigger (backport to 13.x)
  projects/angular/src/popover/tooltip/_tooltips.clarity.scss
Labels: cla-not-required, type:fix, backport

#567 fix(forms): fix template-driven forms validation regression (backport to 13.x)
  .storybook/stories/forms/forms-reactive.stories.ts
  .storybook/stories/forms/forms-template-driven.stories.ts
  projects/angular/src/forms/common/abstract-container.ts
  projects/angular/src/forms/datepicker/date-container.spec.ts
  projects/angular/src/forms/tests/container.spec.ts
  projects/demo/src/app/forms/forms.demo.module.ts
  projects/demo/src/app/forms/forms.demo.routing.ts
  projects/demo/src/app/forms/forms.demo.ts
  projects/demo/src/app/forms/reactive/reactive.ts
  projects/demo/src/app/forms/template-driven/template-driven.ts
Labels: cla-not-required, type:fix, backport

#570 fix(button): custom aria label for button group menu toggle
  .storybook/stories/button/button-group.stories.ts
  projects/angular/clarity.api.md
  projects/angular/src/button/button-group/button-group.html
  projects/angular/src/button/button-group/button-group.spec.ts
  projects/angular/src/button/button-group/button-group.ts
Labels: cla-not-required

#572 chore: update angular/commitizen to resolve security warnings
  package-lock.json
  package.json
Labels: cla-not-required

#573 chore(storybook): move `clrToggleButtonAriaLabel` arg to inputs section
  .storybook/stories/button/button-group.stories.ts
Labels: cla-not-required, type:chore

#574 fix(button): custom aria label for button group menu toggle (backport to 13.x)
  .storybook/stories/button/button-group.stories.ts
  projects/angular/clarity.api.md
  projects/angular/src/button/button-group/button-group.html
  projects/angular/src/button/button-group/button-group.spec.ts
  projects/angular/src/button/button-group/button-group.ts
Labels: cla-not-required, backport

#562 fix(dropdown): manage focus correctly when a modal is opened
  .storybook/stories/dropdown/dropdown-item-that-opens-modal.stories.ts
  projects/angular/clarity.api.md
  projects/angular/src/popover/dropdown/dropdown-item.ts
  projects/angular/src/popover/dropdown/dropdown.spec.ts
  projects/angular/src/popover/dropdown/dropdown.ts
  projects/angular/src/popover/dropdown/providers/dropdown-focus-handler.service.ts
Labels: cla-not-required, type:fix

#568 feat(checkbox,radio,tree): refactor checbox/radio label styles to class
  projects/angular/src/data/tree-view/_tree-view.clarity.scss
  projects/angular/src/data/tree-view/_variables.tree-view.scss
  projects/angular/src/data/tree-view/tree-node.html
  projects/angular/src/forms/styles/_checkbox.clarity.scss
  projects/angular/src/forms/styles/_mixins.forms.scss
  projects/angular/src/forms/styles/_radio.clarity.scss
Labels: cla-not-required

#579 chore: add autocomplete attributes to date,username,password inputs
  .storybook/stories/datepicker/date-container.stories.ts
  .storybook/stories/datepicker/datepicker.stories.ts
  .storybook/stories/forms/forms-reactive.stories.ts
  .storybook/stories/forms/forms-template-driven.stories.ts
  projects/angular/src/forms/datepicker/date-container.spec.ts
  projects/demo/src/app/datepicker/css-regression.html
  projects/demo/src/app/datepicker/datepicker-AK.ts
  projects/demo/src/app/datepicker/datepicker-AR.ts
  projects/demo/src/app/datepicker/datepicker-DE.ts
  projects/demo/src/app/datepicker/datepicker-HI.ts
  projects/demo/src/app/datepicker/datepicker-KKJ.ts
  projects/demo/src/app/datepicker/datepicker-date-input-explicit-wrapper.html
  projects/demo/src/app/datepicker/datepicker-date-input.html
  projects/demo/src/app/datepicker/datepicker-hr.ts
  projects/demo/src/app/datepicker/datepicker-in-template-driven-forms.html
  projects/demo/src/app/datepicker/datepicker-min-max.html
  projects/demo/src/app/datepicker/disabled.html
  projects/demo/src/app/datepicker/layout.html
  projects/demo/src/app/datepicker/ngmodel-auto-wrapped.html
  projects/demo/src/app/datepicker/ngmodel-wrapper-explicit-wrapper.html
  projects/demo/src/app/forms/a11y/a11y.html
  projects/demo/src/app/forms/disabled/disabled.html
  projects/demo/src/app/forms/input-group/input-group.html
  projects/demo/src/app/forms/layout-angular/layout-angular.html
  projects/demo/src/app/forms/validation/validation.html
  projects/demo/src/app/login/login.demo.html
  projects/demo/src/app/password/password.demo.html
  projects/demo/src/app/stepper/stepper.demo.html
  projects/demo/src/app/z-index/various-content/various-content.html
Labels: cla-not-required

#580 chore(dropdown): remove redundant visual regression test
  .storybook/stories/dropdown/dropdown-item-that-opens-modal.stories.ts
Labels: cla-not-required, type:chore

#581 chore: use kebab casing for workflow step ids
  .github/workflows/pr-comment-bot.yml
  .github/workflows/pr-preview.yml
  .github/workflows/pr-visual-regression.yml
Labels: cla-not-required, type:chore

#583 fix(datagrid): disable autocomplete on filter input
  projects/angular/src/data/datagrid/built-in/filters/datagrid-numeric-filter.ts
  projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.ts
Labels: cla-not-required, type:fix

#585 fix(datagrid): disable autocomplete on filter input (backport to 13.x)
  projects/angular/src/data/datagrid/built-in/filters/datagrid-numeric-filter.ts
  projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.ts
Labels: cla-not-required, backport

#584 chore: update actions to avoid deprecated features
  .github/workflows/accept-merged-visual-changes.yml
  .github/workflows/label-stale-threads.yml
  .github/workflows/lock-inactive-threads.yml
  .github/workflows/pr-build.yml
  .github/workflows/pr-comment-bot.yml
  .github/workflows/pr-preview.yml
  .github/workflows/pr-visual-regression.yml
  .github/workflows/release-preview.yml
  .github/workflows/release.yml
Labels: cla-not-required, type:chore

#588 chore: fetch just head commit in release workflows
  .github/workflows/release-preview.yml
  .github/workflows/release.yml
Labels: cla-not-required, type:chore

#587 chore: update actions to avoid deprecated features (backport to 13.x)
  .github/workflows/pr-build.yml
  .github/workflows/release-preview.yml
  .github/workflows/release.yml
Labels: cla-not-required, type:chore, backport

#594 fix(datagrid): apply min/max filter placeholder values from column (backport to 13.x)
  projects/angular/src/data/datagrid/datagrid-column.ts
Labels: cla-not-required, type:fix, backport

#592 chore(datagrid): remove redundant default values for filter placeholders
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-column.ts
Labels: cla-not-required, type:chore

#597 chore: enable Angular's strict checks in library and demo app (backport to 13.x)
  projects/angular/src/utils/focus-trap/focus-trap.ts
  projects/demo/src/app/cds-theme-select.component.ts
  projects/demo/src/app/overlay-clipping/overlay-clipping.demo.html
  projects/demo/tsconfig.app.json
  tsconfig.json
Labels: cla-not-required, type:chore, backport

#577 fix(button): navigate menu via keyboard with focus
  projects/angular/clarity.api.md
  projects/angular/src/button/all.spec.ts
  projects/angular/src/button/button-group/button-group.html
  projects/angular/src/button/button-group/button-group.ts
  projects/angular/src/button/button-group/button.spec.ts
  projects/angular/src/button/button-group/button.ts
  projects/angular/src/button/providers/button-group-focus-handler.service.ts
  projects/angular/src/button/providers/button-group-focus-handler.spec.ts
  projects/angular/src/button/providers/button-group-focus.enum.ts
  projects/angular/src/button/providers/button-in-group.service.spec.ts
  projects/angular/src/utils/focus/focus.service.ts
Labels: cla-not-required, type:fix, waiting:needs-a11y

#604 chore: checkout the correct commit in "PR Visual Snapshot Update Bot"
  .github/workflows/pr-visual-snapshot-update-bot.yml
Labels: cla-not-required, type:chore
