Repository vmware-clarity/ng-clarity, pull requests merged in 2023-06, with the labels that each got.

#733 chore(datagrid): add screenshot variants for multi/single row selection
  .storybook/stories/datagrid/datagrid-row.stories.ts
  tests/snapshots/datagrid/row--variants-core-dark.png
  tests/snapshots/datagrid/row--variants-core-light.png
  tests/snapshots/datagrid/row--variants-high-contrast.png
  tests/snapshots/datagrid/row--variants-ng-dark.png
  tests/snapshots/datagrid/row--variants-ng-light.png
Labels: cla-not-required

#734 fix(datgrid): resolve centering issue with checkbox
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  tests/snapshots/datagrid/row--variants-core-dark.png
  tests/snapshots/datagrid/row--variants-core-light.png
  tests/snapshots/datagrid/row--variants-high-contrast.png
  tests/snapshots/datagrid/row--variants-ng-dark.png
  tests/snapshots/datagrid/row--variants-ng-light.png
Labels: cla-not-required

#731 chore(signpost): style documentation
  projects/angular/src/popover/signpost/STYLES.md
Labels: cla-not-required

#714 chore: add alert css docs
  projects/angular/src/emphasis/alert/STYLES.md
Labels: type:chore, website / documentation

#726 chore: add forms css docs
  projects/angular/src/forms/STYLES.MD
Labels: cla-not-required, type:chore, website / documentation

#727 chore: add modal css docs
  projects/angular/src/modal/STYLES.md
Labels: cla-not-required, type:chore, website / documentation

#728 chore(select): add CSS classes and custom properties documentation
  projects/angular/src/forms/select/STYLES.md
Labels: cla-not-required

#739 fix(accordion): display nested accordions correctly
  .storybook/stories/accordion/nested-accordion.stories.ts
  projects/angular/src/accordion/_accordion.clarity.scss
  projects/angular/src/accordion/accordion-panel.html
  tests/snapshots/accordion/nested-accordion--variants-core-dark.png
  tests/snapshots/accordion/nested-accordion--variants-core-light.png
  tests/snapshots/accordion/nested-accordion--variants-high-contrast.png
  tests/snapshots/accordion/nested-accordion--variants-ng-dark.png
  tests/snapshots/accordion/nested-accordion--variants-ng-light.png
Labels: cla-not-required, type:fix

#740 fix(accordion): display nested accordions correctly (backport to 13.x)
  .storybook/stories/accordion/nested-accordion.stories.ts
  projects/angular/src/accordion/_accordion.clarity.scss
  projects/angular/src/accordion/accordion-panel.html
  tests/snapshots/accordion/nested-accordion--variants-core-dark.png
  tests/snapshots/accordion/nested-accordion--variants-core-light.png
  tests/snapshots/accordion/nested-accordion--variants-high-contrast.png
  tests/snapshots/accordion/nested-accordion--variants-ng-dark.png
  tests/snapshots/accordion/nested-accordion--variants-ng-light.png
Labels: cla-not-required, type:fix, backport

#735 fix(package): change peer dependency to `@clr/angular` -> `@clr/ui`
  scripts/semantic-release-add-peer-dependency.js
Labels: cla-not-required, type:fix

#736 fix(package): change peer dependency to `@clr/angular` -> `@clr/ui` (backport to 13.x)
  scripts/semantic-release-add-peer-dependency.js
Labels: cla-not-required, type:fix, backport

#743 fix(datagrid): resolve centering issue with checkbox (backport to 13.x)
  .storybook/stories/datagrid/datagrid-row.stories.ts
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  tests/snapshots/datagrid/row--variants-core-dark.png
  tests/snapshots/datagrid/row--variants-core-light.png
  tests/snapshots/datagrid/row--variants-high-contrast.png
  tests/snapshots/datagrid/row--variants-ng-dark.png
  tests/snapshots/datagrid/row--variants-ng-light.png
Labels: cla-not-required, type:fix, backport

#723 fix(header): add `role="banner"` by default
  .storybook/stories/header/header.stories.ts
  projects/angular/clarity.api.md
  projects/angular/src/layout/nav/header.spec.ts
  projects/angular/src/layout/nav/header.ts
Labels: cla-not-required, type:fix

#709 chore: add badge css docs
  projects/angular/src/emphasis/STYLES.md
Labels: cla-not-required, type:chore, website / documentation

#741 chore(tabs): style documentation
  projects/angular/src/layout/tabs/STYLE.md
Labels: cla-not-required

#742 chore(checkbox): add CSS classes and custom properties documentation
  projects/angular/src/forms/checkbox/STYLES.md
Labels: cla-not-required

#720 chore: css documentation for combobox
  projects/angular/src/forms/combobox/STYLES.md
Labels: cla-not-required

#745 chore: add datepicker css docs
  projects/angular/src/forms/datepicker/STYLES.md
Labels: cla-not-required, type:chore, website / documentation

#747 chore: add progress bar css docs
  projects/angular/src/progress/progress-bars/STYLES.md
Labels: cla-not-required, type:chore, website / documentation

#746 chore: css documentation for main layout and headers
  projects/angular/src/forms/combobox/STYLES.md
  projects/angular/src/layout/main-container/STYLES.md
Labels: cla-not-required

#749 chore: add tree view css docs
  projects/angular/src/data/tree-view/STYLES.md
Labels: cla-not-required, type:chore, website / documentation

#751 chore: (lists) add CSS classes documentation
  projects/angular/src/typography/STYLES.md
Labels: cla-not-required

#752 chore(button group): add style documentation
  projects/angular/src/button/button-group/STYLE.md
Labels: cla-not-required

#754 chore: add stack view css docs
  projects/angular/src/data/stack-view/STYLES.md
Labels: cla-not-required, type:chore, website / documentation

#756 fix(datagrid): change manage columns popover close button color on hover
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
Labels: cla-not-required, type:fix

#762 chore(modal): declare `_open` property on a single line
  projects/angular/src/modal/modal.ts
Labels: cla-not-required, type:chore

#759 chore: css docs for tooltip
  projects/angular/src/popover/tooltip/STYLES.md
Labels: cla-not-required

#765 chore: css documentation for wizard
  projects/angular/src/wizard/STYLES.md
Labels: cla-not-required

#758 chore: add css documentation for the grid system
  projects/angular/src/layout/grid/STYLES.md
Labels: cla-not-required

#738 chore: accordion documentation for css
  projects/angular/src/accordion/STYLES.md
Labels: cla-not-required

#713 chore(spinner): add css documentation
  projects/angular/src/progress/spinner/STYLES.md
Labels: cla-not-required

#716 chore: add documentation for range component
  projects/angular/src/forms/range/STYLES.md
Labels: cla-not-required

#719 chore: add dropdown documentation
  projects/angular/src/popover/dropdown/STYLES.md
Labels: cla-not-required

#767 fix(select): change caret color on hover (backport to 13.x)
  projects/angular/src/forms/styles/_select.clarity.scss
Labels: cla-not-required, type:fix, backport

#768 fix(datagrid): change manage columns popover close button color on hover (backport to 13.x)
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
Labels: cla-not-required, type:fix, backport

#721 chore: add radio documentation
  projects/angular/src/forms/radio/STYLES.md
Labels: cla-not-required

#724 chore: add label documentation
  projects/angular/src/forms/common/STYLES.label.md
Labels: cla-not-required

#778 chore: add title to readme
  README.md
Labels: cla-not-required

#779 chore: remove debug line from scss file
  projects/angular/src/utils/variables/_properties.global.scss
Labels: cla-not-required, type:chore

#760 fix(accordion): style disabled panel button correctly
  projects/angular/src/accordion/_accordion.clarity.scss
  projects/angular/src/accordion/_properties.accordion.scss
  projects/angular/src/accordion/_variables.accordion.scss
  projects/angular/src/utils/_theme.dark.clarity.scss
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/accordion/accordion-panel--variants-core-dark.png
  tests/snapshots/accordion/accordion-panel--variants-core-light.png
  tests/snapshots/accordion/accordion-panel--variants-high-contrast.png
  tests/snapshots/accordion/accordion-panel--variants-ng-dark.png
  tests/snapshots/accordion/accordion-panel--variants-ng-light.png
Labels: cla-not-required, type:fix

#761 fix(accordion): style disabled panel button correctly (backport to 13.x)
  projects/angular/src/accordion/_accordion.clarity.scss
  projects/angular/src/accordion/_properties.accordion.scss
  projects/angular/src/accordion/_variables.accordion.dark.scss
  projects/angular/src/accordion/_variables.accordion.scss
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/accordion/accordion-panel--variants-core-dark.png
  tests/snapshots/accordion/accordion-panel--variants-core-light.png
  tests/snapshots/accordion/accordion-panel--variants-high-contrast.png
  tests/snapshots/accordion/accordion-panel--variants-ng-dark.png
  tests/snapshots/accordion/accordion-panel--variants-ng-light.png
Labels: cla-not-required, type:fix, backport

#777 chore: rename `beta` prerelease channel to `next`
  .releaserc.js
Labels: cla-not-required, type:chore

#784 chore: update style doc wording for card and login
  projects/angular/src/layout/API.md
  projects/angular/src/layout/STYLES.md
Labels: cla-not-required, type:chore

#707 chore: add button css docs
  projects/angular/src/button/STYLES.md
Labels: type:chore, website / documentation

#788 chore: move `_build:ui` script before sub-tasks
  package.json
Labels: cla-not-required, type:chore

#786 chore: delete leftover accordion style API.md file
  projects/angular/src/accordion/API.md
Labels: cla-not-required, type:chore

#789 chore: prevent "element not focusable" warning in tests
  projects/angular/src/utils/popover/stop-escape-propagation.directive.spec.ts
Labels: cla-not-required, type:chore
