Repository vmware-clarity/ng-clarity, pull requests merged in 2023-01, with the labels that each got.

#449 fix(datagrid): show full border when detail pane is open
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
Labels: cla-not-required, type:fix

#454 chore: remove unnecessary annotation comment
  projects/angular/src/popover/common/abstract-popover.ts
Labels: cla-not-required, type:chore

#453 chore: rename `ELement` to `Element`
  .storybook/helpers/elements.data.ts
  .storybook/stories/datagrid/datagrid-detail.stories.ts
Labels: cla-not-required, type:chore

#447 fix(tooltip): keep tooltip content visible as user hovers
  projects/angular/clarity.api.md
  projects/angular/src/popover/tooltip/_tooltips.clarity.scss
  projects/angular/src/popover/tooltip/all.spec.ts
  projects/angular/src/popover/tooltip/providers/tooltip-mouse.service.spec.ts
  projects/angular/src/popover/tooltip/providers/tooltip-mouse.service.ts
  projects/angular/src/popover/tooltip/tooltip-content.ts
  projects/angular/src/popover/tooltip/tooltip-trigger.spec.ts
  projects/angular/src/popover/tooltip/tooltip-trigger.ts
  projects/angular/src/popover/tooltip/tooltip.ts
Labels: cla-not-required, type:fix, a11y

#456 feat(datagrid): rename `closeCheck` method `close`
  .storybook/stories/datagrid/datagrid-detail.stories.ts
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-detail.ts
Labels: cla-not-required, type:breaking-change

#445 feat: remove `datepickerToggle` fallback common string property
  projects/angular/clarity.api.md
  projects/angular/src/forms/datepicker/date-container.ts
  projects/angular/src/utils/i18n/common-strings.default.ts
  projects/angular/src/utils/i18n/common-strings.interface.ts
Labels: cla-not-required, type:breaking-change

#455 fix(modal): capture and return focus
  projects/angular/src/modal/modal.html
Labels: cla-not-required, type:fix, beta

#463 fix(wizard): restore wizard sidenav scss variables
  projects/angular/src/utils/_overwrites.clarity.scss
  projects/angular/src/utils/_theme.dark.clarity.scss
Labels: cla-not-required, type:fix, beta

#466 fix(modal): prevent scrolling content under modal when tabbing
  projects/angular/src/modal/modal.html
Labels: cla-not-required, type:fix, beta

#468 fix(tabs): ensure tabs are announced in the correct order
  projects/angular/clarity.api.md
  projects/angular/src/layout/tabs/tabs.ts
Labels: cla-not-required

#479 fix(datepicker): skip updating toggle button attributes when disabled
  projects/angular/src/forms/datepicker/date-container.ts
Labels: cla-not-required, type:fix

#481 feat: remove deprecated, unused `$clr-monoFont` scss variable
  projects/angular/src/utils/variables/_variables.typography.scss
Labels: cla-not-required, type:breaking-change

#483 fix: prevent error on destroy in `StopEscapePropagationDirective`
  projects/angular/src/utils/popover/stop-escape-propagation.directive.ts
Labels: cla-not-required, type:fix, beta
