Repository vmware-clarity/ng-clarity, pull requests merged in 2024-05, with the labels that each got.

#1378 fix(a11y): update role to radiogroup for radio group control
  projects/angular/src/forms/radio/radio-container.ts
Labels: cla-not-required

#1377 fix(forms): compact layout alignment fixes
  projects/angular/src/forms/styles/_containers.clarity.scss
  projects/angular/src/forms/styles/_radio.clarity.scss
Labels: cla-not-required

#1383 fix(a11y): treeview incorrect levels
  projects/angular/src/data/tree-view/recursive-children.ts
Labels: cla-not-required, auto-backport-to-16.x

#1387 chore: update missed licensed files
  .storybook/preview.js
  projects/angular/src/forms/combobox/combobox.html
  projects/angular/src/forms/datepicker/datepicker-view-manager.html
  projects/demo/src/app/datepicker/datepicker-min-max.html
  projects/demo/src/app/typography/typography-font-autopsy.html
  projects/demo/src/app/typography/utils/font-switcher.html
Labels: cla-not-required, auto-backport-to-16.x

#1386 fix(a11y): aria-label in datagrid header is not announced by screen reader
  projects/angular/src/data/datagrid/datagrid-row.html
  projects/angular/src/data/datagrid/datagrid.html
  projects/angular/src/data/datagrid/datagrid.spec.ts
Labels: cla-not-required, auto-backport-to-16.x

#1346 feat(datagrid): optimise layout rendering
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  projects/angular/src/data/datagrid/datagrid.ts
  projects/angular/src/data/datagrid/interfaces/column-state.interface.ts
  projects/angular/src/data/datagrid/render/cell-renderer.spec.ts
  projects/angular/src/data/datagrid/render/cell-renderer.ts
  projects/angular/src/data/datagrid/render/header-renderer.spec.ts
  projects/angular/src/data/datagrid/render/header-renderer.ts
  projects/angular/src/data/datagrid/render/main-renderer.spec.ts
  projects/angular/src/data/datagrid/render/main-renderer.ts
  projects/angular/src/data/datagrid/render/render-organizer.ts
  projects/angular/src/data/datagrid/render/row-renderer.spec.ts
  projects/angular/src/data/datagrid/render/row-renderer.ts
  projects/angular/src/utils/animations/expandable-animation/expandable-animation.ts
  projects/angular/src/utils/dom-adapter/dom-adapter.ts
  tests/snapshots/chromium/datagrid/action-overflow--action-overflow-core-dark.png
  tests/snapshots/chromium/datagrid/action-overflow--action-overflow-core-light.png
  tests/snapshots/chromium/datagrid/datagrid--compact-core-dark.png
  tests/snapshots/chromium/datagrid/datagrid--compact-core-light.png
  tests/snapshots/chromium/datagrid/datagrid--compact-single-select-core-dark.png
  tests/snapshots/chromium/datagrid/datagrid--compact-single-select-core-light.png
  tests/snapshots/chromium/datagrid/datagrid--datagrid-core-dark.png
  tests/snapshots/chromium/datagrid/datagrid--datagrid-core-light.png
  tests/snapshots/chromium/datagrid/datagrid--manage-columns-core-dark.png
  tests/snapshots/chromium/datagrid/datagrid--manage-columns-core-light.png
  tests/snapshots/chromium/datagrid/datagrid--single-select-core-dark.png
  tests/snapshots/chromium/datagrid/datagrid--single-select-core-light.png
  tests/snapshots/chromium/datagrid/detail--detail-core-dark.png
  tests/snapshots/chromium/datagrid/detail--detail-core-light.png
  tests/snapshots/chromium/datagrid/expandable-rows--expandable-rows-core-dark.png
  tests/snapshots/chromium/datagrid/expandable-rows--expandable-rows-core-light.png
  tests/snapshots/chromium/datagrid/modal-stacked-on-detail--modal-stacked-on-detail-core-dark.png
  tests/snapshots/chromium/datagrid/modal-stacked-on-detail--modal-stacked-on-detail-core-light.png
  tests/snapshots/chromium/datagrid/nested-detail-in-detail--nested-detail-in-detail-core-dark.png
  tests/snapshots/chromium/datagrid/nested-detail-in-detail--nested-detail-in-detail-core-light.png
  tests/snapshots/chromium/datagrid/nested-popover-in-detail--nested-popover-in-detail-core-dark.png
  tests/snapshots/chromium/datagrid/nested-popover-in-detail--nested-popover-in-detail-core-light.png
  tests/snapshots/chromium/datagrid/page-size--page-size-core-dark.png
  tests/snapshots/chromium/datagrid/page-size--page-size-core-light.png
  tests/snapshots/chromium/datagrid/pagination--pagination-core-dark.png
  tests/snapshots/chromium/datagrid/pagination--pagination-core-light.png
  tests/snapshots/chromium/datagrid/row--row-core-dark.png
  tests/snapshots/chromium/datagrid/row--row-core-light.png
  tests/snapshots/chromium/datagrid/row--single-selection-core-dark.png
  tests/snapshots/chromium/datagrid/row--single-selection-core-light.png
  tests/snapshots/firefox/datagrid/expandable-rows--expandable-rows-core-dark.png
  tests/snapshots/firefox/datagrid/expandable-rows--expandable-rows-core-light.png
Labels: cla-not-required, type:feat, auto-backport-to-16.x

#1374 fix(datalist): use label size from `clrForm` directive
  .storybook/stories/datalist/datalist.stories.ts
  .storybook/stories/forms/forms-reactive.stories.ts
  .storybook/stories/forms/forms-template-driven.stories.ts
  projects/angular/src/forms/datalist/datalist-container.ts
  tests/snapshots/chromium/datalist/datalist--datalist-core-dark.png
  tests/snapshots/chromium/datalist/datalist--datalist-core-light.png
  tests/snapshots/chromium/datalist/datalist--disabled-core-dark.png
  tests/snapshots/chromium/datalist/datalist--disabled-core-light.png
  tests/snapshots/chromium/forms/reactive--compact-layout-core-dark.png
  tests/snapshots/chromium/forms/reactive--compact-layout-core-light.png
  tests/snapshots/chromium/forms/reactive--horizontal-layout-core-dark.png
  tests/snapshots/chromium/forms/reactive--horizontal-layout-core-light.png
  tests/snapshots/chromium/forms/reactive--horizontal-layout-label-size-6-core-dark.png
  tests/snapshots/chromium/forms/reactive--horizontal-layout-label-size-6-core-light.png
  tests/snapshots/chromium/forms/reactive--vertical-layout-core-dark.png
  tests/snapshots/chromium/forms/reactive--vertical-layout-core-light.png
  tests/snapshots/chromium/forms/template-driven--compact-layout-core-dark.png
  tests/snapshots/chromium/forms/template-driven--compact-layout-core-light.png
  tests/snapshots/chromium/forms/template-driven--horizontal-layout-core-dark.png
  tests/snapshots/chromium/forms/template-driven--horizontal-layout-core-light.png
  tests/snapshots/chromium/forms/template-driven--horizontal-layout-label-size-6-core-dark.png
  tests/snapshots/chromium/forms/template-driven--horizontal-layout-label-size-6-core-light.png
  tests/snapshots/chromium/forms/template-driven--vertical-layout-core-dark.png
  tests/snapshots/chromium/forms/template-driven--vertical-layout-core-light.png
  tests/snapshots/firefox/datalist/datalist--datalist-core-dark.png
  tests/snapshots/firefox/datalist/datalist--datalist-core-light.png
  tests/snapshots/firefox/datalist/datalist--disabled-core-dark.png
  tests/snapshots/firefox/datalist/datalist--disabled-core-light.png
  tests/snapshots/firefox/forms/reactive--compact-layout-core-dark.png
  tests/snapshots/firefox/forms/reactive--compact-layout-core-light.png
  tests/snapshots/firefox/forms/reactive--horizontal-layout-core-dark.png
  tests/snapshots/firefox/forms/reactive--horizontal-layout-core-light.png
  tests/snapshots/firefox/forms/reactive--horizontal-layout-label-size-6-core-dark.png
  tests/snapshots/firefox/forms/reactive--horizontal-layout-label-size-6-core-light.png
  tests/snapshots/firefox/forms/reactive--vertical-layout-core-dark.png
  tests/snapshots/firefox/forms/reactive--vertical-layout-core-light.png
  tests/snapshots/firefox/forms/template-driven--compact-layout-core-dark.png
  tests/snapshots/firefox/forms/template-driven--compact-layout-core-light.png
  tests/snapshots/firefox/forms/template-driven--horizontal-layout-core-dark.png
  tests/snapshots/firefox/forms/template-driven--horizontal-layout-core-light.png
  tests/snapshots/firefox/forms/template-driven--horizontal-layout-label-size-6-core-dark.png
  tests/snapshots/firefox/forms/template-driven--horizontal-layout-label-size-6-core-light.png
  tests/snapshots/firefox/forms/template-driven--vertical-layout-core-dark.png
  tests/snapshots/firefox/forms/template-driven--vertical-layout-core-light.png
Labels: type:fix

#1298 chore(tree): conditionally render child nodes in tree node story
  .storybook/stories/tree/tree-node.stories.ts
Labels: cla-not-required, type:chore

#1393 chore: add assistiv-labs and browserstack to readme (#1182)
  README.md
Labels: cla-not-required

#1394 fix(a11y): stepper-announce step complete/error on vo safari
  projects/angular/src/accordion/accordion-panel.html
  projects/angular/src/accordion/stepper/stepper-panel.spec.ts
  projects/angular/src/accordion/stepper/stepper-panel.ts
Labels: cla-not-required, auto-backport-to-16.x

#1376 feat(wizard): add back inline wizards in 17.x
  .storybook/stories/modal/modal.stories.ts
  projects/angular/clarity.api.md
  projects/angular/src/modal/modal.ts
  projects/angular/src/wizard/_wizard.clarity.scss
  projects/angular/src/wizard/wizard.html
  projects/angular/src/wizard/wizard.ts
  projects/demo/src/app/wizard/wizard-inline.demo.html
  projects/demo/src/app/wizard/wizard-inline.demo.ts
  projects/demo/src/app/wizard/wizard.demo.module.ts
  projects/demo/src/app/wizard/wizard.demo.routing.ts
  projects/demo/src/app/wizard/wizard.demo.ts
Labels: cla-not-required

#1396 chore: various fixes for style documentation
  projects/angular/src/forms/STYLES.md
  projects/angular/src/layout/STYLES.md
  projects/angular/src/layout/tabs/STYLES.md
Labels: cla-not-required

#1403 fix(modal): fall back to modal id for dialog `aria-labelledby` attribute
  projects/angular/src/modal/modal.html
  projects/angular/src/modal/modal.spec.ts
  projects/angular/src/modal/modal.ts
Labels: cla-not-required, type:fix

#1401 fix(a11y): return focus to datagrid detail pane toggle button after pane closed in zoom more than 250%
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-detail-header.ts
  projects/angular/src/data/datagrid/providers/detail.service.ts
Labels: cla-not-required, auto-backport-to-16.x

#1408 fix(a11y): return focus to datagrid detail pane toggle button after esc with zoom 250%
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-detail-header.ts
  projects/angular/src/data/datagrid/providers/detail.service.ts
Labels: cla-not-required, auto-backport-to-16.x

#1415 fix(file-input): add vertical spacing between label and browse button
  projects/angular/src/forms/styles/_file-input.clarity.scss
  tests/snapshots/chromium/file-input/file-input--vertical-file-input-core-dark.png
  tests/snapshots/chromium/file-input/file-input--vertical-file-input-core-light.png
  tests/snapshots/chromium/file-input/file-input-states--vertical-file-input-states-core-dark.png
  tests/snapshots/chromium/file-input/file-input-states--vertical-file-input-states-core-light.png
  tests/snapshots/firefox/file-input/file-input--vertical-file-input-core-dark.png
  tests/snapshots/firefox/file-input/file-input--vertical-file-input-core-light.png
  tests/snapshots/firefox/file-input/file-input-states--vertical-file-input-states-core-dark.png
  tests/snapshots/firefox/file-input/file-input-states--vertical-file-input-states-core-light.png
Labels: cla-not-required, type:fix, auto-backport-to-16.x
