Repository vmware-clarity/ng-clarity, pull requests merged in 2024-08, with the labels that each got.

#1502 chore: remove assistiv labs from readme
  README.md
Labels: cla-not-required, type:chore

#1491 fix(a11y): update vertical nav selected and hover colors
  projects/angular/src/layout/vertical-nav/_properties.vertical-nav.scss
  projects/ui/src/temp-overrides.scss
  tests/snapshots/chromium/vertical-nav/vertical-header-and-divider--nav-header-and-divider-core-light.png
  tests/snapshots/chromium/vertical-nav/vertical-nav--basic-nav-core-light.png
  tests/snapshots/chromium/vertical-nav/vertical-nav--collapsed-core-light.png
  tests/snapshots/chromium/vertical-nav/vertical-nav--collapsible-with-icons-core-light.png
  tests/snapshots/chromium/vertical-nav/vertical-nav--expanded-core-light.png
  tests/snapshots/chromium/vertical-nav/vertical-nav--non-collapsible-with-icons-core-light.png
  tests/snapshots/chromium/vertical-nav/vertical-nav-group--basic-nav-group-expanded-core-light.png
  tests/snapshots/chromium/vertical-nav/vertical-nav-group--nav-group-expanded-with-icons-core-light.png
  tests/snapshots/firefox/vertical-nav/vertical-nav--basic-nav-core-light.png
  tests/snapshots/firefox/vertical-nav/vertical-nav--collapsed-core-light.png
  tests/snapshots/firefox/vertical-nav/vertical-nav--collapsible-with-icons-core-light.png
  tests/snapshots/firefox/vertical-nav/vertical-nav--expanded-core-light.png
  tests/snapshots/firefox/vertical-nav/vertical-nav--non-collapsible-with-icons-core-light.png
  tests/snapshots/firefox/vertical-nav/vertical-nav-group--basic-nav-group-expanded-core-light.png
  tests/snapshots/firefox/vertical-nav/vertical-nav-group--nav-group-expanded-with-icons-core-light.png
Labels: cla-not-required

#1500 fix(spinner): override wrong tokens mapping
  .storybook/stories/spinner/spinner.stories.ts
  projects/angular/src/progress/spinner/STYLES.md
  projects/demo/src/app/spinners/spinner-types.html
  projects/demo/src/app/spinners/spinner.demo.scss
  projects/ui/src/temp-overrides.scss
  tests/snapshots/chromium/spinner/spinner--inline-inverse-core-dark.png
  tests/snapshots/chromium/spinner/spinner--inline-inverse-core-light.png
  tests/snapshots/chromium/spinner/spinner--inverse-core-dark.png
  tests/snapshots/chromium/spinner/spinner--inverse-core-light.png
  tests/snapshots/chromium/spinner/spinner--medium-inverse-core-dark.png
  tests/snapshots/chromium/spinner/spinner--medium-inverse-core-light.png
  tests/snapshots/chromium/spinner/spinner--small-inverse-core-dark.png
  tests/snapshots/chromium/spinner/spinner--small-inverse-core-light.png
  tests/snapshots/firefox/spinner/spinner--inline-inverse-core-dark.png
  tests/snapshots/firefox/spinner/spinner--inline-inverse-core-light.png
  tests/snapshots/firefox/spinner/spinner--inverse-core-dark.png
  tests/snapshots/firefox/spinner/spinner--inverse-core-light.png
  tests/snapshots/firefox/spinner/spinner--medium-inverse-core-dark.png
  tests/snapshots/firefox/spinner/spinner--medium-inverse-core-light.png
  tests/snapshots/firefox/spinner/spinner--small-inverse-core-dark.png
  tests/snapshots/firefox/spinner/spinner--small-inverse-core-light.png
Labels: cla-not-required, type:fix

#1503 fix(signpost): vertical overflow and long content pointer position
  .storybook/stories/signpost/signpost.stories.ts
  projects/angular/src/popover/signpost/_signposts.clarity.scss
  projects/demo/src/app/signpost/signpost.demo.html
  projects/demo/src/app/signpost/signpost.demo.ts
  tests/snapshots/chromium/signpost/signpost--initial-core-dark.png
  tests/snapshots/chromium/signpost/signpost--initial-core-light.png
  tests/snapshots/chromium/signpost/signpost--opened-core-dark.png
  tests/snapshots/chromium/signpost/signpost--opened-core-light.png
  tests/snapshots/chromium/signpost/signpost--opened-long-content-core-dark.png
  tests/snapshots/chromium/signpost/signpost--opened-long-content-core-light.png
  tests/snapshots/firefox/signpost/signpost--initial-core-dark.png
  tests/snapshots/firefox/signpost/signpost--initial-core-light.png
  tests/snapshots/firefox/signpost/signpost--opened-core-dark.png
  tests/snapshots/firefox/signpost/signpost--opened-core-light.png
  tests/snapshots/firefox/signpost/signpost--opened-long-content-core-dark.png
  tests/snapshots/firefox/signpost/signpost--opened-long-content-core-light.png
Labels: cla-not-required, type:fix

#1478 fix(wizard): redesign wizard stepnav (add success icon and align states)
  projects/angular/src/wizard/STYLES.md
  projects/angular/src/wizard/_properties.wizard.scss
  projects/angular/src/wizard/_variables.wizard.scss
  projects/angular/src/wizard/_wizard.clarity.scss
  projects/angular/src/wizard/wizard-stepnav-item.spec.ts
  projects/angular/src/wizard/wizard-stepnav-item.ts
  projects/angular/src/wizard/wizard.module.ts
  tests/snapshots/chromium/wizard/wizard--full-screen-wizard-core-dark.png
  tests/snapshots/chromium/wizard/wizard--full-screen-wizard-core-light.png
  tests/snapshots/chromium/wizard/wizard--wizard-core-dark.png
  tests/snapshots/chromium/wizard/wizard--wizard-core-light.png
  tests/snapshots/chromium/wizard/wizard-long-titles--wizard-long-titles-core-dark.png
  tests/snapshots/chromium/wizard/wizard-long-titles--wizard-long-titles-core-light.png
  tests/snapshots/chromium/wizard/wizard-page--wizard-page-core-dark.png
  tests/snapshots/chromium/wizard/wizard-page--wizard-page-core-light.png
  tests/snapshots/chromium/wizard/wizard-page--wizard-page-status-indicators-core-dark.png
  tests/snapshots/chromium/wizard/wizard-page--wizard-page-status-indicators-core-light.png
  tests/snapshots/firefox/wizard/wizard--full-screen-wizard-core-dark.png
  tests/snapshots/firefox/wizard/wizard--full-screen-wizard-core-light.png
  tests/snapshots/firefox/wizard/wizard--wizard-core-dark.png
  tests/snapshots/firefox/wizard/wizard--wizard-core-light.png
  tests/snapshots/firefox/wizard/wizard-long-titles--wizard-long-titles-core-dark.png
  tests/snapshots/firefox/wizard/wizard-long-titles--wizard-long-titles-core-light.png
  tests/snapshots/firefox/wizard/wizard-page--wizard-page-core-dark.png
  tests/snapshots/firefox/wizard/wizard-page--wizard-page-core-light.png
  tests/snapshots/firefox/wizard/wizard-page--wizard-page-status-indicators-core-dark.png
  tests/snapshots/firefox/wizard/wizard-page--wizard-page-status-indicators-core-light.png
Labels: cla-not-required, type:feat

#1511 chore: refactor active element assertions
  projects/angular/src/button/providers/button-group-focus-handler.spec.ts
  projects/angular/src/data/datagrid/datagrid-action-overflow.spec.ts
  projects/angular/src/data/datagrid/datagrid-virtual-scroll.directive.spec.ts
  projects/angular/src/data/datagrid/datagrid.spec.ts
  projects/angular/src/data/datagrid/providers/detail.service.spec.ts
  projects/angular/src/forms/datepicker/date-container.spec.ts
  projects/angular/src/modal/modal.spec.ts
  projects/angular/src/modal/side-panel.spec.ts
  projects/angular/src/wizard/wizard.spec.ts
Labels: cla-not-required

#1506 fix(modal): backdrop click focus to title
  projects/angular/clarity.api.md
  projects/angular/src/modal/modal.html
  projects/angular/src/modal/modal.spec.ts
  projects/angular/src/modal/modal.ts
Labels: cla-not-required, type:fix, auto-backport-to-16.x

#1508 fix(combobox): use specific line height
  projects/angular/src/forms/combobox/_combobox.clarity.scss
Labels: cla-not-required, type:fix

#1514 fix(modal): backdrop click focus to title (backport to 16.x)
  projects/angular/src/forms/combobox/_combobox.clarity.scss
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required, type:fix, v16

#1516 fix(datagrid): opened details missing vertical separator (backport to 16.x)
  .storybook/helpers/common.ts
  .storybook/stories/datagrid/datagrid-detail.stories.ts
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  tests/snapshots/chromium/datagrid/detail--detail-core-dark.png
  tests/snapshots/chromium/datagrid/detail--detail-core-light.png
  tests/snapshots/chromium/datagrid/detail--detail-ng-dark.png
  tests/snapshots/chromium/datagrid/detail--detail-ng-light.png
  tests/snapshots/chromium/datagrid/detail--open-detail-core-dark.png
  tests/snapshots/chromium/datagrid/detail--open-detail-core-light.png
  tests/snapshots/chromium/datagrid/detail--open-detail-ng-dark.png
  tests/snapshots/chromium/datagrid/detail--open-detail-ng-light.png
  tests/snapshots/firefox/datagrid/detail--detail-core-dark.png
  tests/snapshots/firefox/datagrid/detail--detail-core-light.png
  tests/snapshots/firefox/datagrid/detail--detail-ng-dark.png
  tests/snapshots/firefox/datagrid/detail--detail-ng-light.png
  tests/snapshots/firefox/datagrid/detail--open-detail-core-dark.png
  tests/snapshots/firefox/datagrid/detail--open-detail-core-light.png
  tests/snapshots/firefox/datagrid/detail--open-detail-ng-dark.png
  tests/snapshots/firefox/datagrid/detail--open-detail-ng-light.png
Labels: cla-not-required, type:fix, v16

#1518 chore: remove commitlint
  .commitlintrc.js
  .czrc
  .husky/commit-msg
  package-lock.json
  package.json
Labels: cla-not-required

#1521 chore(ci): remove Slack post from release process
  .github/workflows/release.yml
  .releaserc.js
  docs/PUBLISHING.md
  package-lock.json
  package.json
Labels: cla-not-required

#1531 chore(forms): remove control height unit tests (backport to 16.x)
  projects/angular/src/forms/styles/containers.spec.ts
Labels: cla-not-required, backport

#1529 chore: remove commitlint (backport to 16.x)
  .commitlintrc.js
  .czrc
  .husky/commit-msg
  package-lock.json
  package.json
Labels: cla-not-required, backport

#1530 chore(ci): remove Slack post from release process (backport to 16.x)
  .github/workflows/release.yml
  .releaserc.js
  docs/PUBLISHING.md
  package-lock.json
  package.json
Labels: cla-not-required, backport

#1522 fix(tooltip): text color of nested list
  projects/angular/src/popover/tooltip/_tooltips.clarity.scss
  projects/demo/src/app/tooltips/tooltips-angular.html
Labels: cla-not-required

#1533 fix(tooltip): text color of nested list (backport to 16.x)
  projects/demo/src/app/tooltips/tooltips-angular.html
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required, type:fix, v16
