Repository vmware-clarity/ng-clarity, pull requests merged in 2024-02, with the labels that each got.

#1182 chore: add assistiv labs to readme
  README.md
Labels: cla-not-required, type:chore

#1183 chore: reword text about VoiceOver behavior
  projects/demo/src/app/i18n-a11y/i18n-a11y.demo.html
Labels: cla-not-required, type:chore, auto-backport-to-next, auto-backport-to-15.x

#1188 chore: update `rxjs` package
  package-lock.json
  package.json
  projects/angular/src/data/datagrid/datagrid-if-expanded.service.ts
  projects/angular/src/utils/chocolate/willy-wonka.ts
  projects/angular/src/utils/focus/key-focus/key-focus.ts
  projects/angular/src/wizard/providers/button-hub.service.ts
  projects/angular/src/wizard/providers/wizard-navigation.service.ts
  projects/angular/src/wizard/wizard.spec.ts
  projects/angular/src/wizard/wizard.ts
  projects/demo/src/app/forms/dynamic-controls/dynamic-controls.demo.ts
Labels: type:chore

#1181 fix(button): change loading button conents from div to span
  projects/angular/src/button/button-loading/loading-button.ts
Labels: cla-not-required, type:fix, auto-backport-to-next, auto-backport-to-15.x

#1109 fix(popover): update positioning logic to render within body
  projects/angular/src/utils/popover/providers/popover-position.service.spec.ts
  projects/angular/src/utils/popover/providers/popover-position.service.ts
Labels: cla-not-required, type:fix, auto-backport-to-next, auto-backport-to-15.x

#1187 fix(signpost): allow keyboard scrolling in overflow content (backport to 15.x)
  projects/angular/src/popover/signpost/signpost-content.ts
Labels: cla-not-required

#1179 fix(a11y): clr-password-container show/hide Icon does not have unique label
  projects/angular/clarity.api.md
  projects/angular/src/forms/password/password-container.spec.ts
  projects/angular/src/forms/password/password-container.ts
  projects/angular/src/utils/i18n/common-strings.default.ts
Labels: cla-not-required

#1180 feat(header): refactor icons, dividers and deprecations
  .storybook/stories/header/header-static.stories.ts
  projects/angular/src/layout/main-container/STYLES.md
  projects/angular/src/layout/main-container/_properties.header.scss
  projects/angular/src/layout/main-container/_variables.header.scss
  projects/angular/src/layout/nav/_header.clarity.scss
  projects/angular/src/layout/nav/_responsive-nav.clarity.scss
  projects/demo/src/app/nav/header-types.demo.html
  tests/snapshots/header/header--variants-core-dark.png
  tests/snapshots/header/header--variants-core-light.png
  tests/snapshots/header/headers-collapsed--variants-core-dark.png
  tests/snapshots/header/headers-collapsed--variants-core-light.png
  tests/snapshots/header/headers-static--variants-core-dark.png
  tests/snapshots/header/headers-static--variants-core-light.png
Labels: cla-not-required

#1184 fix(stepper): improve panel status updates
  projects/angular/src/accordion/stepper/models/stepper.model.ts
  projects/angular/src/accordion/stepper/providers/stepper.service.ts
  projects/angular/src/accordion/stepper/stepper-panel.ts
  projects/angular/src/accordion/stepper/stepper.spec.ts
Labels: cla-not-required, type:fix, auto-backport-to-15.x, auto-backport-to-main

#1202 feat(deps): bump cds/core to 6.9.2
  package-lock.json
  package.json
  projects/angular/package.json
  projects/ui/package.json
Labels: cla-not-required, type:breaking-change

#1204 fix(stepper): improve panel status updates (port to 16.x)
  projects/angular/src/accordion/stepper/models/stepper.model.ts
  projects/angular/src/accordion/stepper/providers/stepper.service.ts
  projects/angular/src/accordion/stepper/stepper-panel.ts
  projects/angular/src/accordion/stepper/stepper.spec.ts
Labels: cla-not-required, type:fix

#1205 fix(stepper): improve panel status updates (port to 15.x)
  projects/angular/src/accordion/stepper/models/stepper.model.ts
  projects/angular/src/accordion/stepper/providers/stepper.service.ts
  projects/angular/src/accordion/stepper/stepper-panel.ts
  projects/angular/src/accordion/stepper/stepper.spec.ts
Labels: cla-not-required, type:fix

#1206 chore: add pr backport workflow (port to `next`)
  .github/workflows/pr-backport.yml
Labels: cla-not-required, type:chore

#1203 fix(ui): remove core imports in clr-ui and add documentation steps
  angular.json
  docs/INSTALLATION.md
  projects/angular/README.md
  projects/ui/README.md
  projects/ui/src/clr-ui.scss
Labels: cla-not-required, type:fix

#1208 fix(alerts): different internal icons and loading and unknown types can be used anywhere
  .storybook/stories/alert/alert.stories.ts
  projects/angular/src/emphasis/alert/_alert.clarity.scss
  projects/angular/src/emphasis/alert/alert.module.ts
  projects/angular/src/emphasis/alert/alert.spec.ts
  projects/angular/src/emphasis/alert/alert.ts
  projects/angular/src/emphasis/alert/providers/icon-and-types.service.spec.ts
  projects/angular/src/emphasis/alert/providers/icon-and-types.service.ts
  projects/demo/src/app/alert/static/alert-app-level.demo.html
  projects/demo/src/app/alert/static/alert-cards.demo.html
  projects/demo/src/app/alert/static/alert-content-area.demo.html
  projects/demo/src/app/alert/static/alert-modals.demo.html
  projects/demo/src/app/alert/static/alert-sizes.demo.html
  projects/demo/src/app/alert/static/alert-styles.demo.html
  projects/demo/src/app/buttons/buttons-test.html
  projects/demo/src/app/datagrid/binding-properties/binding-properties.html
  projects/demo/src/app/datagrid/built-in-filters/built-in-filters.html
  projects/demo/src/app/datagrid/sorting/sorting.html
  projects/demo/src/app/iconography/icon-size.demo.html
  projects/demo/src/app/layout/layout-all.html
  projects/demo/src/app/modal/modal-static-old.demo.html
  tests/snapshots/alert/alert--variants-core-dark.png
  tests/snapshots/alert/alert--variants-core-light.png
  tests/snapshots/alert/alerts--variants-core-dark.png
  tests/snapshots/alert/alerts--variants-core-light.png
Labels: cla-not-required, type:fix, type:breaking-change

#1194 chore(button): update stories for buttons
  .storybook/stories/button/button-group.stories.ts
  .storybook/stories/button/button.stories.ts
  .storybook/stories/button/buttons-all.stories.ts
  .storybook/stories/button/buttons-loading.stories.ts
  tests/snapshots/button/button--button-core-dark.png
  tests/snapshots/button/button--button-core-light.png
  tests/snapshots/button/button--flat-core-dark.png
  tests/snapshots/button/button--flat-core-light.png
  tests/snapshots/button/button--link-core-dark.png
  tests/snapshots/button/button--link-core-light.png
  tests/snapshots/button/button--outline-core-dark.png
  tests/snapshots/button/button--outline-core-light.png
  tests/snapshots/button/button--showcase-core-dark.png
  tests/snapshots/button/button--showcase-core-light.png
  tests/snapshots/button/button--solid-core-dark.png
  tests/snapshots/button/button--solid-core-light.png
  tests/snapshots/button/button--variants-core-dark.png
  tests/snapshots/button/button--variants-core-light.png
  tests/snapshots/button/button-group--button-group-core-dark.png
  tests/snapshots/button/button-group--button-group-core-light.png
  tests/snapshots/button/button-group--disabled-core-dark.png
  tests/snapshots/button/button-group--disabled-core-light.png
  tests/snapshots/button/button-group--variants-core-dark.png
  tests/snapshots/button/button-group--variants-core-light.png
  tests/snapshots/button/button-loading-states--button-loading-states-core-dark.png
  tests/snapshots/button/button-loading-states--button-loading-states-core-light.png
  tests/snapshots/button/button-loading-states--loading-core-dark.png
  tests/snapshots/button/button-loading-states--loading-core-light.png
  tests/snapshots/button/buttons-all--variants-core-dark.png
  tests/snapshots/button/buttons-all--variants-core-light.png
  tests/snapshots/button/buttons-loading-states--variants-core-dark.png
  tests/snapshots/button/buttons-loading-states--variants-core-light.png
Labels: cla-not-required, type:chore

#1210 fix(combobox): use diacritic-insensitive search to filter items
  projects/angular/src/forms/combobox/option-items.directive.spec.ts
  projects/angular/src/forms/combobox/option-items.directive.ts
Labels: cla-not-required, type:fix, auto-backport-to-15.x, auto-backport-to-main

#1199 chore(label): update stories for labels
  .storybook/stories/label/label.stories.ts
  tests/snapshots/label/label--label-core-dark.png
  tests/snapshots/label/label--label-core-light.png
  tests/snapshots/label/label--showcase-core-dark.png
  tests/snapshots/label/label--showcase-core-light.png
  tests/snapshots/label/label--variants-core-dark.png
  tests/snapshots/label/label--variants-core-light.png
Labels: cla-not-required, type:chore

#1214 fix(typography): override cds-text font-weight for headings
  projects/demo/src/app/typography/typography-headings-cds.html
  projects/demo/src/app/typography/typography-headings-cds.ts
  projects/demo/src/app/typography/typography.demo.module.ts
  projects/demo/src/app/typography/typography.demo.routing.ts
  projects/demo/src/app/typography/typography.demo.ts
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/header/header--variants-core-dark.png
  tests/snapshots/header/header--variants-core-light.png
  tests/snapshots/header/header-colors--variants-core-dark.png
  tests/snapshots/header/header-colors--variants-core-light.png
  tests/snapshots/header/headers-collapsed--variants-core-dark.png
  tests/snapshots/header/headers-collapsed--variants-core-light.png
  tests/snapshots/header/headers-collapsed--variants-ng-dark.png
  tests/snapshots/header/headers-collapsed--variants-ng-light.png
  tests/snapshots/header/headers-static--variants-core-dark.png
  tests/snapshots/header/headers-static--variants-core-light.png
Labels: cla-not-required, type:fix

#1198 chore(datepicker, combobox): update stories for datepicker and combobox
  .storybook/stories/combobox/combobox.stories.ts
  .storybook/stories/datepicker/date-container.stories.ts
  .storybook/stories/datepicker/datepicker.stories.ts
  tests/snapshots/combobox/combobox--multi-selection-core-dark.png
  tests/snapshots/combobox/combobox--multi-selection-core-light.png
  tests/snapshots/combobox/combobox--multi-selection-disabled-core-dark.png
  tests/snapshots/combobox/combobox--multi-selection-disabled-core-light.png
  tests/snapshots/combobox/combobox--multi-selection-preselected-core-dark.png
  tests/snapshots/combobox/combobox--multi-selection-preselected-core-light.png
  tests/snapshots/combobox/combobox--single-selection-core-dark.png
  tests/snapshots/combobox/combobox--single-selection-core-light.png
  tests/snapshots/combobox/combobox--single-selection-disabled-core-dark.png
  tests/snapshots/combobox/combobox--single-selection-disabled-core-light.png
  tests/snapshots/combobox/combobox--single-selection-preselected-core-dark.png
  tests/snapshots/combobox/combobox--single-selection-preselected-core-light.png
  tests/snapshots/combobox/combobox--variants-core-dark.png
  tests/snapshots/combobox/combobox--variants-core-light.png
  tests/snapshots/datepicker/datecontainer--date-container-core-dark.png
  tests/snapshots/datepicker/datecontainer--date-container-core-light.png
  tests/snapshots/datepicker/datepicker--datepicker-core-dark.png
  tests/snapshots/datepicker/datepicker--datepicker-core-light.png
  tests/snapshots/datepicker/datepicker--default-date-core-dark.png
  tests/snapshots/datepicker/datepicker--default-date-core-light.png
  tests/snapshots/datepicker/datepicker--disabled-core-dark.png
  tests/snapshots/datepicker/datepicker--disabled-core-light.png
  tests/snapshots/datepicker/datepicker--max-date-core-dark.png
  tests/snapshots/datepicker/datepicker--max-date-core-light.png
  tests/snapshots/datepicker/datepicker--min-date-core-dark.png
  tests/snapshots/datepicker/datepicker--min-date-core-light.png
  tests/snapshots/datepicker/datepicker--variants-core-dark.png
  tests/snapshots/datepicker/datepicker--variants-core-light.png
Labels: cla-not-required, type:chore

#1215 chore(card): update stories for card
  .storybook/stories/card/card.stories.ts
  tests/snapshots/card/card--card-core-dark.png
  tests/snapshots/card/card--card-core-light.png
  tests/snapshots/card/card--variants-core-dark.png
  tests/snapshots/card/card--variants-core-light.png
Labels: cla-not-required

#1213 fix(signpost): set aria-expanded on button during initial render
  projects/angular/src/popover/signpost/signpost-trigger.spec.ts
  projects/angular/src/popover/signpost/signpost-trigger.ts
Labels: cla-not-required, type:fix, auto-backport-to-15.x, auto-backport-to-main

#1201 chore(release): update release to deploy beta to v17 site
  .github/workflows/release.yml
Labels: cla-not-required

#1218 chore(spinner): update stories for spinner
  .storybook/stories/spinner/spinner.stories.ts
  tests/snapshots/spinner/spinner--inline-core-dark.png
  tests/snapshots/spinner/spinner--inline-core-light.png
  tests/snapshots/spinner/spinner--inline-inverse-core-dark.png
  tests/snapshots/spinner/spinner--inline-inverse-core-light.png
  tests/snapshots/spinner/spinner--inverse-core-dark.png
  tests/snapshots/spinner/spinner--inverse-core-light.png
  tests/snapshots/spinner/spinner--medium-core-dark.png
  tests/snapshots/spinner/spinner--medium-core-light.png
  tests/snapshots/spinner/spinner--medium-inverse-core-dark.png
  tests/snapshots/spinner/spinner--medium-inverse-core-light.png
  tests/snapshots/spinner/spinner--small-core-dark.png
  tests/snapshots/spinner/spinner--small-core-light.png
  tests/snapshots/spinner/spinner--small-inverse-core-dark.png
  tests/snapshots/spinner/spinner--small-inverse-core-light.png
  tests/snapshots/spinner/spinner--spinner-core-dark.png
  tests/snapshots/spinner/spinner--spinner-core-light.png
  tests/snapshots/spinner/spinner--variants-core-dark.png
  tests/snapshots/spinner/spinner--variants-core-light.png
Labels: cla-not-required, type:chore

#1221 chore(select): update stories for select
  .storybook/stories/select/select.stories.ts
  tests/snapshots/select/select--select-core-dark.png
  tests/snapshots/select/select--select-core-light.png
Labels: cla-not-required

#1226 fix(modal): use correct backdrop opacity for core theme
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/modal/static--variants-core-dark.png
  tests/snapshots/modal/static--variants-core-light.png
  tests/snapshots/wizard/wizard--variants-core-dark.png
  tests/snapshots/wizard/wizard--variants-core-light.png
  tests/snapshots/wizard/wizard-page--variants-core-dark.png
  tests/snapshots/wizard/wizard-page--variants-core-light.png
Labels: cla-not-required, type:fix

#1227 fix(forms): use helper id on aria-describedby in error/success state
  projects/angular/src/forms/common/wrapped-control.spec.ts
  projects/angular/src/forms/common/wrapped-control.ts
Labels: cla-not-required, type:fix

#1229 chore(forms): simplify wrapped control aria-describedby tests
  projects/angular/src/forms/common/wrapped-control.spec.ts
Labels: cla-not-required, type:chore

#1233 fix(wizard): allow long page titles to wrap in stepnav (backport to next)
  .storybook/stories/wizard/wizard-long-titles.stories.ts
  projects/angular/src/wizard/_properties.wizard.scss
  projects/angular/src/wizard/_wizard.clarity.scss
  tests/snapshots/wizard/wizard--variants-core-dark.png
  tests/snapshots/wizard/wizard--variants-core-light.png
  tests/snapshots/wizard/wizard-long-titles--variants-core-dark.png
  tests/snapshots/wizard/wizard-long-titles--variants-core-light.png
  tests/snapshots/wizard/wizard-page--variants-core-dark.png
  tests/snapshots/wizard/wizard-page--variants-core-light.png
Labels: cla-not-required, type:fix

#1232 fix(wizard): allow long page titles to wrap in stepnav (backport to 15.x)
  .storybook/stories/wizard/wizard-long-titles.stories.ts
  projects/angular/src/wizard/_wizard.clarity.scss
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/wizard/wizard--variants-core-dark.png
  tests/snapshots/wizard/wizard--variants-core-light.png
  tests/snapshots/wizard/wizard-long-titles--variants-core-dark.png
  tests/snapshots/wizard/wizard-long-titles--variants-core-light.png
  tests/snapshots/wizard/wizard-long-titles--variants-ng-dark.png
  tests/snapshots/wizard/wizard-long-titles--variants-ng-light.png
  tests/snapshots/wizard/wizard-page--variants-core-dark.png
  tests/snapshots/wizard/wizard-page--variants-core-light.png
Labels: cla-not-required, type:fix, v15

#1224 fix(button): icon text misalignment when clrLoading is used
  .storybook/stories/button/button-group.stories.ts
  .storybook/stories/button/button.stories.ts
  .storybook/stories/button/buttons-loading.stories.ts
  projects/angular/src/button/_buttons.clarity.scss
  projects/angular/src/button/button-loading/loading-button.ts
  projects/demo/src/app/buttons/button-loading.html
  tests/snapshots/button/button--showcase-core-dark.png
  tests/snapshots/button/button--showcase-core-light.png
  tests/snapshots/button/button-group--button-group-core-dark.png
  tests/snapshots/button/button-group--button-group-core-light.png
  tests/snapshots/button/button-group--button-group-loading-core-dark.png
  tests/snapshots/button/button-group--button-group-loading-core-light.png
  tests/snapshots/button/button-group--disabled-core-dark.png
  tests/snapshots/button/button-group--disabled-core-light.png
  tests/snapshots/button/button-loading-states--button-loading-states-core-dark.png
  tests/snapshots/button/button-loading-states--button-loading-states-core-light.png
Labels: cla-not-required, type:fix, auto-backport-to-main

#1230 chore(dropdown): update stories for dropdown
  .storybook/stories/dropdown/dropdown-item-that-opens-modal.stories.ts
  .storybook/stories/dropdown/dropdown-menu.stories.ts
  .storybook/stories/dropdown/dropdown-static.stories.ts
  .storybook/stories/dropdown/dropdown-tree.stories.ts
  .storybook/stories/dropdown/dropdown.stories.ts
  tests/snapshots/dropdown/dropdown--dropdown-core-dark.png
  tests/snapshots/dropdown/dropdown--dropdown-core-light.png
  tests/snapshots/dropdown/dropdown--icon-button-core-dark.png
  tests/snapshots/dropdown/dropdown--icon-button-core-light.png
  tests/snapshots/dropdown/dropdown--link-button-core-dark.png
  tests/snapshots/dropdown/dropdown--link-button-core-light.png
  tests/snapshots/dropdown/dropdown--outline-button-core-dark.png
  tests/snapshots/dropdown/dropdown--outline-button-core-light.png
  tests/snapshots/dropdown/dropdown--variants-core-dark.png
  tests/snapshots/dropdown/dropdown--variants-core-light.png
  tests/snapshots/dropdown/dropdown-menu--dropdown-menu-core-dark.png
  tests/snapshots/dropdown/dropdown-menu--dropdown-menu-core-light.png
  tests/snapshots/dropdown/dropdown-menu--showcase-core-dark.png
  tests/snapshots/dropdown/dropdown-menu--showcase-core-light.png
  tests/snapshots/dropdown/dropdown-static--dropdown-static-core-dark.png
  tests/snapshots/dropdown/dropdown-static--dropdown-static-core-light.png
  tests/snapshots/dropdown/dropdown-static--variants-core-dark.png
  tests/snapshots/dropdown/dropdown-static--variants-core-light.png
  tests/snapshots/dropdown/dropdown-with-modal--dropdown-with-modal-core-dark.png
  tests/snapshots/dropdown/dropdown-with-modal--dropdown-with-modal-core-light.png
  tests/snapshots/dropdown/dropdown-with-tree--dropdown-with-tree-core-dark.png
  tests/snapshots/dropdown/dropdown-with-tree--dropdown-with-tree-core-light.png
Labels: cla-not-required

#1222 chore(table): updated stories
  .storybook/stories/table/table.stories.ts
  tests/snapshots/table/table--basic-core-dark.png
  tests/snapshots/table/table--basic-core-light.png
  tests/snapshots/table/table--compact-core-dark.png
  tests/snapshots/table/table--compact-core-light.png
  tests/snapshots/table/table--left-aligned-core-dark.png
  tests/snapshots/table/table--left-aligned-core-light.png
  tests/snapshots/table/table--non-bordered-core-dark.png
  tests/snapshots/table/table--non-bordered-core-light.png
  tests/snapshots/table/table--variants-core-dark.png
  tests/snapshots/table/table--variants-core-light.png
  tests/snapshots/table/table--vertical-core-dark.png
  tests/snapshots/table/table--vertical-core-light.png
Labels: cla-not-required

#1235 fix(button): icon text misalignment when clrLoading is used (backport of #1224)
  .storybook/stories/button/button-group.stories.ts
  .storybook/stories/button/button.stories.ts
  .storybook/stories/button/buttons-all.stories.ts
  .storybook/stories/button/buttons-loading.stories.ts
  projects/angular/src/button/_buttons.clarity.scss
  projects/angular/src/button/button-loading/loading-button.ts
  projects/demo/src/app/buttons/button-loading.html
  tests/snapshots/button/button--variants-core-dark.png
  tests/snapshots/button/button--variants-core-light.png
  tests/snapshots/button/button--variants-ng-dark.png
  tests/snapshots/button/button--variants-ng-light.png
  tests/snapshots/button/button-group--variants-core-dark.png
  tests/snapshots/button/button-group--variants-core-light.png
  tests/snapshots/button/button-group--variants-ng-dark.png
  tests/snapshots/button/button-group--variants-ng-light.png
  tests/snapshots/button/buttons-all--variants-core-dark.png
  tests/snapshots/button/buttons-all--variants-core-light.png
  tests/snapshots/button/buttons-all--variants-ng-dark.png
  tests/snapshots/button/buttons-all--variants-ng-light.png
  tests/snapshots/button/buttons-loading-states--variants-core-dark.png
  tests/snapshots/button/buttons-loading-states--variants-core-light.png
  tests/snapshots/button/buttons-loading-states--variants-ng-dark.png
  tests/snapshots/button/buttons-loading-states--variants-ng-light.png
Labels: cla-not-required

#1236 fix(accordion): use disabled color for header description
  projects/angular/src/accordion/_accordion.clarity.scss
Labels: cla-not-required, auto-backport-to-15.x, auto-backport-to-main

#1237 fix(shim): remove body-font-weight override
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required

#1239 chore: delete visual snapshot update branch immediately
  .github/workflows/pr-visual-snapshot-update-bot.yml
Labels: cla-not-required, type:chore

#1238 chore: report visual snapshot update bot status to pull request
  .github/workflows/pr-visual-snapshot-update-bot.yml
Labels: cla-not-required, type:chore

#1228 chore(button-group): simplify template
  projects/angular/src/button/button-group/button-group.html
Labels: cla-not-required, type:chore, auto-backport-to-15.x, auto-backport-to-16.x

#1240 chore: remove workflows that run on `main` from `15.x` branch
  .github/workflows/label-stale-threads.yml
  .github/workflows/lock-inactive-threads.yml
  .github/workflows/pr-comment-bot.yml
  .github/workflows/pr-preview.yml
  .github/workflows/pr-visual-snapshot-update-bot.yml
Labels: cla-not-required, type:chore

#1241 chore: remove workflows that run on `main` from `16.x` branch
  .github/workflows/label-stale-threads.yml
  .github/workflows/lock-inactive-threads.yml
  .github/workflows/pr-backport.yml
  .github/workflows/pr-comment-bot.yml
  .github/workflows/pr-preview.yml
  .github/workflows/pr-visual-snapshot-update-bot.yml
Labels: cla-not-required, type:chore

#1234 chore(datalist): update stories for datalist
  .storybook/stories/datalist/datalist.stories.ts
  tests/snapshots/datalist/datalist--datalist-core-dark.png
  tests/snapshots/datalist/datalist--datalist-core-light.png
  tests/snapshots/datalist/datalist--disabled-core-dark.png
  tests/snapshots/datalist/datalist--disabled-core-light.png
  tests/snapshots/datalist/datalist--variants-core-dark.png
  tests/snapshots/datalist/datalist--variants-core-light.png
Labels: cla-not-required

#1223 chore(list): update stories for lists
  .storybook/stories/list/list.stories.ts
  tests/snapshots/chromium/list/list--list-core-dark.png
  tests/snapshots/chromium/list/list--list-core-light.png
  tests/snapshots/chromium/list/list--unstyled-list-core-dark.png
  tests/snapshots/chromium/list/list--unstyled-list-core-light.png
  tests/snapshots/chromium/list/list--variants-core-dark.png
  tests/snapshots/chromium/list/list--variants-core-light.png
  tests/snapshots/firefox/list/list--list-core-dark.png
  tests/snapshots/firefox/list/list--list-core-light.png
  tests/snapshots/firefox/list/list--unstyled-list-core-dark.png
  tests/snapshots/firefox/list/list--unstyled-list-core-light.png
  tests/snapshots/firefox/list/list--variants-core-dark.png
  tests/snapshots/firefox/list/list--variants-core-light.png
Labels: cla-not-required

#1251 chore(datalist): update stories for datalist
  .storybook/stories/datalist/datalist.stories.ts
  tests/snapshots/chromium/datalist/datalist--datalist-core-dark.png
  tests/snapshots/chromium/datalist/datalist--datalist-core-light.png
  tests/snapshots/chromium/datalist/datalist--disabled-core-dark.png
  tests/snapshots/chromium/datalist/datalist--disabled-core-light.png
  tests/snapshots/chromium/datalist/datalist--variants-core-dark.png
  tests/snapshots/chromium/datalist/datalist--variants-core-light.png
  tests/snapshots/firefox/datalist/datalist--datalist-core-dark.png
  tests/snapshots/firefox/datalist/datalist--datalist-core-light.png
  tests/snapshots/firefox/datalist/datalist--disabled-core-dark.png
  tests/snapshots/firefox/datalist/datalist--disabled-core-light.png
  tests/snapshots/firefox/datalist/datalist--variants-core-dark.png
  tests/snapshots/firefox/datalist/datalist--variants-core-light.png
Labels: cla-not-required

#1245 fix(select): show selected multi-select options when not focused
  .storybook/stories/select/multiple-select.stories.ts
  projects/angular/src/forms/STYLES.MD
  projects/angular/src/forms/styles/_properties.forms.scss
  projects/angular/src/forms/styles/_select.clarity.scss
  projects/angular/src/forms/styles/_variables.forms.scss
  tests/snapshots/chromium/select/multiple-select--multiple-select-core-dark.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-core-light.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-option-core-dark.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-option-core-light.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-options-core-dark.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-options-core-light.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-core-dark.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-core-light.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-option-core-dark.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-option-core-light.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-options-core-dark.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-options-core-light.png
Labels: cla-not-required, type:fix, auto-backport-to-15.x, auto-backport-to-16.x

#1244 fix(modal): prevent error when modal is escaped with a focused input
  projects/angular/src/modal/modal-stack.service.ts
Labels: cla-not-required, type:fix, auto-backport-to-15.x, auto-backport-to-16.x

#1256 fix(select): show selected multi-select options when not focused (port to 16.x)
  .storybook/stories/select/multiple-select.stories.ts
  projects/angular/src/forms/STYLES.MD
  projects/angular/src/forms/styles/_properties.forms.scss
  projects/angular/src/forms/styles/_select.clarity.scss
  projects/angular/src/forms/styles/_variables.forms.scss
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/chromium/select/multiple-select--multiple-select-core-dark.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-core-light.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-ng-dark.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-ng-light.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-option-core-dark.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-option-core-light.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-option-ng-dark.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-option-ng-light.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-options-core-dark.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-options-core-light.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-options-ng-dark.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-options-ng-light.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-core-dark.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-core-light.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-ng-dark.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-ng-light.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-option-core-dark.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-option-core-light.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-option-ng-dark.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-option-ng-light.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-options-core-dark.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-options-core-light.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-options-ng-dark.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-options-ng-light.png
Labels: cla-not-required, backport, auto-backport-to-15.x

#1259 fix(select): show selected multi-select options when not focused (backport to 15.x)
  .storybook/stories/select/multiple-select.stories.ts
  projects/angular/src/forms/STYLES.MD
  projects/angular/src/forms/styles/_properties.forms.scss
  projects/angular/src/forms/styles/_select.clarity.scss
  projects/angular/src/forms/styles/_variables.forms.scss
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/chromium/select/multiple-select--multiple-select-core-dark.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-core-light.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-ng-dark.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-ng-light.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-option-core-dark.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-option-core-light.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-option-ng-dark.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-option-ng-light.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-options-core-dark.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-options-core-light.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-options-ng-dark.png
  tests/snapshots/chromium/select/multiple-select--multiple-select-with-selected-options-ng-light.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-core-dark.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-core-light.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-ng-dark.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-ng-light.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-option-core-dark.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-option-core-light.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-option-ng-dark.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-option-ng-light.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-options-core-dark.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-options-core-light.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-options-ng-dark.png
  tests/snapshots/firefox/select/multiple-select--multiple-select-with-selected-options-ng-light.png
Labels: cla-not-required, type:fix, backport

#1255 chore(tooltips): update stories for tooltips
  .storybook/stories/tooltip/tooltip.stories.ts
  tests/snapshots/chromium/tooltip/tooltip--tooltip-core-dark.png
  tests/snapshots/chromium/tooltip/tooltip--tooltip-core-light.png
  tests/snapshots/firefox/tooltip/tooltip--tooltip-core-dark.png
  tests/snapshots/firefox/tooltip/tooltip--tooltip-core-light.png
Labels: cla-not-required

#1265 fix(tree-view): set node `min-height` instead of `height` (backport of #1264)
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required

#1264 fix(tree-view): set node `min-height` instead of `height`
  projects/angular/src/data/tree-view/_tree-view.clarity.scss
Labels: cla-not-required, type:fix

#1276 fix(datagrid): fix pressed action overflow icon color
  projects/angular/src/data/datagrid/_properties.datagrid.scss
Labels: cla-not-required, auto-backport-to-16.x

#1277 chore(screenshot): add comment to screenshot options
  tests/screenshot-options.ts
Labels: cla-not-required, auto-backport-to-16.x

#1278 fix(datagrid): fix pressed action overflow icon color (backport to 16.x)
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required

#1268 chore(checkbox & toggle): update stories for checkbox and toggle switch
  .storybook/helpers/checkbox-toggle.helpers.ts
  .storybook/stories/checkbox-toggle/checkbox-toggle-container.stories.ts
  .storybook/stories/checkbox-toggle/checkbox-toggle.stories.ts
  tests/snapshots/chromium/checkbox-or-toggle/checkbox-or-toggle--checkbox-or-toggle-core-dark.png
  tests/snapshots/chromium/checkbox-or-toggle/checkbox-or-toggle--checkbox-or-toggle-core-light.png
  tests/snapshots/chromium/checkbox-or-toggle/checkbox-or-toggle--showcase-checkbox-core-dark.png
  tests/snapshots/chromium/checkbox-or-toggle/checkbox-or-toggle--showcase-checkbox-core-light.png
  tests/snapshots/chromium/checkbox-or-toggle/checkbox-or-toggle--showcase-toggle-switch-core-dark.png
  tests/snapshots/chromium/checkbox-or-toggle/checkbox-or-toggle--showcase-toggle-switch-core-light.png
  tests/snapshots/chromium/checkbox-or-toggle/checkbox-or-toggle--variants-core-dark.png
  tests/snapshots/chromium/checkbox-or-toggle/checkbox-or-toggle--variants-core-light.png
  tests/snapshots/chromium/checkbox-or-toggle/checkbox-or-toggle-container--checkbox-or-toggle-container-core-dark.png
  tests/snapshots/chromium/checkbox-or-toggle/checkbox-or-toggle-container--checkbox-or-toggle-container-core-light.png
  tests/snapshots/chromium/checkbox-or-toggle/checkbox-or-toggle-container--showcase-checkbox-container-core-dark.png
  tests/snapshots/chromium/checkbox-or-toggle/checkbox-or-toggle-container--showcase-checkbox-container-core-light.png
  tests/snapshots/chromium/checkbox-or-toggle/checkbox-or-toggle-container--showcase-toggle-container-core-dark.png
  tests/snapshots/chromium/checkbox-or-toggle/checkbox-or-toggle-container--showcase-toggle-container-core-light.png
  tests/snapshots/chromium/checkbox-or-toggle/checkbox-or-toggle-container--variants-core-dark.png
  tests/snapshots/chromium/checkbox-or-toggle/checkbox-or-toggle-container--variants-core-light.png
  tests/snapshots/firefox/checkbox-or-toggle/checkbox-or-toggle--checkbox-or-toggle-core-dark.png
  tests/snapshots/firefox/checkbox-or-toggle/checkbox-or-toggle--checkbox-or-toggle-core-light.png
  tests/snapshots/firefox/checkbox-or-toggle/checkbox-or-toggle--showcase-checkbox-core-dark.png
  tests/snapshots/firefox/checkbox-or-toggle/checkbox-or-toggle--showcase-checkbox-core-light.png
  tests/snapshots/firefox/checkbox-or-toggle/checkbox-or-toggle--showcase-toggle-switch-core-dark.png
  tests/snapshots/firefox/checkbox-or-toggle/checkbox-or-toggle--showcase-toggle-switch-core-light.png
  tests/snapshots/firefox/checkbox-or-toggle/checkbox-or-toggle--variants-core-dark.png
  tests/snapshots/firefox/checkbox-or-toggle/checkbox-or-toggle--variants-core-light.png
  tests/snapshots/firefox/checkbox-or-toggle/checkbox-or-toggle-container--checkbox-or-toggle-container-core-dark.png
  tests/snapshots/firefox/checkbox-or-toggle/checkbox-or-toggle-container--checkbox-or-toggle-container-core-light.png
  tests/snapshots/firefox/checkbox-or-toggle/checkbox-or-toggle-container--showcase-checkbox-container-core-dark.png
  tests/snapshots/firefox/checkbox-or-toggle/checkbox-or-toggle-container--showcase-checkbox-container-core-light.png
  tests/snapshots/firefox/checkbox-or-toggle/checkbox-or-toggle-container--showcase-toggle-container-core-dark.png
  tests/snapshots/firefox/checkbox-or-toggle/checkbox-or-toggle-container--showcase-toggle-container-core-light.png
  tests/snapshots/firefox/checkbox-or-toggle/checkbox-or-toggle-container--variants-core-dark.png
  tests/snapshots/firefox/checkbox-or-toggle/checkbox-or-toggle-container--variants-core-light.png
Labels: cla-not-required

#1271 chore(progress bar): update stories for progress bar
  .storybook/stories/progress-bar/progress-bar.stories.ts
  tests/snapshots/chromium/progress-bar/progress-bar--progress-bar-core-dark.png
  tests/snapshots/chromium/progress-bar/progress-bar--progress-bar-core-light.png
  tests/snapshots/chromium/progress-bar/progress-bar--showcase-core-dark.png
  tests/snapshots/chromium/progress-bar/progress-bar--showcase-core-light.png
  tests/snapshots/chromium/progress-bar/progress-bar--variants-core-dark.png
  tests/snapshots/chromium/progress-bar/progress-bar--variants-core-light.png
  tests/snapshots/firefox/progress-bar/progress-bar--progress-bar-core-dark.png
  tests/snapshots/firefox/progress-bar/progress-bar--progress-bar-core-light.png
  tests/snapshots/firefox/progress-bar/progress-bar--showcase-core-dark.png
  tests/snapshots/firefox/progress-bar/progress-bar--showcase-core-light.png
  tests/snapshots/firefox/progress-bar/progress-bar--variants-core-dark.png
  tests/snapshots/firefox/progress-bar/progress-bar--variants-core-light.png
Labels: cla-not-required

#1272 chore(login): update stories for login
  .storybook/stories/login/login.stories.ts
  tests/snapshots/chromium/login/login--login-core-dark.png
  tests/snapshots/chromium/login/login--login-core-light.png
  tests/snapshots/firefox/login/login--login-core-dark.png
  tests/snapshots/firefox/login/login--login-core-light.png
Labels: cla-not-required

#1274 chore(radio): update stories for radio
  .storybook/stories/radio/radio-container.stories.ts
  .storybook/stories/radio/radio.stories.ts
  tests/snapshots/chromium/radio/radio--checked-core-dark.png
  tests/snapshots/chromium/radio/radio--checked-core-light.png
  tests/snapshots/chromium/radio/radio--disabled-core-dark.png
  tests/snapshots/chromium/radio/radio--disabled-core-light.png
  tests/snapshots/chromium/radio/radio--disabledd-and-checked-core-dark.png
  tests/snapshots/chromium/radio/radio--disabledd-and-checked-core-light.png
  tests/snapshots/chromium/radio/radio--radio-core-dark.png
  tests/snapshots/chromium/radio/radio--radio-core-light.png
  tests/snapshots/chromium/radio/radio--variants-core-dark.png
  tests/snapshots/chromium/radio/radio--variants-core-light.png
  tests/snapshots/chromium/radio/radio-container--inline-core-dark.png
  tests/snapshots/chromium/radio/radio-container--inline-core-light.png
  tests/snapshots/chromium/radio/radio-container--radio-container-core-dark.png
  tests/snapshots/chromium/radio/radio-container--radio-container-core-light.png
  tests/snapshots/chromium/radio/radio-container--variants-core-dark.png
  tests/snapshots/chromium/radio/radio-container--variants-core-light.png
  tests/snapshots/firefox/radio/radio--checked-core-dark.png
  tests/snapshots/firefox/radio/radio--checked-core-light.png
  tests/snapshots/firefox/radio/radio--disabled-core-dark.png
  tests/snapshots/firefox/radio/radio--disabled-core-light.png
  tests/snapshots/firefox/radio/radio--disabledd-and-checked-core-dark.png
  tests/snapshots/firefox/radio/radio--disabledd-and-checked-core-light.png
  tests/snapshots/firefox/radio/radio--radio-core-dark.png
  tests/snapshots/firefox/radio/radio--radio-core-light.png
  tests/snapshots/firefox/radio/radio--variants-core-dark.png
  tests/snapshots/firefox/radio/radio--variants-core-light.png
  tests/snapshots/firefox/radio/radio-container--inline-core-dark.png
  tests/snapshots/firefox/radio/radio-container--inline-core-light.png
  tests/snapshots/firefox/radio/radio-container--radio-container-core-dark.png
  tests/snapshots/firefox/radio/radio-container--radio-container-core-light.png
  tests/snapshots/firefox/radio/radio-container--variants-core-dark.png
  tests/snapshots/firefox/radio/radio-container--variants-core-light.png
Labels: cla-not-required

#1248 chore: remove "delete stale visual snapshot branches" workflows
  .github/workflows/delete-stale-branches-preview.yml
  .github/workflows/delete-stale-branches.yml
Labels: cla-not-required, type:chore

#1273 chore(header): update stories for header
  .storybook/stories/header/header-collapsed.stories.ts
  .storybook/stories/header/header-colors.stories.ts
  .storybook/stories/header/header-static.stories.ts
  .storybook/stories/header/header.stories.ts
  tests/screenshot-options.ts
  tests/snapshots/chromium/header/header--header-core-dark.png
  tests/snapshots/chromium/header/header--header-core-light.png
  tests/snapshots/chromium/header/header-colors--header-colors-core-dark.png
  tests/snapshots/chromium/header/header-colors--header-colors-core-light.png
  tests/snapshots/chromium/header/header-colors--showcase-core-dark.png
  tests/snapshots/chromium/header/header-colors--showcase-core-light.png
  tests/snapshots/chromium/header/header-colors--variants-core-dark.png
  tests/snapshots/chromium/header/header-colors--variants-core-light.png
  tests/snapshots/chromium/header/headers-collapsed--header-collapsed-core-dark.png
  tests/snapshots/chromium/header/headers-collapsed--header-collapsed-core-light.png
  tests/snapshots/chromium/header/headers-static--header-static-core-dark.png
  tests/snapshots/chromium/header/headers-static--header-static-core-light.png
  tests/snapshots/firefox/header/header--header-core-dark.png
  tests/snapshots/firefox/header/header--header-core-light.png
  tests/snapshots/firefox/header/header-colors--header-colors-core-dark.png
  tests/snapshots/firefox/header/header-colors--header-colors-core-light.png
  tests/snapshots/firefox/header/header-colors--showcase-core-dark.png
  tests/snapshots/firefox/header/header-colors--showcase-core-light.png
  tests/snapshots/firefox/header/header-colors--variants-core-dark.png
  tests/snapshots/firefox/header/header-colors--variants-core-light.png
  tests/snapshots/firefox/header/headers-collapsed--header-collapsed-core-dark.png
  tests/snapshots/firefox/header/headers-collapsed--header-collapsed-core-light.png
  tests/snapshots/firefox/header/headers-static--header-static-core-dark.png
  tests/snapshots/firefox/header/headers-static--header-static-core-light.png
Labels: cla-not-required

#1288 fix(datagrid): set expandable rows overflow hidden only during animation
  .storybook/stories/datagrid/datagrid-expandable-row.stories.ts
  projects/angular/clarity.api.md
  projects/angular/src/utils/animations/expandable-animation/expandable-animation.ts
Labels: cla-not-required, type:fix, auto-backport-to-15.x, auto-backport-to-16.x

#1293 chore(datagrid): add expanded row visual tests
  .storybook/stories/datagrid/datagrid-expandable-row.stories.ts
  tests/snapshots/chromium/datagrid/expandable-rows--variants-core-dark.png
  tests/snapshots/chromium/datagrid/expandable-rows--variants-core-light.png
  tests/snapshots/firefox/datagrid/expandable-rows--variants-core-dark.png
  tests/snapshots/firefox/datagrid/expandable-rows--variants-core-light.png
Labels: cla-not-required, type:chore, auto-backport-to-15.x, auto-backport-to-16.x

#1281 chore(timeline): update stories to CSFv3
  .storybook/stories/timeline/timeline-step.stories.ts
  .storybook/stories/timeline/timeline.stories.ts
  tests/snapshots/chromium/timeline/timeline--horizontal-layout-core-dark.png
  tests/snapshots/chromium/timeline/timeline--horizontal-layout-core-light.png
  tests/snapshots/chromium/timeline/timeline--variants-core-dark.png
  tests/snapshots/chromium/timeline/timeline--variants-core-light.png
  tests/snapshots/chromium/timeline/timeline--vertical-layout-core-dark.png
  tests/snapshots/chromium/timeline/timeline--vertical-layout-core-light.png
  tests/snapshots/chromium/timeline/timeline-step--timeline-step-core-dark.png
  tests/snapshots/chromium/timeline/timeline-step--timeline-step-core-light.png
  tests/snapshots/chromium/timeline/timeline-step--timeline-step-states-core-dark.png
  tests/snapshots/chromium/timeline/timeline-step--timeline-step-states-core-light.png
  tests/snapshots/chromium/timeline/timeline-step--variants-core-dark.png
  tests/snapshots/chromium/timeline/timeline-step--variants-core-light.png
  tests/snapshots/firefox/timeline/timeline--horizontal-layout-core-dark.png
  tests/snapshots/firefox/timeline/timeline--horizontal-layout-core-light.png
  tests/snapshots/firefox/timeline/timeline--variants-core-dark.png
  tests/snapshots/firefox/timeline/timeline--variants-core-light.png
  tests/snapshots/firefox/timeline/timeline--vertical-layout-core-dark.png
  tests/snapshots/firefox/timeline/timeline--vertical-layout-core-light.png
  tests/snapshots/firefox/timeline/timeline-step--timeline-step-core-dark.png
  tests/snapshots/firefox/timeline/timeline-step--timeline-step-core-light.png
  tests/snapshots/firefox/timeline/timeline-step--timeline-step-states-core-dark.png
  tests/snapshots/firefox/timeline/timeline-step--timeline-step-states-core-light.png
  tests/snapshots/firefox/timeline/timeline-step--variants-core-dark.png
  tests/snapshots/firefox/timeline/timeline-step--variants-core-light.png
Labels: cla-not-required

#1286 chore(modal): update stories to CSFv3
  .storybook/stories/modal/modal-static.stories.ts
  .storybook/stories/modal/modal.stories.ts
  .storybook/stories/modal/nested-datagrid-detail.stories.ts
  .storybook/stories/modal/nested-popover.stories.ts
  .storybook/stories/modal/stacked-modal.stories.ts
  tests/snapshots/chromium/modal/modal--modal-core-dark.png
  tests/snapshots/chromium/modal/modal--modal-core-light.png
  tests/snapshots/chromium/modal/nested-datagrid-detail--nested-datagrid-detail-core-dark.png
  tests/snapshots/chromium/modal/nested-datagrid-detail--nested-datagrid-detail-core-light.png
  tests/snapshots/chromium/modal/nested-popover--nested-popover-core-dark.png
  tests/snapshots/chromium/modal/nested-popover--nested-popover-core-light.png
  tests/snapshots/chromium/modal/stacked-modal--stacked-modal-core-dark.png
  tests/snapshots/chromium/modal/stacked-modal--stacked-modal-core-light.png
  tests/snapshots/chromium/modal/static--extra-large-modal-core-dark.png
  tests/snapshots/chromium/modal/static--extra-large-modal-core-light.png
  tests/snapshots/chromium/modal/static--large-modal-core-dark.png
  tests/snapshots/chromium/modal/static--large-modal-core-light.png
  tests/snapshots/chromium/modal/static--medium-modal-core-dark.png
  tests/snapshots/chromium/modal/static--medium-modal-core-light.png
  tests/snapshots/chromium/modal/static--small-modal-core-dark.png
  tests/snapshots/chromium/modal/static--small-modal-core-light.png
  tests/snapshots/chromium/modal/static--variants-core-dark.png
  tests/snapshots/chromium/modal/static--variants-core-light.png
  tests/snapshots/firefox/modal/modal--modal-core-dark.png
  tests/snapshots/firefox/modal/modal--modal-core-light.png
  tests/snapshots/firefox/modal/nested-datagrid-detail--nested-datagrid-detail-core-dark.png
  tests/snapshots/firefox/modal/nested-datagrid-detail--nested-datagrid-detail-core-light.png
  tests/snapshots/firefox/modal/nested-popover--nested-popover-core-dark.png
  tests/snapshots/firefox/modal/nested-popover--nested-popover-core-light.png
  tests/snapshots/firefox/modal/stacked-modal--stacked-modal-core-dark.png
  tests/snapshots/firefox/modal/stacked-modal--stacked-modal-core-light.png
  tests/snapshots/firefox/modal/static--extra-large-modal-core-dark.png
  tests/snapshots/firefox/modal/static--extra-large-modal-core-light.png
  tests/snapshots/firefox/modal/static--large-modal-core-dark.png
  tests/snapshots/firefox/modal/static--large-modal-core-light.png
  tests/snapshots/firefox/modal/static--medium-modal-core-dark.png
  tests/snapshots/firefox/modal/static--medium-modal-core-light.png
  tests/snapshots/firefox/modal/static--small-modal-core-dark.png
  tests/snapshots/firefox/modal/static--small-modal-core-light.png
  tests/snapshots/firefox/modal/static--variants-core-dark.png
  tests/snapshots/firefox/modal/static--variants-core-light.png
Labels: cla-not-required
