Repository vmware-clarity/ng-clarity, pull requests merged in 2024-10, with the labels that each got.

#1574 fix(wizard): update left border color of currently active step
  projects/angular/src/wizard/STYLES.md
  projects/angular/src/wizard/_properties.wizard.scss
  projects/angular/src/wizard/_variables.wizard.scss
  projects/angular/src/wizard/_wizard.clarity.scss
  tests/snapshots/chromium/wizard/wizard--full-screen-wizard-core-dark.png
  tests/snapshots/chromium/wizard/wizard--full-screen-wizard-core-light.png
  tests/snapshots/chromium/wizard/wizard--wizard-core-dark.png
  tests/snapshots/chromium/wizard/wizard--wizard-core-light.png
  tests/snapshots/chromium/wizard/wizard-long-titles--wizard-long-titles-core-dark.png
  tests/snapshots/chromium/wizard/wizard-long-titles--wizard-long-titles-core-light.png
  tests/snapshots/chromium/wizard/wizard-page--wizard-page-core-dark.png
  tests/snapshots/chromium/wizard/wizard-page--wizard-page-core-light.png
  tests/snapshots/chromium/wizard/wizard-page--wizard-page-status-indicators-core-dark.png
  tests/snapshots/chromium/wizard/wizard-page--wizard-page-status-indicators-core-light.png
  tests/snapshots/firefox/wizard/wizard--full-screen-wizard-core-dark.png
  tests/snapshots/firefox/wizard/wizard--full-screen-wizard-core-light.png
  tests/snapshots/firefox/wizard/wizard--wizard-core-dark.png
  tests/snapshots/firefox/wizard/wizard--wizard-core-light.png
  tests/snapshots/firefox/wizard/wizard-long-titles--wizard-long-titles-core-dark.png
  tests/snapshots/firefox/wizard/wizard-long-titles--wizard-long-titles-core-light.png
  tests/snapshots/firefox/wizard/wizard-page--wizard-page-core-dark.png
  tests/snapshots/firefox/wizard/wizard-page--wizard-page-core-light.png
  tests/snapshots/firefox/wizard/wizard-page--wizard-page-status-indicators-core-dark.png
  tests/snapshots/firefox/wizard/wizard-page--wizard-page-status-indicators-core-light.png
Labels: cla-not-required, type:fix

#1577 fix(datagrid): remove setTimeout and check visibility for calculations
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/render/main-renderer.ts
  tests/snapshots/chromium/datagrid/expandable-rows--expandable-rows-core-dark.png
  tests/snapshots/chromium/datagrid/expandable-rows--expandable-rows-core-light.png
Labels: type:fix

#1564 fix(stepper): remove delay in focus to next step
  projects/angular/src/accordion/stepper/stepper-panel.spec.ts
  projects/angular/src/accordion/stepper/stepper-panel.ts
Labels: auto-backport-to-16.x

#1558 fix(wizard): improve screen reader text for stepnav items
  projects/angular/clarity.api.md
  projects/angular/src/utils/i18n/common-strings.default.ts
  projects/angular/src/utils/i18n/common-strings.interface.ts
  projects/angular/src/wizard/wizard-stepnav-item.spec.ts
  projects/angular/src/wizard/wizard-stepnav-item.ts
Labels: cla-not-required, type:fix, a11y, auto-backport-to-16.x

#1581 fix(datagrid): remove expand cell from calculations
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
Labels: auto-backport-to-16.x

#1555 fix(tokens): add new global blue 25 and update alias colors
  projects/ui/src/temp-overrides.scss
  tests/snapshots/chromium/badge/badge--initial-core-light.png
  tests/snapshots/chromium/label/label--label-core-light.png
  tests/snapshots/chromium/label/label--showcase-core-light.png
  tests/snapshots/firefox/badge/badge--initial-core-light.png
  tests/snapshots/firefox/label/label--label-core-light.png
  tests/snapshots/firefox/label/label--showcase-core-light.png
Labels: cla-not-required

#1586 fix(badge): correct orange text color
  projects/angular/src/emphasis/_properties.badges.scss
  tests/snapshots/chromium/label/label--showcase-core-dark.png
  tests/snapshots/firefox/label/label--showcase-core-dark.png
Labels: type:fix

#1589 feat(stepper): update buttons
  .storybook/stories/stepper/stepper.stories.ts
  projects/angular/clarity.api.md
  projects/angular/src/accordion/stepper/_stepper.clarity.scss
  projects/angular/src/accordion/stepper/models/stepper.model.spec.ts
  projects/angular/src/accordion/stepper/models/stepper.model.ts
  projects/angular/src/accordion/stepper/providers/stepper.service.spec.ts
  projects/angular/src/accordion/stepper/providers/stepper.service.ts
  projects/angular/src/accordion/stepper/step-button.spec.ts
  projects/angular/src/accordion/stepper/step-button.ts
  projects/demo/src/app/stepper/stepper.demo.html
  tests/snapshots/chromium/stepper/stepper--stepper-with-previous-button-core-dark.png
  tests/snapshots/chromium/stepper/stepper--stepper-with-previous-button-core-light.png
  tests/snapshots/firefox/stepper/stepper--stepper-with-previous-button-core-dark.png
  tests/snapshots/firefox/stepper/stepper--stepper-with-previous-button-core-light.png
Labels: type:feat

#1584 fix(datagrid): hide separator from last column dynamically
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-column.ts
  projects/angular/src/data/datagrid/render/main-renderer.ts
Labels: auto-backport-to-16.x

#1592 chore(demo): make vertical nav collapsable
  projects/demo/src/app/content-container.component.ts
Labels: type:chore

#1583 feat(stepper): separate header panel from accordion, update icons and number positions
  projects/angular/clarity.api.md
  projects/angular/src/accordion/_accordion.clarity.scss
  projects/angular/src/accordion/accordion-panel.html
  projects/angular/src/accordion/accordion-panel.ts
  projects/angular/src/accordion/stepper/_stepper.clarity.scss
  projects/angular/src/accordion/stepper/stepper-panel.html
  projects/angular/src/accordion/stepper/stepper-panel.ts
  tests/snapshots/chromium/stepper/stepper--stepper-alignment-test-core-dark.png
  tests/snapshots/chromium/stepper/stepper--stepper-alignment-test-core-light.png
  tests/snapshots/chromium/stepper/stepper--stepper-core-dark.png
  tests/snapshots/chromium/stepper/stepper--stepper-core-light.png
  tests/snapshots/chromium/stepper/stepper--stepper-panel-status-indicators-core-dark.png
  tests/snapshots/chromium/stepper/stepper--stepper-panel-status-indicators-core-light.png
  tests/snapshots/chromium/stepper/stepper--stepper-with-previous-button-core-dark.png
  tests/snapshots/chromium/stepper/stepper--stepper-with-previous-button-core-light.png
  tests/snapshots/firefox/stepper/stepper--stepper-alignment-test-core-dark.png
  tests/snapshots/firefox/stepper/stepper--stepper-alignment-test-core-light.png
  tests/snapshots/firefox/stepper/stepper--stepper-core-dark.png
  tests/snapshots/firefox/stepper/stepper--stepper-core-light.png
  tests/snapshots/firefox/stepper/stepper--stepper-panel-status-indicators-core-dark.png
  tests/snapshots/firefox/stepper/stepper--stepper-panel-status-indicators-core-light.png
  tests/snapshots/firefox/stepper/stepper--stepper-with-previous-button-core-dark.png
  tests/snapshots/firefox/stepper/stepper--stepper-with-previous-button-core-light.png
Labels: cla-not-required, type:feat

#1596 fix(alerts): update dark theme colors
  projects/angular/src/emphasis/alert/_properties.alert.scss
  projects/ui/src/temp-overrides.scss
  tests/snapshots/chromium/alert/standard-alerts--alert-core-dark.png
  tests/snapshots/chromium/alert/standard-alerts--closable-core-dark.png
  tests/snapshots/chromium/alert/standard-alerts--different-icon-core-dark.png
  tests/snapshots/chromium/alert/standard-alerts--small-core-dark.png
  tests/snapshots/chromium/alert/standard-alerts--with-actions-core-dark.png
  tests/snapshots/chromium/login/login--login-core-dark.png
  tests/snapshots/firefox/alert/standard-alerts--alert-core-dark.png
  tests/snapshots/firefox/alert/standard-alerts--closable-core-dark.png
  tests/snapshots/firefox/alert/standard-alerts--different-icon-core-dark.png
  tests/snapshots/firefox/alert/standard-alerts--small-core-dark.png
  tests/snapshots/firefox/alert/standard-alerts--with-actions-core-dark.png
  tests/snapshots/firefox/login/login--login-core-dark.png
Labels: type:fix

#1601 feat(token): add viz alias for severity warning light
  projects/ui/src/temp-overrides.scss
Labels: cla-not-required

#1603 fix(tokens): update alias overrides and remove unused
  projects/angular/src/layout/nav/_properties.responsive-nav.scss
  projects/angular/src/layout/nav/_variables.responsive-nav.scss
  projects/angular/src/layout/vertical-nav/_properties.vertical-nav.scss
  projects/ui/src/temp-overrides.scss
Labels: cla-not-required, type:fix
