Repository vmware-clarity/ng-clarity, pull requests merged in 2024-03, with the labels that each got.

#1283 chore(tree): update stories to CSFv3
  .storybook/helpers/files.data.ts
  .storybook/stories/tree/tree-node.stories.ts
  .storybook/stories/tree/tree-with-lazy-loaded-nodes.stories.ts
  .storybook/stories/tree/tree-with-lazy-loaded-recursive-nodes.stories.ts
  .storybook/stories/tree/tree-with-recursive-nodes.stories.ts
  .storybook/stories/tree/tree.stories.ts
  tests/snapshots/chromium/tree/tree--tree-view-core-dark.png
  tests/snapshots/chromium/tree/tree--tree-view-core-light.png
  tests/snapshots/chromium/tree/tree-node--tree-node-core-dark.png
  tests/snapshots/chromium/tree/tree-node--tree-node-core-light.png
  tests/snapshots/chromium/tree/tree-node--tree-node-showcase-core-dark.png
  tests/snapshots/chromium/tree/tree-node--tree-node-showcase-core-light.png
  tests/snapshots/chromium/tree/tree-node--variants-core-dark.png
  tests/snapshots/chromium/tree/tree-node--variants-core-light.png
  tests/snapshots/chromium/tree/tree-with-lazy-loaded-nodes--lazy-loaded-nodes-core-dark.png
  tests/snapshots/chromium/tree/tree-with-lazy-loaded-nodes--lazy-loaded-nodes-core-light.png
  tests/snapshots/chromium/tree/tree-with-lazy-loaded-recursive-nodes--lazy-loaded-recursive-nodes-core-dark.png
  tests/snapshots/chromium/tree/tree-with-lazy-loaded-recursive-nodes--lazy-loaded-recursive-nodes-core-light.png
  tests/snapshots/chromium/tree/tree-with-recursive-nodes--recursive-nodes-core-dark.png
  tests/snapshots/chromium/tree/tree-with-recursive-nodes--recursive-nodes-core-light.png
  tests/snapshots/firefox/tree/tree--tree-view-core-dark.png
  tests/snapshots/firefox/tree/tree--tree-view-core-light.png
  tests/snapshots/firefox/tree/tree-node--tree-node-core-dark.png
  tests/snapshots/firefox/tree/tree-node--tree-node-core-light.png
  tests/snapshots/firefox/tree/tree-node--tree-node-showcase-core-dark.png
  tests/snapshots/firefox/tree/tree-node--tree-node-showcase-core-light.png
  tests/snapshots/firefox/tree/tree-node--variants-core-dark.png
  tests/snapshots/firefox/tree/tree-node--variants-core-light.png
  tests/snapshots/firefox/tree/tree-with-lazy-loaded-nodes--lazy-loaded-nodes-core-dark.png
  tests/snapshots/firefox/tree/tree-with-lazy-loaded-nodes--lazy-loaded-nodes-core-light.png
  tests/snapshots/firefox/tree/tree-with-lazy-loaded-recursive-nodes--lazy-loaded-recursive-nodes-core-dark.png
  tests/snapshots/firefox/tree/tree-with-lazy-loaded-recursive-nodes--lazy-loaded-recursive-nodes-core-light.png
  tests/snapshots/firefox/tree/tree-with-recursive-nodes--recursive-nodes-core-dark.png
  tests/snapshots/firefox/tree/tree-with-recursive-nodes--recursive-nodes-core-light.png
Labels: cla-not-required

#1285 chore(tabs): update stories to CSFv3
  .storybook/stories/tabs/tabs-collapsed.stories.ts
  .storybook/stories/tabs/tabs.stories.ts
  tests/snapshots/chromium/tabs/tabs--tabs-core-dark.png
  tests/snapshots/chromium/tabs/tabs--tabs-core-light.png
  tests/snapshots/chromium/tabs/tabs--tabs-responsive-core-dark.png
  tests/snapshots/chromium/tabs/tabs--tabs-responsive-core-light.png
  tests/snapshots/chromium/tabs/tabs--variants-core-dark.png
  tests/snapshots/chromium/tabs/tabs--variants-core-light.png
  tests/snapshots/chromium/tabs/tabs--vertical-tabs-core-dark.png
  tests/snapshots/chromium/tabs/tabs--vertical-tabs-core-light.png
  tests/snapshots/chromium/tabs/tabs-reactive--variants-core-dark.png
  tests/snapshots/chromium/tabs/tabs-reactive--variants-core-light.png
  tests/snapshots/firefox/tabs/tabs--tabs-core-dark.png
  tests/snapshots/firefox/tabs/tabs--tabs-core-light.png
  tests/snapshots/firefox/tabs/tabs--tabs-responsive-core-dark.png
  tests/snapshots/firefox/tabs/tabs--tabs-responsive-core-light.png
  tests/snapshots/firefox/tabs/tabs--variants-core-dark.png
  tests/snapshots/firefox/tabs/tabs--variants-core-light.png
  tests/snapshots/firefox/tabs/tabs--vertical-tabs-core-dark.png
  tests/snapshots/firefox/tabs/tabs--vertical-tabs-core-light.png
  tests/snapshots/firefox/tabs/tabs-reactive--variants-core-dark.png
  tests/snapshots/firefox/tabs/tabs-reactive--variants-core-light.png
Labels: cla-not-required

#1282 chore(range): update stories to CSFv3
  .storybook/stories/range/range.stories.ts
  tests/snapshots/chromium/range/range-container--range-core-dark.png
  tests/snapshots/chromium/range/range-container--range-core-light.png
  tests/snapshots/chromium/range/range-container--showcase-range-core-dark.png
  tests/snapshots/chromium/range/range-container--showcase-range-core-light.png
  tests/snapshots/chromium/range/range-container--variants-core-dark.png
  tests/snapshots/chromium/range/range-container--variants-core-light.png
  tests/snapshots/firefox/range/range-container--range-core-dark.png
  tests/snapshots/firefox/range/range-container--range-core-light.png
  tests/snapshots/firefox/range/range-container--showcase-range-core-dark.png
  tests/snapshots/firefox/range/range-container--showcase-range-core-light.png
  tests/snapshots/firefox/range/range-container--variants-core-dark.png
  tests/snapshots/firefox/range/range-container--variants-core-light.png
Labels: cla-not-required

#1302 chore(wizard): update stories to CSFv3
  .storybook/stories/wizard/wizard-long-titles.stories.ts
  .storybook/stories/wizard/wizard-page.stories.ts
  .storybook/stories/wizard/wizard.stories.ts
  tests/snapshots/chromium/wizard/wizard--wizard-core-dark.png
  tests/snapshots/chromium/wizard/wizard--wizard-core-light.png
  tests/snapshots/chromium/wizard/wizard-long-titles--wizard-long-titles-core-dark.png
  tests/snapshots/chromium/wizard/wizard-long-titles--wizard-long-titles-core-light.png
  tests/snapshots/chromium/wizard/wizard-page--wizard-page-core-dark.png
  tests/snapshots/chromium/wizard/wizard-page--wizard-page-core-light.png
  tests/snapshots/firefox/wizard/wizard--wizard-core-dark.png
  tests/snapshots/firefox/wizard/wizard--wizard-core-light.png
  tests/snapshots/firefox/wizard/wizard-long-titles--wizard-long-titles-core-dark.png
  tests/snapshots/firefox/wizard/wizard-long-titles--wizard-long-titles-core-light.png
  tests/snapshots/firefox/wizard/wizard-page--wizard-page-core-dark.png
  tests/snapshots/firefox/wizard/wizard-page--wizard-page-core-light.png
Labels: cla-not-required

#1301 chore(stepper): update stories to CSFv3
  .storybook/stories/stepper/stepper.stories.ts
  tests/snapshots/chromium/stepper/stepper--stepper-core-dark.png
  tests/snapshots/chromium/stepper/stepper--stepper-core-light.png
  tests/snapshots/firefox/stepper/stepper--stepper-core-dark.png
  tests/snapshots/firefox/stepper/stepper--stepper-core-light.png
Labels: cla-not-required

#1304 chore(accordion): update storybook to include accordion description
  .storybook/stories/accordion/accordion-panel.stories.ts
  tests/snapshots/chromium/accordion/accordion-panel--panel-closed-core-dark.png
  tests/snapshots/chromium/accordion/accordion-panel--panel-closed-core-light.png
  tests/snapshots/chromium/accordion/accordion-panel--panel-closed-disabled-core-dark.png
  tests/snapshots/chromium/accordion/accordion-panel--panel-closed-disabled-core-light.png
  tests/snapshots/chromium/accordion/accordion-panel--panel-opened-core-dark.png
  tests/snapshots/chromium/accordion/accordion-panel--panel-opened-core-light.png
  tests/snapshots/chromium/accordion/accordion-panel--panel-opened-disabled-core-dark.png
  tests/snapshots/chromium/accordion/accordion-panel--panel-opened-disabled-core-light.png
  tests/snapshots/firefox/accordion/accordion-panel--panel-closed-core-dark.png
  tests/snapshots/firefox/accordion/accordion-panel--panel-closed-core-light.png
  tests/snapshots/firefox/accordion/accordion-panel--panel-closed-disabled-core-dark.png
  tests/snapshots/firefox/accordion/accordion-panel--panel-closed-disabled-core-light.png
  tests/snapshots/firefox/accordion/accordion-panel--panel-opened-core-dark.png
  tests/snapshots/firefox/accordion/accordion-panel--panel-opened-core-light.png
  tests/snapshots/firefox/accordion/accordion-panel--panel-opened-disabled-core-dark.png
  tests/snapshots/firefox/accordion/accordion-panel--panel-opened-disabled-core-light.png
Labels: cla-not-required

#1103 chore(alert): update stories for alerts
  .storybook/stories/alert/app-level-alert.stories.ts
  .storybook/stories/alert/standard-alert.stories.ts
  tests/snapshots/chromium/alert/app-level-alerts--alert-core-dark.png
  tests/snapshots/chromium/alert/app-level-alerts--alert-core-light.png
  tests/snapshots/chromium/alert/app-level-alerts--closable-core-dark.png
  tests/snapshots/chromium/alert/app-level-alerts--closable-core-light.png
  tests/snapshots/chromium/alert/app-level-alerts--different-icon-core-dark.png
  tests/snapshots/chromium/alert/app-level-alerts--different-icon-core-light.png
  tests/snapshots/chromium/alert/app-level-alerts--paginated-closable-core-dark.png
  tests/snapshots/chromium/alert/app-level-alerts--paginated-closable-core-light.png
  tests/snapshots/chromium/alert/app-level-alerts--paginated-core-dark.png
  tests/snapshots/chromium/alert/app-level-alerts--paginated-core-light.png
  tests/snapshots/chromium/alert/standard-alerts--alert-core-dark.png
  tests/snapshots/chromium/alert/standard-alerts--alert-core-light.png
  tests/snapshots/chromium/alert/standard-alerts--closable-core-dark.png
  tests/snapshots/chromium/alert/standard-alerts--closable-core-light.png
  tests/snapshots/chromium/alert/standard-alerts--different-icon-core-dark.png
  tests/snapshots/chromium/alert/standard-alerts--different-icon-core-light.png
  tests/snapshots/chromium/alert/standard-alerts--lightweight-core-dark.png
  tests/snapshots/chromium/alert/standard-alerts--lightweight-core-light.png
  tests/snapshots/chromium/alert/standard-alerts--small-core-dark.png
  tests/snapshots/chromium/alert/standard-alerts--small-core-light.png
  tests/snapshots/chromium/alert/standard-alerts--small-lightweight-core-dark.png
  tests/snapshots/chromium/alert/standard-alerts--small-lightweight-core-light.png
  tests/snapshots/firefox/alert/app-level-alerts--alert-core-dark.png
  tests/snapshots/firefox/alert/app-level-alerts--alert-core-light.png
  tests/snapshots/firefox/alert/app-level-alerts--closable-core-dark.png
  tests/snapshots/firefox/alert/app-level-alerts--closable-core-light.png
  tests/snapshots/firefox/alert/app-level-alerts--different-icon-core-dark.png
  tests/snapshots/firefox/alert/app-level-alerts--different-icon-core-light.png
  tests/snapshots/firefox/alert/app-level-alerts--paginated-closable-core-dark.png
  tests/snapshots/firefox/alert/app-level-alerts--paginated-closable-core-light.png
  tests/snapshots/firefox/alert/app-level-alerts--paginated-core-dark.png
  tests/snapshots/firefox/alert/app-level-alerts--paginated-core-light.png
  tests/snapshots/firefox/alert/standard-alerts--alert-core-dark.png
  tests/snapshots/firefox/alert/standard-alerts--alert-core-light.png
  tests/snapshots/firefox/alert/standard-alerts--closable-core-dark.png
  tests/snapshots/firefox/alert/standard-alerts--closable-core-light.png
  tests/snapshots/firefox/alert/standard-alerts--different-icon-core-dark.png
  tests/snapshots/firefox/alert/standard-alerts--different-icon-core-light.png
  tests/snapshots/firefox/alert/standard-alerts--lightweight-core-dark.png
  tests/snapshots/firefox/alert/standard-alerts--lightweight-core-light.png
  tests/snapshots/firefox/alert/standard-alerts--small-core-dark.png
  tests/snapshots/firefox/alert/standard-alerts--small-core-light.png
  tests/snapshots/firefox/alert/standard-alerts--small-lightweight-core-dark.png
  tests/snapshots/firefox/alert/standard-alerts--small-lightweight-core-light.png
Labels: cla-not-required

#1309 fix(tabs): fix aria-labelledby attribute
  projects/angular/clarity.api.md
  projects/angular/src/layout/tabs/tab-content.ts
  projects/angular/src/layout/tabs/tab-link.directive.ts
Labels: cla-not-required

#1310 fix(tabs): fix aria-labelledby attribute (#1309)
  projects/angular/clarity.api.md
  projects/angular/src/layout/tabs/tab-content.ts
  projects/angular/src/layout/tabs/tab-link.directive.ts
Labels: cla-not-required

#1311 fix(tabs): fix aria-labelledby attribute (#1309)
  projects/angular/clarity.api.md
  projects/angular/src/layout/tabs/tab-content.ts
  projects/angular/src/layout/tabs/tab-link.directive.ts
Labels: cla-not-required

#1312 feat: add support for Angular 17
  .github/workflows/pr-build.yml
  projects/angular/package.json
Labels: cla-not-required

#1314 fix(button-group): add missing divider
  .storybook/helpers/button-class.helper.ts
  .storybook/stories/button/button-group.stories.ts
  .storybook/stories/button/button.stories.ts
  projects/angular/src/button/button-group/_button-group.clarity.scss
  tests/snapshots/chromium/button/button-group--button-group-showcase-core-dark.png
  tests/snapshots/chromium/button/button-group--button-group-showcase-core-light.png
  tests/snapshots/firefox/button/button-group--button-group-showcase-core-dark.png
  tests/snapshots/firefox/button/button-group--button-group-showcase-core-light.png
Labels: cla-not-required

#1317 fix(button-group): use status color for overflow button
  projects/angular/src/button/_buttons.clarity.scss
  tests/snapshots/chromium/button/button-group--button-group-showcase-core-dark.png
  tests/snapshots/chromium/button/button-group--button-group-showcase-core-light.png
  tests/snapshots/firefox/button/button-group--button-group-showcase-core-dark.png
  tests/snapshots/firefox/button/button-group--button-group-showcase-core-light.png
Labels: cla-not-required

#1318 fix(a11y): combobox - aria-describedby error is not associated initially
  .storybook/stories/combobox/combobox.stories.ts
  projects/angular/src/forms/combobox/combobox.ts
  tests/snapshots/chromium/combobox/combobox--multi-selection-required-core-dark.png
  tests/snapshots/chromium/combobox/combobox--multi-selection-required-core-light.png
  tests/snapshots/chromium/combobox/combobox--single-selection-required-core-dark.png
  tests/snapshots/chromium/combobox/combobox--single-selection-required-core-light.png
  tests/snapshots/firefox/combobox/combobox--multi-selection-required-core-dark.png
  tests/snapshots/firefox/combobox/combobox--multi-selection-required-core-light.png
  tests/snapshots/firefox/combobox/combobox--single-selection-required-core-dark.png
  tests/snapshots/firefox/combobox/combobox--single-selection-required-core-light.png
Labels: cla-not-required

#1319 fix(a11y): combobox - aria-describedby error is not associated initially (backport to 16.x)
  .storybook/stories/combobox/combobox.stories.ts
  projects/angular/src/forms/combobox/combobox.ts
  tests/snapshots/chromium/combobox/combobox--variants-core-dark.png
  tests/snapshots/chromium/combobox/combobox--variants-core-light.png
  tests/snapshots/chromium/combobox/combobox--variants-ng-dark.png
  tests/snapshots/chromium/combobox/combobox--variants-ng-light.png
  tests/snapshots/firefox/combobox/combobox--variants-core-dark.png
  tests/snapshots/firefox/combobox/combobox--variants-core-light.png
  tests/snapshots/firefox/combobox/combobox--variants-ng-dark.png
  tests/snapshots/firefox/combobox/combobox--variants-ng-light.png
Labels: cla-not-required, auto-backport-to-15.x

#1320 fix(a11y): combobox - aria-describedby error is not associated initially (backport to 15.x)
  .storybook/stories/combobox/combobox.stories.ts
  projects/angular/src/forms/combobox/combobox.ts
  tests/snapshots/chromium/combobox/combobox--variants-core-dark.png
  tests/snapshots/chromium/combobox/combobox--variants-core-light.png
  tests/snapshots/chromium/combobox/combobox--variants-ng-dark.png
  tests/snapshots/chromium/combobox/combobox--variants-ng-light.png
  tests/snapshots/firefox/combobox/combobox--variants-core-dark.png
  tests/snapshots/firefox/combobox/combobox--variants-core-light.png
  tests/snapshots/firefox/combobox/combobox--variants-ng-dark.png
  tests/snapshots/firefox/combobox/combobox--variants-ng-light.png
Labels: cla-not-required

#1321 chore(datagrid): performance demo page
  projects/demo/src/app/datagrid/datagrid.demo.html
  projects/demo/src/app/datagrid/datagrid.demo.module.ts
  projects/demo/src/app/datagrid/datagrid.demo.routing.ts
  projects/demo/src/app/datagrid/inventory/dynamic-data.ts
  projects/demo/src/app/datagrid/performance/performance.html
  projects/demo/src/app/datagrid/performance/performance.ts
  projects/demo/src/main.ts
Labels: cla-not-required

#1323 chore(modal): add visual snapshots for open modal component
  .storybook/stories/modal/modal.stories.ts
  tests/screenshot-options.ts
  tests/snapshots/chromium/modal/modal--open-extra-large-modal-core-dark.png
  tests/snapshots/chromium/modal/modal--open-extra-large-modal-core-light.png
  tests/snapshots/chromium/modal/modal--open-large-modal-core-dark.png
  tests/snapshots/chromium/modal/modal--open-large-modal-core-light.png
  tests/snapshots/chromium/modal/modal--open-medium-modal-core-dark.png
  tests/snapshots/chromium/modal/modal--open-medium-modal-core-light.png
  tests/snapshots/chromium/modal/modal--open-small-modal-core-dark.png
  tests/snapshots/chromium/modal/modal--open-small-modal-core-light.png
  tests/snapshots/firefox/modal/modal--open-extra-large-modal-core-dark.png
  tests/snapshots/firefox/modal/modal--open-extra-large-modal-core-light.png
  tests/snapshots/firefox/modal/modal--open-large-modal-core-dark.png
  tests/snapshots/firefox/modal/modal--open-large-modal-core-light.png
  tests/snapshots/firefox/modal/modal--open-medium-modal-core-dark.png
  tests/snapshots/firefox/modal/modal--open-medium-modal-core-light.png
  tests/snapshots/firefox/modal/modal--open-small-modal-core-dark.png
  tests/snapshots/firefox/modal/modal--open-small-modal-core-light.png
Labels: cla-not-required

#1326 chore: direct support requests to Google Spaces
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/workflows/pr-comment-bot.yml
Labels: cla-not-required

#1322 fix(a11y): datepicker - screen reader is reading extra information on opening
  projects/angular/src/forms/datepicker/daypicker.ts
  projects/angular/src/forms/datepicker/monthpicker.ts
  projects/angular/src/forms/datepicker/yearpicker.ts
Labels: cla-not-required, auto-backport-to-15.x, auto-backport-to-16.x

#1333 chore: use relative file path import for story helpers
  .storybook/stories/button/button-group.stories.ts
  .storybook/stories/button/button.stories.ts
  .storybook/stories/button/buttons-loading.stories.ts
  .storybook/stories/combobox/combobox.stories.ts
  .storybook/stories/datagrid/modal-stacked-on-detail.stories.ts
  .storybook/stories/datagrid/nested-detail-in-detail.stories.ts
  .storybook/stories/datalist/datalist.stories.ts
  .storybook/stories/datepicker/date-container.stories.ts
  .storybook/stories/datepicker/datepicker.stories.ts
  .storybook/stories/dropdown/dropdown-item-that-opens-modal.stories.ts
  .storybook/stories/dropdown/dropdown-menu.stories.ts
  .storybook/stories/dropdown/dropdown-static.stories.ts
  .storybook/stories/dropdown/dropdown-tree.stories.ts
  .storybook/stories/dropdown/dropdown.stories.ts
  .storybook/stories/forms/forms-input-states.stories.ts
  .storybook/stories/forms/forms-reactive.stories.ts
  .storybook/stories/forms/forms-required-mark.stories.ts
  .storybook/stories/forms/forms-template-driven.stories.ts
  .storybook/stories/modal/nested-datagrid-detail.stories.ts
  .storybook/stories/modal/nested-popover.stories.ts
  .storybook/stories/modal/stacked-modal.stories.ts
  .storybook/stories/radio/radio-container.stories.ts
  .storybook/stories/radio/radio.stories.ts
  .storybook/stories/spinner/spinner.stories.ts
  .storybook/stories/stepper/stepper.stories.ts
Labels: cla-not-required

#1329 chore(alert): remove old non-CSFv3 alert stories
  .storybook/stories/alert/alert.stories.ts
  .storybook/stories/alert/alerts.stories.ts
  tests/snapshots/chromium/alert/alert--variants-core-dark.png
  tests/snapshots/chromium/alert/alert--variants-core-light.png
  tests/snapshots/chromium/alert/alerts--variants-core-dark.png
  tests/snapshots/chromium/alert/alerts--variants-core-light.png
  tests/snapshots/firefox/alert/alert--variants-core-dark.png
  tests/snapshots/firefox/alert/alert--variants-core-light.png
  tests/snapshots/firefox/alert/alerts--variants-core-dark.png
  tests/snapshots/firefox/alert/alerts--variants-core-light.png
Labels: cla-not-required

#1328 chore(storybook): use consistent code pattern for story variants
  .storybook/stories/accordion/accordion-panel.stories.ts
  .storybook/stories/accordion/accordion.stories.ts
  .storybook/stories/accordion/nested-accordion.stories.ts
  .storybook/stories/alert/app-level-alert.stories.ts
  .storybook/stories/alert/standard-alert.stories.ts
  .storybook/stories/signpost/signpost.stories.ts
Labels: cla-not-required

#1342 chore(storybook): remove dead `setupStorybook` function
  .storybook/helpers/setup-storybook.helpers.ts
Labels: cla-not-required

#1331 chore(modal): prevent error when story hot reloads
  .storybook/stories/modal/modal.stories.ts
Labels: cla-not-required

#1332 chore(wizard): remove title focus outline from screenshots
  .storybook/helpers/common.ts
  .storybook/stories/modal/modal.stories.ts
  .storybook/stories/wizard/wizard.stories.ts
  tests/snapshots/chromium/wizard/wizard--wizard-core-dark.png
  tests/snapshots/chromium/wizard/wizard--wizard-core-light.png
  tests/snapshots/firefox/wizard/wizard--wizard-core-dark.png
  tests/snapshots/firefox/wizard/wizard--wizard-core-light.png
Labels: cla-not-required
