Repository vmware-clarity/ng-clarity, pull requests merged in 2024-01, with the labels that each got.

#1105 chore(badge): update story to csfv3
  .storybook/stories/badge/badge.stories.ts
  tests/snapshots/badge/badge--initial-core-dark.png
  tests/snapshots/badge/badge--initial-core-light.png
  tests/snapshots/badge/badge--variants-core-dark.png
  tests/snapshots/badge/badge--variants-core-light.png
Labels: cla-not-required

#1104 chore(accordion): update storybook stories to csfv3 (port of #996)
  .storybook/stories/accordion/accordion-panel.stories.ts
  .storybook/stories/accordion/accordion.stories.ts
  .storybook/stories/accordion/nested-accordion.stories.ts
  tests/snapshots/accordion/accordion--initial-core-dark.png
  tests/snapshots/accordion/accordion--initial-core-light.png
  tests/snapshots/accordion/accordion--multiple-panels-opened-core-dark.png
  tests/snapshots/accordion/accordion--multiple-panels-opened-core-light.png
  tests/snapshots/accordion/accordion--single-panel-opened-core-dark.png
  tests/snapshots/accordion/accordion--single-panel-opened-core-light.png
  tests/snapshots/accordion/accordion--variants-core-dark.png
  tests/snapshots/accordion/accordion--variants-core-light.png
  tests/snapshots/accordion/accordion-panel--panel-closed-core-dark.png
  tests/snapshots/accordion/accordion-panel--panel-closed-core-light.png
  tests/snapshots/accordion/accordion-panel--panel-closed-disabled-core-dark.png
  tests/snapshots/accordion/accordion-panel--panel-closed-disabled-core-light.png
  tests/snapshots/accordion/accordion-panel--panel-opened-core-dark.png
  tests/snapshots/accordion/accordion-panel--panel-opened-core-light.png
  tests/snapshots/accordion/accordion-panel--panel-opened-disabled-core-dark.png
  tests/snapshots/accordion/accordion-panel--panel-opened-disabled-core-light.png
  tests/snapshots/accordion/accordion-panel--variants-core-dark.png
  tests/snapshots/accordion/accordion-panel--variants-core-light.png
  tests/snapshots/accordion/nested-accordion--closed-core-dark.png
  tests/snapshots/accordion/nested-accordion--closed-core-light.png
  tests/snapshots/accordion/nested-accordion--opened-core-dark.png
  tests/snapshots/accordion/nested-accordion--opened-core-light.png
  tests/snapshots/accordion/nested-accordion--variants-core-dark.png
  tests/snapshots/accordion/nested-accordion--variants-core-light.png
Labels: cla-not-required

#1119 fix(accordion): prevent error with nested accordions
  projects/angular/src/accordion/accordion.ts
Labels: cla-not-required

#1078 chore(spinner): extract common styling into mixins
  projects/angular/src/progress/spinner/_spinner.clarity.scss
Labels: cla-not-required

#1121 fix(accordion): prevent error with nested accordions
  projects/angular/src/accordion/accordion.ts
Labels: cla-not-required, type:fix

#1120 fix(accordion): prevent error with nested accordions
  projects/angular/src/accordion/accordion.ts
Labels: cla-not-required, type:fix, backport

#1125 chore(vertical-nav): negative margin content
  projects/angular/src/layout/vertical-nav/_vertical-nav.clarity.scss
Labels: cla-not-required

#1124 chore(forms): shim removal cleanup
  projects/angular/src/forms/styles/_properties.forms.scss
  projects/angular/src/forms/styles/_select.clarity.scss
  projects/angular/src/forms/styles/_variables.forms.scss
  tests/snapshots/login/login--variants-core-dark.png
  tests/snapshots/login/login--variants-core-light.png
  tests/snapshots/select/select--variants-core-dark.png
  tests/snapshots/select/select--variants-core-light.png
Labels: cla-not-required, type:chore

#1127 fix(links): change visited hover saas variable
  projects/angular/src/layout/nav/_links.clarity.scss
  projects/angular/src/utils/_reboot.clarity.scss
  projects/demo/src/app/typography/typography-links.html
Labels: cla-not-required, type:fix

#1128 chore(ci): delete stale visual snapshot branches workflow
  .github/workflows/delete-stale-branches-preview.yml
  .github/workflows/delete-stale-branches.yml
Labels: cla-not-required

#1129 chore: delete visual snapshot update branch immediately
  .github/workflows/pr-visual-snapshot-update-bot.yml
Labels: cla-not-required

#1134 chore: remove success and error loading buttons from visual test
  .storybook/stories/button/buttons-loading.stories.ts
  tests/snapshots/button/buttons-loading-states--variants-core-dark.png
  tests/snapshots/button/buttons-loading-states--variants-core-light.png
  tests/snapshots/button/buttons-loading-states--variants-ng-dark.png
  tests/snapshots/button/buttons-loading-states--variants-ng-light.png
Labels: cla-not-required

#1135 chore: report visual snapshot update bot status to pull request
  .github/workflows/pr-visual-snapshot-update-bot.yml
Labels: cla-not-required

#1139 fix(button group): fix border disappears in button group with disable
  .storybook/stories/button/button-group.stories.ts
  projects/angular/src/button/button-group/_button-group.clarity.scss
  tests/snapshots/button/button-group--variants-core-dark.png
  tests/snapshots/button/button-group--variants-core-light.png
  tests/snapshots/button/button-group--variants-ng-dark.png
  tests/snapshots/button/button-group--variants-ng-light.png
Labels: cla-not-required, type:fix

#1142 fix(button-group): handle keyboard focus for async menu buttons
  projects/angular/src/button/button-group/button-group.ts
  projects/demo/src/app/button-group/angular/basic-structure/basic-button-group.html
  projects/demo/src/app/button-group/angular/basic-structure/basic-button-group.ts
Labels: cla-not-required, type:fix, a11y

#1136 chore: remove success and error loading buttons from visual test (port to 17.x)
  .storybook/stories/button/buttons-loading.stories.ts
  tests/snapshots/button/buttons-loading-states--variants-core-dark.png
  tests/snapshots/button/buttons-loading-states--variants-core-light.png
Labels: cla-not-required, type:chore

#1137 chore: remove success and error loading buttons from visual test (port to 15.x)
  .storybook/stories/button/buttons-loading.stories.ts
  tests/snapshots/button/buttons-loading-states--variants-core-dark.png
  tests/snapshots/button/buttons-loading-states--variants-core-light.png
  tests/snapshots/button/buttons-loading-states--variants-ng-dark.png
  tests/snapshots/button/buttons-loading-states--variants-ng-light.png
Labels: cla-not-required, type:chore

#1138 fix(date-picker): trigger validation on min/max date change
  projects/angular/src/forms/datepicker/date-input.ts
  projects/demo/src/app/datepicker/datepicker-min-max.html
  projects/demo/src/app/datepicker/datepicker-min-max.ts
Labels: cla-not-required, type:fix

#1148 fix(button group): fix border disappears in button group with disable (port of 1139)
  .storybook/stories/button/button-group.stories.ts
  projects/angular/src/button/button-group/_button-group.clarity.scss
  tests/snapshots/button/button-group--variants-core-dark.png
  tests/snapshots/button/button-group--variants-core-light.png
Labels: cla-not-required, type:fix, next

#1147 fix(button group): fix border disappears in button group with disable (port of #1139)
  .storybook/stories/button/button-group.stories.ts
  projects/angular/src/button/button-group/_button-group.clarity.scss
  tests/snapshots/button/button-group--variants-core-dark.png
  tests/snapshots/button/button-group--variants-core-light.png
  tests/snapshots/button/button-group--variants-ng-dark.png
  tests/snapshots/button/button-group--variants-ng-light.png
Labels: cla-not-required, type:fix, v15

#1150 fix(date-picker): trigger validation on min/max date change (#1138)
  projects/angular/src/forms/datepicker/date-input.ts
  projects/demo/src/app/datepicker/datepicker-min-max.html
  projects/demo/src/app/datepicker/datepicker-min-max.ts
Labels: cla-not-required, type:fix

#1149 fix(date-picker): trigger validation on min/max date change (#1138)
  projects/angular/src/forms/datepicker/date-input.ts
  projects/demo/src/app/datepicker/datepicker-min-max.html
  projects/demo/src/app/datepicker/datepicker-min-max.ts
Labels: cla-not-required, type:fix

#1152 fix(signpost): prevent header from overlapping top of scrollbar
  projects/angular/src/popover/signpost/_properties.signpost.scss
  projects/angular/src/popover/signpost/_signposts.clarity.scss
  projects/ui/src/shim.cds-core.scss
Labels: cla-not-required, type:fix, v15

#1146 fix(button-group): handle keyboard focus for async menu buttons (port to 17.x)
  projects/angular/src/button/button-group/button-group.ts
  projects/demo/src/app/button-group/angular/basic-structure/basic-button-group.html
  projects/demo/src/app/button-group/angular/basic-structure/basic-button-group.ts
Labels: cla-not-required, type:fix, a11y

#1145 fix(button-group): handle keyboard focus for async menu buttons (port to 15.x)
  projects/angular/src/button/button-group/button-group.ts
  projects/demo/src/app/button-group/angular/basic-structure/basic-button-group.html
  projects/demo/src/app/button-group/angular/basic-structure/basic-button-group.ts
Labels: cla-not-required, type:fix, a11y

#1141 fix(button): skip animation on first render of loading button
  projects/angular/src/button/button-loading/loading-button.ts
Labels: cla-not-required, type:fix

#1155 fix(button): skip animation on first render of loading button (port to 17.x)
  projects/angular/src/button/button-loading/loading-button.ts
Labels: cla-not-required, type:fix

#1156 fix(alert): prevent error if alert is initially closed
  projects/angular/src/emphasis/alert/alert.ts
  projects/angular/src/emphasis/alert/alerts.spec.ts
Labels: cla-not-required, type:fix

#1144 feat(datagrid): use only `clrDgItemsTrackBy` for selection tracking
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/all.spec.ts
  projects/angular/src/data/datagrid/datagrid-items-trackby.spec.ts
  projects/angular/src/data/datagrid/datagrid-items-trackby.ts
  projects/angular/src/data/datagrid/datagrid-items.spec.ts
  projects/angular/src/data/datagrid/datagrid-items.ts
  projects/angular/src/data/datagrid/datagrid-row.spec.ts
  projects/angular/src/data/datagrid/datagrid.module.ts
  projects/angular/src/data/datagrid/datagrid.spec.ts
  projects/angular/src/data/datagrid/datagrid.ts
  projects/angular/src/data/datagrid/index.ts
  projects/angular/src/data/datagrid/providers/items.ts
  projects/angular/src/data/datagrid/providers/selection.spec.ts
  projects/angular/src/data/datagrid/providers/selection.ts
Labels: cla-not-required, type:breaking-change

#1153 fix(input): use "pointer" cursor for input action buttons
  projects/angular/src/forms/styles/_input-group.clarity.scss
Labels: cla-not-required, type:fix

#1117 chore(accordion): extract stepper component styles in separate file
  projects/angular/src/accordion/_accordion.clarity.scss
  projects/angular/src/accordion/stepper/_stepper.clarity.scss
  projects/angular/src/utils/_components.clarity.scss
Labels: cla-not-required

#1158 fix(alert): prevent error if alert is initially closed (port to 15.x)
  projects/angular/src/emphasis/alert/alert.ts
  projects/angular/src/emphasis/alert/alerts.spec.ts
Labels: cla-not-required, type:fix

#1159 fix(input): use "pointer" cursor for input action buttons (port to 15.x)
  projects/angular/src/forms/styles/_input-group.clarity.scss
Labels: cla-not-required, type:fix

#1157 fix(alert): prevent error if alert is initially closed (port to 17.x)
  projects/angular/src/emphasis/alert/alert.ts
  projects/angular/src/emphasis/alert/alerts.spec.ts
Labels: cla-not-required, type:fix

#1162 fix(forms): align labels inside horizontal forms #809
  projects/ui/src/shim.cds-core.scss
  tests/snapshots/forms/input-states--variants-core-dark.png
  tests/snapshots/forms/input-states--variants-core-light.png
  tests/snapshots/forms/reactive--variants-core-dark.png
  tests/snapshots/forms/reactive--variants-core-light.png
  tests/snapshots/forms/required-mark--variants-core-dark.png
  tests/snapshots/forms/required-mark--variants-core-light.png
  tests/snapshots/forms/template-driven--variants-core-dark.png
  tests/snapshots/forms/template-driven--variants-core-light.png
Labels: cla-not-required, type:fix, v15

#819 chore: add pr backport workflow
  .github/workflows/pr-backport.yml
Labels: cla-not-required, type:chore, flag:stale

#1163 feat(accordion): add title min-width
  projects/angular/src/accordion/_accordion.clarity.scss
  projects/angular/src/accordion/_properties.accordion.scss
  projects/angular/src/accordion/_variables.accordion.scss
  tests/snapshots/stepper/stepper--variants-core-dark.png
  tests/snapshots/stepper/stepper--variants-core-light.png
Labels: cla-not-required

#774 fix(datagrid): use correct layers, remove no-op z-indexes
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
Labels: cla-not-required, auto-backport-to-next

#1058 fix(date-picker): add null check for optional date control (port to 17.x)
  projects/angular/clarity.api.md
  projects/angular/src/forms/common/wrapped-control.ts
  projects/angular/src/forms/datepicker/date-input.spec.ts
Labels: cla-not-required, type:fix

#1165 fix(datagrid): use correct layers, remove no-op z-indexes (port to 17.x)
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
Labels: cla-not-required, type:fix

#1170 fix(card): resolve clickable card hover shifting text (#1166)
  projects/angular/src/layout/_card.clarity.scss
  projects/angular/src/layout/_properties.card.scss
Labels: cla-not-required, type:fix

#1169 fix(date-picker): ignore non-string values in date service parser
  projects/angular/src/forms/datepicker/providers/date-io.service.ts
Labels: cla-not-required, auto-backport-to-next, auto-backport-to-15.x

#1168 fix(accordion): header spacing and disabled panel content color
  projects/angular/src/accordion/STYLES.md
  projects/angular/src/accordion/_accordion.clarity.scss
  projects/angular/src/accordion/_properties.accordion.scss
  projects/angular/src/accordion/_variables.accordion.scss
  projects/angular/src/accordion/stepper/_stepper.clarity.scss
  tests/snapshots/accordion/accordion-panel--panel-opened-disabled-core-dark.png
  tests/snapshots/accordion/accordion-panel--panel-opened-disabled-core-light.png
  tests/snapshots/stepper/stepper--variants-core-dark.png
  tests/snapshots/stepper/stepper--variants-core-light.png
Labels: cla-not-required
