Repository vmware-clarity/ng-clarity, pull requests merged in 2025-01, with the labels that each got.

#1643 fix(datagrid): exclude row checkbox from error styling and validation
  projects/angular/src/data/datagrid/datagrid-row.html
  projects/angular/src/forms/styles/_checkbox.clarity.scss
Labels: cla-not-required

#937 fix(label): allow signposts inside labels
  projects/angular/clarity.api.md
  projects/angular/src/forms/common/label.spec.ts
  projects/angular/src/forms/common/label.ts
  projects/demo/src/app/forms/layout-angular/layout-angular.html
Labels: cla-not-required, type:fix, waiting:blocked, v16

#1660 chore(file-input): refactor validation to a single loop
  projects/angular/src/forms/file-input/file-input-validator.ts
Labels: cla-not-required

#1654 feat(storybook): add accordion nested components story
  .storybook/helpers/nesting-components.ts
  .storybook/stories/accordion/nested-components.stories.ts
  tests/snapshots/chromium/accordion/nested-components--nested-components-core-dark.png
  tests/snapshots/chromium/accordion/nested-components--nested-components-core-light.png
  tests/snapshots/firefox/accordion/nested-components--nested-components-core-dark.png
  tests/snapshots/firefox/accordion/nested-components--nested-components-core-light.png
Labels: cla-not-required

#1664 fix(stepper): remove rounded corners when nested in accordion
  .storybook/helpers/nesting-components.ts
  projects/angular/src/accordion/_accordion.clarity.scss
  projects/demo/src/app/stepper/stepper.demo.html
  tests/snapshots/chromium/accordion/nested-components--nested-components-core-dark.png
  tests/snapshots/chromium/accordion/nested-components--nested-components-core-light.png
  tests/snapshots/firefox/accordion/nested-components--nested-components-core-dark.png
  tests/snapshots/firefox/accordion/nested-components--nested-components-core-light.png
Labels: cla-not-required

#1661 fix(combobox): remove underline when no focus
  projects/angular/src/forms/combobox/combobox.ts
Labels: cla-not-required

#1668 fix(file-input): prevent validation error when `accept` is empty string
  projects/angular/src/forms/file-input/file-input-validator.spec.ts
  projects/angular/src/forms/file-input/file-input-validator.ts
Labels: cla-not-required

#1645 feat(datagrid): add string filter label
  .storybook/stories/datagrid/datagrid-column.stories.ts
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  projects/angular/src/data/datagrid/built-in/filters/datagrid-string-filter.ts
  projects/angular/src/utils/i18n/common-strings.default.ts
  projects/angular/src/utils/i18n/common-strings.interface.ts
  tests/snapshots/chromium/datagrid/column-filter--column-name-filter-opened-core-dark.png
  tests/snapshots/chromium/datagrid/column-filter--column-name-filter-opened-core-light.png
  tests/snapshots/chromium/datagrid/column-filter--column-number-filter-opened-core-dark.png
  tests/snapshots/chromium/datagrid/column-filter--column-number-filter-opened-core-light.png
  tests/snapshots/firefox/datagrid/column-filter--column-name-filter-opened-core-dark.png
  tests/snapshots/firefox/datagrid/column-filter--column-name-filter-opened-core-light.png
  tests/snapshots/firefox/datagrid/column-filter--column-number-filter-opened-core-dark.png
  tests/snapshots/firefox/datagrid/column-filter--column-number-filter-opened-core-light.png
Labels: cla-not-required, type:feat

#1670 fix(combobox): null reference ngControl
  projects/angular/src/forms/combobox/combobox.ts
Labels: cla-not-required

#1673 fix(datagrid): prevent injection error with `@angular/cdk@19.1.0`
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-virtual-scroll.directive.ts
Labels: cla-not-required

#1674 chore: update to actions/upload-artifact@v4
  .github/workflows/pr-build.yml
Labels: cla-not-required

#1671 chore(forms): remove nested status change subscription
  projects/angular/src/forms/common/if-control-state/if-control-state.service.spec.ts
  projects/angular/src/forms/common/if-control-state/if-control-state.service.ts
Labels: cla-not-required

#1655 feat(file-input): add file list (advanced file picker)
  .storybook/helpers/casing.helpers.ts
  .storybook/stories/file-input/advanced-file-input-states.stories.ts
  .storybook/stories/file-input/advanced-file-input.stories.ts
  .storybook/stories/file-input/file-input-states.stories.ts
  projects/angular/clarity.api.md
  projects/angular/src/forms/common/abstract-container.ts
  projects/angular/src/forms/common/providers/ng-control.service.ts
  projects/angular/src/forms/file-input/file-input-container.ts
  projects/angular/src/forms/file-input/file-input-validator-errors.ts
  projects/angular/src/forms/file-input/file-input-validator.ts
  projects/angular/src/forms/file-input/file-input.module.ts
  projects/angular/src/forms/file-input/file-input.ts
  projects/angular/src/forms/file-input/file-list.ts
  projects/angular/src/forms/file-input/file-messages-template.ts
  projects/angular/src/forms/file-input/file-messages.ts
  projects/angular/src/forms/file-input/index.ts
  projects/angular/src/forms/styles/_containers.clarity.scss
  projects/angular/src/forms/styles/_file-input.clarity.scss
  projects/demo/src/app/forms/controls/file.html
  projects/demo/src/app/forms/controls/file.ts
  tests/snapshots/chromium/file-input/advanced-file-input--compact-advanced-file-input-core-dark.png
  tests/snapshots/chromium/file-input/advanced-file-input--compact-advanced-file-input-core-light.png
  tests/snapshots/chromium/file-input/advanced-file-input--horizontal-advanced-file-input-core-dark.png
  tests/snapshots/chromium/file-input/advanced-file-input--horizontal-advanced-file-input-core-light.png
  tests/snapshots/chromium/file-input/advanced-file-input--vertical-advanced-file-input-core-dark.png
  tests/snapshots/chromium/file-input/advanced-file-input--vertical-advanced-file-input-core-light.png
  tests/snapshots/chromium/file-input/advanced-file-input-states--compact-advanced-file-input-states-core-dark.png
  tests/snapshots/chromium/file-input/advanced-file-input-states--compact-advanced-file-input-states-core-light.png
  tests/snapshots/chromium/file-input/advanced-file-input-states--horizontal-advanced-file-input-states-core-dark.png
  tests/snapshots/chromium/file-input/advanced-file-input-states--horizontal-advanced-file-input-states-core-light.png
  tests/snapshots/chromium/file-input/advanced-file-input-states--vertical-advanced-file-input-states-core-dark.png
  tests/snapshots/chromium/file-input/advanced-file-input-states--vertical-advanced-file-input-states-core-light.png
  tests/snapshots/firefox/file-input/advanced-file-input--compact-advanced-file-input-core-dark.png
  tests/snapshots/firefox/file-input/advanced-file-input--compact-advanced-file-input-core-light.png
  tests/snapshots/firefox/file-input/advanced-file-input--horizontal-advanced-file-input-core-dark.png
  tests/snapshots/firefox/file-input/advanced-file-input--horizontal-advanced-file-input-core-light.png
  tests/snapshots/firefox/file-input/advanced-file-input--vertical-advanced-file-input-core-dark.png
  tests/snapshots/firefox/file-input/advanced-file-input--vertical-advanced-file-input-core-light.png
  tests/snapshots/firefox/file-input/advanced-file-input-states--compact-advanced-file-input-states-core-dark.png
  tests/snapshots/firefox/file-input/advanced-file-input-states--compact-advanced-file-input-states-core-light.png
  tests/snapshots/firefox/file-input/advanced-file-input-states--horizontal-advanced-file-input-states-core-dark.png
  tests/snapshots/firefox/file-input/advanced-file-input-states--horizontal-advanced-file-input-states-core-light.png
  tests/snapshots/firefox/file-input/advanced-file-input-states--vertical-advanced-file-input-states-core-dark.png
  tests/snapshots/firefox/file-input/advanced-file-input-states--vertical-advanced-file-input-states-core-light.png
  tsconfig.json
Labels: cla-not-required, type:feat

#1678 fix(datagrid): expanded row replace details padding
  .storybook/stories/datagrid/datagrid-expandable-row.stories.ts
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  tests/snapshots/chromium/datagrid/expandable-rows--compact-expanded-column-replace-expandable-rows-core-dark.png
  tests/snapshots/chromium/datagrid/expandable-rows--compact-expanded-column-replace-expandable-rows-core-light.png
  tests/snapshots/chromium/datagrid/expandable-rows--compact-expanded-expandable-rows-core-dark.png
  tests/snapshots/chromium/datagrid/expandable-rows--compact-expanded-expandable-rows-core-light.png
  tests/snapshots/chromium/datagrid/expandable-rows--expanded-column-replace-expandable-rows-core-dark.png
  tests/snapshots/chromium/datagrid/expandable-rows--expanded-column-replace-expandable-rows-core-light.png
  tests/snapshots/chromium/datagrid/expandable-rows--expanded-expandable-rows-core-dark.png
  tests/snapshots/chromium/datagrid/expandable-rows--expanded-expandable-rows-core-light.png
  tests/snapshots/firefox/datagrid/expandable-rows--compact-expanded-column-replace-expandable-rows-core-dark.png
  tests/snapshots/firefox/datagrid/expandable-rows--compact-expanded-column-replace-expandable-rows-core-light.png
  tests/snapshots/firefox/datagrid/expandable-rows--compact-expanded-expandable-rows-core-dark.png
  tests/snapshots/firefox/datagrid/expandable-rows--compact-expanded-expandable-rows-core-light.png
  tests/snapshots/firefox/datagrid/expandable-rows--expanded-column-replace-expandable-rows-core-dark.png
  tests/snapshots/firefox/datagrid/expandable-rows--expanded-column-replace-expandable-rows-core-light.png
  tests/snapshots/firefox/datagrid/expandable-rows--expanded-expandable-rows-core-dark.png
  tests/snapshots/firefox/datagrid/expandable-rows--expanded-expandable-rows-core-light.png
Labels: cla-not-required, type:fix

#1681 fix(form-label): prevent id attribute from being removed
  projects/angular/src/forms/common/label.spec.ts
  projects/angular/src/forms/common/label.ts
Labels: cla-not-required

#1669 fix(breadcrumbs): fix spacing and remove unnecessary css properties
  projects/angular/src/layout/breadcrumbs/STYLES.md
  projects/angular/src/layout/breadcrumbs/_breadcrumbs.clarity.scss
  projects/angular/src/layout/breadcrumbs/_properties.breadcrumbs.scss
  projects/angular/src/layout/breadcrumbs/_variables.breadcrumbs.scss
  projects/angular/src/layout/breadcrumbs/breadcrumbs.spec.ts
  tests/snapshots/chromium/breadcrumbs/breadcrumbs--collapsed-core-dark.png
  tests/snapshots/chromium/breadcrumbs/breadcrumbs--collapsed-core-light.png
  tests/snapshots/chromium/breadcrumbs/breadcrumbs--initial-core-dark.png
  tests/snapshots/chromium/breadcrumbs/breadcrumbs--initial-core-light.png
  tests/snapshots/firefox/breadcrumbs/breadcrumbs--collapsed-core-dark.png
  tests/snapshots/firefox/breadcrumbs/breadcrumbs--collapsed-core-light.png
  tests/snapshots/firefox/breadcrumbs/breadcrumbs--initial-core-dark.png
  tests/snapshots/firefox/breadcrumbs/breadcrumbs--initial-core-light.png
Labels: cla-not-required

#1672 feat(datagrid): add overflow ellipsis
  .storybook/stories/datagrid/datagrid-action-overflow.stories.ts
  .storybook/stories/datagrid/datagrid-expandable-row.stories.ts
  .storybook/stories/datagrid/datagrid.stories.ts
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  projects/demo/src/app/datagrid/datagrid.demo.html
  projects/demo/src/app/datagrid/datagrid.demo.module.ts
  projects/demo/src/app/datagrid/datagrid.demo.routing.ts
  projects/demo/src/app/datagrid/density/density.html
  projects/demo/src/app/datagrid/density/density.ts
  tests/snapshots/chromium/datagrid/action-overflow--compact-overflow-ellipsis-action-overflow-core-dark.png
  tests/snapshots/chromium/datagrid/action-overflow--compact-overflow-ellipsis-action-overflow-core-light.png
  tests/snapshots/chromium/datagrid/datagrid--compact-overflow-ellipsis-core-dark.png
  tests/snapshots/chromium/datagrid/datagrid--compact-overflow-ellipsis-core-light.png
  tests/snapshots/chromium/datagrid/expandable-rows--compact-overflow-ellipsis-expandable-rows-core-dark.png
  tests/snapshots/chromium/datagrid/expandable-rows--compact-overflow-ellipsis-expandable-rows-core-light.png
  tests/snapshots/firefox/datagrid/action-overflow--compact-overflow-ellipsis-action-overflow-core-dark.png
  tests/snapshots/firefox/datagrid/action-overflow--compact-overflow-ellipsis-action-overflow-core-light.png
  tests/snapshots/firefox/datagrid/datagrid--compact-overflow-ellipsis-core-dark.png
  tests/snapshots/firefox/datagrid/datagrid--compact-overflow-ellipsis-core-light.png
  tests/snapshots/firefox/datagrid/expandable-rows--compact-overflow-ellipsis-expandable-rows-core-dark.png
  tests/snapshots/firefox/datagrid/expandable-rows--compact-overflow-ellipsis-expandable-rows-core-light.png
Labels: cla-not-required, type:feat

#1676 chore(date-picker): simplify `listenForControlValueChanges` method
  projects/angular/src/forms/common/wrapped-control.ts
  projects/angular/src/forms/datepicker/date-input.ts
Labels: cla-not-required

#1677 fix(file-input): allow advanced file input without file messages
  projects/angular/src/forms/file-input/file-list.ts
Labels: cla-not-required

#1651 chore: remove unnecessary `_dynamic` and `DynamicWrapper`
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/wrapped-cell.ts
  projects/angular/src/data/datagrid/wrapped-column.ts
  projects/angular/src/data/datagrid/wrapped-row.ts
  projects/angular/src/forms/checkbox/checkbox-wrapper.ts
  projects/angular/src/forms/common/abstract-container.ts
  projects/angular/src/forms/common/common.spec.ts
  projects/angular/src/forms/common/wrapped-control.spec.ts
  projects/angular/src/forms/common/wrapped-control.ts
  projects/angular/src/forms/radio/radio-wrapper.ts
  projects/angular/src/utils/host-wrapping/dynamic-wrapper.ts
  projects/angular/src/utils/host-wrapping/host-wrapper.ts
  projects/angular/src/utils/host-wrapping/host-wrapping.spec.ts
Labels: cla-not-required, type:chore

#1682 chore(ci): black duck integration
  .github/workflows/release-preview.yml
  .github/workflows/release.yml
  .releaserc.base.js
  .releaserc.release.js
  package-lock.json
  package.json
  scripts/execute-blackduck-scan.sh
Labels: cla-not-required

#1667 chore: extract visual diffs to temporary directory
  .github/workflows/pr-visual-snapshot-update-bot.yml
Labels: cla-not-required

#1640 fix(datepicker): accessibility fix for aria-hidden on focusable element error
  projects/angular/src/forms/datepicker/calendar.html
Labels: cla-not-required

#1691 fix(datagrid): key navigation when using num pad
  projects/angular/src/data/datagrid/datagrid-virtual-scroll.directive.spec.ts
  projects/angular/src/data/datagrid/datagrid.spec.ts
  projects/angular/src/data/datagrid/utils/key-navigation-grid.controller.ts
  projects/angular/src/utils/enums/keys.enum.ts
Labels: type:fix
