Repository vmware-clarity/ng-clarity, pull requests merged in 2025-08, with the labels that each got.

#1960 fix(datagrid): skeleton loading without removing row content
  projects/angular/src/data/datagrid/_datagrid.clarity.scss
  projects/angular/src/data/datagrid/datagrid-row.html
  projects/angular/src/utils/animations/_animations.clarity.scss
  projects/angular/src/utils/variables/_variables.global.scss
Labels: type:fix

#1963 fix(datagrid): calculate average height for pageUp and pageDown navigation
  projects/angular/src/data/datagrid/datagrid-virtual-scroll.directive.spec.ts
  projects/angular/src/data/datagrid/utils/key-navigation-grid.controller.spec.ts
  projects/angular/src/data/datagrid/utils/key-navigation-utils.ts
  projects/angular/src/utils/testing/helpers.spec.ts
Labels: type:fix

#1974 fix(links): increase active state specificity and interactieve stories
  .storybook/stories/link/link.stories.ts
  .storybook/stories/link/link.storybook.component.ts
  projects/angular/src/layout/nav/_links.clarity.scss
  tests/snapshots/chromium/link/link--link-active-dark-compact.png
  tests/snapshots/chromium/link/link--link-active-dark-default.png
  tests/snapshots/chromium/link/link--link-active-dark-regular.png
  tests/snapshots/chromium/link/link--link-active-light-compact.png
  tests/snapshots/chromium/link/link--link-active-light-default.png
  tests/snapshots/chromium/link/link--link-active-light-regular.png
  tests/snapshots/chromium/link/link--link-hover-dark-compact.png
  tests/snapshots/chromium/link/link--link-hover-dark-default.png
  tests/snapshots/chromium/link/link--link-hover-dark-regular.png
  tests/snapshots/chromium/link/link--link-hover-light-compact.png
  tests/snapshots/chromium/link/link--link-hover-light-default.png
  tests/snapshots/chromium/link/link--link-hover-light-regular.png
  tests/snapshots/chromium/link/link--link-visited-dark-compact.png
  tests/snapshots/chromium/link/link--link-visited-dark-default.png
  tests/snapshots/chromium/link/link--link-visited-dark-regular.png
  tests/snapshots/chromium/link/link--link-visited-hover-dark-compact.png
  tests/snapshots/chromium/link/link--link-visited-hover-dark-default.png
  tests/snapshots/chromium/link/link--link-visited-hover-dark-regular.png
  tests/snapshots/chromium/link/link--link-visited-hover-light-compact.png
  tests/snapshots/chromium/link/link--link-visited-hover-light-default.png
  tests/snapshots/chromium/link/link--link-visited-hover-light-regular.png
  tests/snapshots/chromium/link/link--link-visited-light-compact.png
  tests/snapshots/chromium/link/link--link-visited-light-default.png
  tests/snapshots/chromium/link/link--link-visited-light-regular.png
  tests/snapshots/firefox/link/link--link-active-dark-compact.png
  tests/snapshots/firefox/link/link--link-active-dark-default.png
  tests/snapshots/firefox/link/link--link-active-dark-regular.png
  tests/snapshots/firefox/link/link--link-active-light-compact.png
  tests/snapshots/firefox/link/link--link-active-light-default.png
  tests/snapshots/firefox/link/link--link-active-light-regular.png
  tests/snapshots/firefox/link/link--link-hover-dark-compact.png
  tests/snapshots/firefox/link/link--link-hover-dark-default.png
  tests/snapshots/firefox/link/link--link-hover-dark-regular.png
  tests/snapshots/firefox/link/link--link-hover-light-compact.png
  tests/snapshots/firefox/link/link--link-hover-light-default.png
  tests/snapshots/firefox/link/link--link-hover-light-regular.png
  tests/snapshots/firefox/link/link--link-visited-dark-compact.png
  tests/snapshots/firefox/link/link--link-visited-dark-default.png
  tests/snapshots/firefox/link/link--link-visited-dark-regular.png
  tests/snapshots/firefox/link/link--link-visited-hover-dark-compact.png
  tests/snapshots/firefox/link/link--link-visited-hover-dark-default.png
  tests/snapshots/firefox/link/link--link-visited-hover-dark-regular.png
  tests/snapshots/firefox/link/link--link-visited-hover-light-compact.png
  tests/snapshots/firefox/link/link--link-visited-hover-light-default.png
  tests/snapshots/firefox/link/link--link-visited-hover-light-regular.png
  tests/snapshots/firefox/link/link--link-visited-light-compact.png
  tests/snapshots/firefox/link/link--link-visited-light-default.png
  tests/snapshots/firefox/link/link--link-visited-light-regular.png
Labels: type:fix, auto-backport-to-main

#1969 fix(datagrid): virtual scroll header not scrolling
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid.ts
  projects/angular/src/data/datagrid/utils/key-navigation-grid.controller.ts
  projects/demo/src/app/datagrid/virtual-scroll-empty-rows/virtual-scroll-empty-rows.html
  projects/demo/src/app/datagrid/virtual-scroll-empty-rows/virtual-scroll-empty-rows.ts
Labels: type:fix, auto-backport-to-main

#1981 fix(datagrid): resizing columns in expanded rows not updating row details
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid.module.ts
  projects/angular/src/data/datagrid/helpers.spec.ts
  projects/angular/src/data/datagrid/index.ts
  projects/angular/src/data/datagrid/render/main-renderer.ts
  projects/angular/src/data/datagrid/render/row-detail-renderer.ts
  projects/angular/src/data/datagrid/render/row-renderer.ts
  projects/demo/src/app/datagrid/expandable-rows/expandable-rows.html
Labels: type:fix, auto-backport-to-main

#1986 fix(datagrid): virtual scroll subscriptions not initialized on after view init
  projects/angular/src/data/datagrid/datagrid.ts
Labels: type:fix, auto-backport-to-main

#1988 feat: remove deprecated baselineRem tokens
  projects/angular/src/forms/styles/_mixins.forms.scss
  projects/angular/src/forms/styles/_variables.forms.scss
  projects/angular/src/layout/grid/mixins/_grid-framework.scss
  projects/angular/src/layout/main-container/_layout.clarity.scss
  projects/angular/src/layout/nav/_subnav.clarity.scss
  projects/angular/src/layout/vertical-nav/_properties.vertical-nav.scss
  projects/angular/src/utils/_close.clarity.scss
  projects/angular/src/utils/_mixins.scss
  projects/angular/src/utils/variables/_variables.global.scss
  projects/angular/src/wizard/_wizard.clarity.scss
  projects/demo/src/app/accordion/accordion.demo.scss
  projects/demo/src/app/alert/alert.demo.scss
  projects/demo/src/app/breadcrumbs/breadcrumbs.demo.scss
  projects/demo/src/app/button-group/button-group.demo.scss
  projects/demo/src/app/buttons/buttons.demo.scss
  projects/demo/src/app/card/card.demo.scss
  projects/demo/src/app/color/color-palette.demo.scss
  projects/demo/src/app/color/color-shared.demo.scss
  projects/demo/src/app/datagrid/datagrid.demo.scss
  projects/demo/src/app/datepicker/datepicker.demo.scss
  projects/demo/src/app/dropdown/dropdown.demo.scss
  projects/demo/src/app/grid/grid.demo.scss
  projects/demo/src/app/iconography/iconography.demo.scss
  projects/demo/src/app/images/images.demo.scss
  projects/demo/src/app/layout/layout.demo.scss
  projects/demo/src/app/nav/headers.demo.scss
  projects/demo/src/app/popovers/popovers.demo.scss
  projects/demo/src/app/progress-bars/progress-bars.demo.scss
  projects/demo/src/app/signpost/signpost.demo.scss
  projects/demo/src/app/stepper/stepper.demo.scss
  projects/demo/src/app/tabs/tabs.demo.scss
  projects/demo/src/app/tooltips/tooltips.demo.scss
  projects/demo/src/app/tree-view/tree-view.demo.scss
  projects/demo/src/app/typography/font-autopsy.demo.scss
  projects/demo/src/app/typography/line-height.demo.scss
  projects/demo/src/app/vertical-nav/vertical-nav.demo.scss
  projects/demo/src/styles.scss
Labels: type:breaking-change
