Repository vmware-clarity/ng-clarity, pull requests merged in 2025-09, with the labels that each got.

#2001 fix(dropdown, combobox): remove min-height, add multi-line stories (backport to next)
  .storybook/stories/combobox/combobox.stories.ts
  .storybook/stories/combobox/combobox.storybook.component.ts
  projects/angular/src/popover/dropdown/_menu-mixins.clarity.scss
  tests/screenshot-options.ts
  tests/snapshots/chromium/combobox/combobox--opened-dark-compact.png
  tests/snapshots/chromium/combobox/combobox--opened-dark-default.png
  tests/snapshots/chromium/combobox/combobox--opened-dark-regular.png
  tests/snapshots/chromium/combobox/combobox--opened-light-compact.png
  tests/snapshots/chromium/combobox/combobox--opened-light-default.png
  tests/snapshots/chromium/combobox/combobox--opened-light-regular.png
  tests/snapshots/chromium/combobox/combobox--opened-multi-line-items-dark-compact.png
  tests/snapshots/chromium/combobox/combobox--opened-multi-line-items-dark-default.png
  tests/snapshots/chromium/combobox/combobox--opened-multi-line-items-dark-regular.png
  tests/snapshots/chromium/combobox/combobox--opened-multi-line-items-light-compact.png
  tests/snapshots/chromium/combobox/combobox--opened-multi-line-items-light-default.png
  tests/snapshots/chromium/combobox/combobox--opened-multi-line-items-light-regular.png
  tests/snapshots/firefox/combobox/combobox--opened-dark-compact.png
  tests/snapshots/firefox/combobox/combobox--opened-dark-default.png
  tests/snapshots/firefox/combobox/combobox--opened-dark-regular.png
  tests/snapshots/firefox/combobox/combobox--opened-light-compact.png
  tests/snapshots/firefox/combobox/combobox--opened-light-default.png
  tests/snapshots/firefox/combobox/combobox--opened-light-regular.png
  tests/snapshots/firefox/combobox/combobox--opened-multi-line-items-dark-compact.png
  tests/snapshots/firefox/combobox/combobox--opened-multi-line-items-dark-default.png
  tests/snapshots/firefox/combobox/combobox--opened-multi-line-items-dark-regular.png
  tests/snapshots/firefox/combobox/combobox--opened-multi-line-items-light-compact.png
  tests/snapshots/firefox/combobox/combobox--opened-multi-line-items-light-default.png
  tests/snapshots/firefox/combobox/combobox--opened-multi-line-items-light-regular.png
Labels: backport

#2011 chore(ci): update pr preview to checkout pr branch
  .github/workflows/pr-build.yml
  .github/workflows/pr-preview.yml
Labels: type:chore

#2020 chore: use github owned actions for artifacts and status
  .github/workflows/pr-preview.yml
  .github/workflows/pr-visual-snapshot-update-bot.yml
Labels: auto-backport-to-main

#2027 chore: remove unknown params from artifacts step
  .github/workflows/pr-preview.yml
  .github/workflows/pr-visual-snapshot-update-bot.yml
Labels: type:chore, auto-backport-to-next

#2029 chore: use compatible versions for download and upload artifacts
  .github/workflows/pr-preview.yml
  .github/workflows/pr-visual-snapshot-update-bot.yml
Labels: auto-backport-to-next

#2033 chore: add permissions and edit parameters on workflows
  .github/workflows/pr-preview.yml
  .github/workflows/pr-visual-snapshot-update-bot.yml
Labels: auto-backport-to-next

#2040 chore: use proper property names and permissions for workflows
  .github/workflows/pr-preview.yml
  .github/workflows/pr-visual-snapshot-update-bot.yml
Labels: auto-backport-to-next

#2044 chore: typo on check for docs comment bot
  .github/workflows/pr-comment-bot.yml
Labels: auto-backport-to-next

#2049 chore: use proper path for download artifact steps
  .github/workflows/pr-preview.yml
Labels: type:chore, auto-backport-to-next

#1617 feat(datagrid): add ability to unsort datagrid colums
  .storybook/stories/datagrid/datagrid-column.stories.ts
  projects/angular/clarity.api.md
  projects/angular/src/data/datagrid/datagrid-column.spec.ts
  projects/angular/src/data/datagrid/datagrid-column.ts
  projects/demo/src/app/datagrid/sorting/sorting.html
  projects/demo/src/app/datagrid/sorting/sorting.ts
  tests/snapshots/chromium/datagrid/column-filter--column-filter-dark-compact.png
  tests/snapshots/chromium/datagrid/column-filter--column-filter-dark-default.png
  tests/snapshots/chromium/datagrid/column-filter--column-filter-dark-regular.png
  tests/snapshots/chromium/datagrid/column-filter--column-filter-light-compact.png
  tests/snapshots/chromium/datagrid/column-filter--column-filter-light-default.png
  tests/snapshots/chromium/datagrid/column-filter--column-filter-light-regular.png
  tests/snapshots/chromium/datagrid/column-filter--column-name-filter-opened-dark-compact.png
  tests/snapshots/chromium/datagrid/column-filter--column-name-filter-opened-dark-default.png
  tests/snapshots/chromium/datagrid/column-filter--column-name-filter-opened-dark-regular.png
  tests/snapshots/chromium/datagrid/column-filter--column-name-filter-opened-light-compact.png
  tests/snapshots/chromium/datagrid/column-filter--column-name-filter-opened-light-default.png
  tests/snapshots/chromium/datagrid/column-filter--column-name-filter-opened-light-regular.png
  tests/snapshots/chromium/datagrid/column-filter--column-number-filter-opened-dark-compact.png
  tests/snapshots/chromium/datagrid/column-filter--column-number-filter-opened-dark-default.png
  tests/snapshots/chromium/datagrid/column-filter--column-number-filter-opened-dark-regular.png
  tests/snapshots/chromium/datagrid/column-filter--column-number-filter-opened-light-compact.png
  tests/snapshots/chromium/datagrid/column-filter--column-number-filter-opened-light-default.png
  tests/snapshots/chromium/datagrid/column-filter--column-number-filter-opened-light-regular.png
  tests/snapshots/firefox/datagrid/column-filter--column-filter-dark-compact.png
  tests/snapshots/firefox/datagrid/column-filter--column-filter-dark-default.png
  tests/snapshots/firefox/datagrid/column-filter--column-filter-dark-regular.png
  tests/snapshots/firefox/datagrid/column-filter--column-filter-light-compact.png
  tests/snapshots/firefox/datagrid/column-filter--column-filter-light-default.png
  tests/snapshots/firefox/datagrid/column-filter--column-filter-light-regular.png
  tests/snapshots/firefox/datagrid/column-filter--column-name-filter-opened-dark-compact.png
  tests/snapshots/firefox/datagrid/column-filter--column-name-filter-opened-dark-default.png
  tests/snapshots/firefox/datagrid/column-filter--column-name-filter-opened-dark-regular.png
  tests/snapshots/firefox/datagrid/column-filter--column-name-filter-opened-light-compact.png
  tests/snapshots/firefox/datagrid/column-filter--column-name-filter-opened-light-default.png
  tests/snapshots/firefox/datagrid/column-filter--column-name-filter-opened-light-regular.png
  tests/snapshots/firefox/datagrid/column-filter--column-number-filter-opened-dark-compact.png
  tests/snapshots/firefox/datagrid/column-filter--column-number-filter-opened-dark-default.png
  tests/snapshots/firefox/datagrid/column-filter--column-number-filter-opened-dark-regular.png
  tests/snapshots/firefox/datagrid/column-filter--column-number-filter-opened-light-compact.png
  tests/snapshots/firefox/datagrid/column-filter--column-number-filter-opened-light-default.png
  tests/snapshots/firefox/datagrid/column-filter--column-number-filter-opened-light-regular.png
Labels: cla-not-required, type:feat, type:breaking-change, v18-candidate
